In [ ]:
import pandas as pd
import numpy as np

Importing Pandas and Numpy into my Notebook using 'import'.

In [ ]:
df=pd.read_csv('/content/sports_uncleaned_5000rows (2).csv')

Reading my dataset using pandas library

In [ ]:
df

,Player_ID,Match_ID,Player_Name,Team,Country,Age,Gender,Coach_Name,Sport_Type,Match_Date,...,Feedback_Score,Fan_ID,Payment_Mode,Fan_Purchase_Amount,Minutes_Played,Matches_Played,Fan_Email,Fan_Phone,Fan_Count,Merch_ID
0,1102,5082,NaN,CSK,india,17.0,male,Rahul Dravid,Football,13-02-2023,...,NaN,81006,NaN,8970.0,1.0,3,NaN,1.234500e+04,2337,78
1,1179,5034,Virat,KKR,india,23.0,Male,NaN,Tennis,05-12-2022,...,NaN,80048,,NaN,NaN,11,NaN,NaN,805,156
2,1092,5195,Rohit,RCB,sri lanka,69.0,female,NaN,footbal,30-08-2020,...,NaN,81850,creadit card,NaN,NaN,23,xyz@,NaN,3039,42
3,1014,5068,Bumrah,KKR,NaN,60.0,mal,,Basketball,22-01-2024,...,NaN,81929,creadit card,NaN,12.0,2,abc@gmail.com,NaN,278,62
4,1106,5128,Joe Root,Lakers,England,39.0,femal,John Smith,Cricket,29-07-2020,...,6.0,82132,creadit card,14920.0,NaN,17,user@yahoo,1.000000e+10,1405,125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1198,5139,NaN,NaN,sri lanka,29.0,mal,NaN,Football,19-10-2022,...,NaN,82239,,9094.0,90.0,7,user@yahoo,9.876543e+09,2039,99
4996,1194,5100,Bumrah,NaN,india,57.0,Mle,NaN,NaN,05-12-2023,...,6.0,84816,,843.0,7.0,8,user@yahoo,1.000000e+10,2199,191
4997,1108,5022,Smith,Barcelona,England,34.0,male,NaN,Cricket,10-06-2021,...,NaN,82859,credit card,NaN,NaN,22,NaN,NaN,4062,29
4998,1046,5199,Rohit,CSK,Australia,15.0,Other,NaN,Football,22-09-2022,...,NaN,82393,cash,4620.0,NaN,9,xyz@,NaN,3238,150
4999,1083,5111,Bumrah,KKR,England,43.0,mal,John Smith,Football,05-12-2023,...,4.0,84568,,NaN,NaN,5,abc@gmail.com,1.234500e+04,1493,93

In [ ]:
print(df.to_string())

      Player_ID  Match_ID Player_Name       Team    Country   Age  Gender    Coach_Name  Sport_Type  Match_Date  Match_Fee   Bonus  Sponsorship_Amount  Score  Assists  Goals  Wickets  Ticket_Sales  Merch_Sales      Venue Weather Win_Status  Rating  Feedback_Score  Fan_ID  Payment_Mode  Fan_Purchase_Amount  Minutes_Played  Matches_Played      Fan_Email     Fan_Phone  Fan_Count  Merch_ID
0          1102      5082         NaN        CSK      india  17.0    male  Rahul Dravid    Football  13-02-2023        NaN     NaN            287941.0     13        0      1        5       37356.0          NaN    Chennai                NaN     4.6             NaN   81006           NaN               8970.0             1.0               3            NaN  1.234500e+04       2337        78
1          1179      5034       Virat        KKR      india  23.0    Male           NaN      Tennis  05-12-2022        NaN     NaN                 NaN     90        9      7        0       18655.0       7745.0        NaN               Draw     9.9             NaN   80048                                NaN             NaN              11            NaN           NaN        805       156
2          1092      5195      Rohit         RCB  sri lanka  69.0  female           NaN     footbal  30-08-2020        NaN  -457.0                 NaN    152        3      6        0           NaN       2843.0        NaN   Sunny       win      NaN             NaN   81850  creadit card                  NaN             NaN              23           xyz@           NaN       3039        42
3          1014      5068      Bumrah        KKR        NaN  60.0     mal                Basketball  22-01-2024        NaN    67.0           1044184.0     76        9      8        0           NaN      14535.0        NaN   rainy       DRAW     NaN             NaN   81929  creadit card                  NaN            12.0               2  abc@gmail.com           NaN        278        62
4          1106      5128    Joe Root     Lakers    England  39.0   femal    John Smith     Cricket  29-07-2020        NaN   870.0                 NaN     84        4      7        5           NaN          NaN                          DRAW     NaN             6.0   82132  creadit card              14920.0             NaN              17     user@yahoo  1.000000e+10       1405       125
5          1071      5195    Joe Root     Lakers  australia  20.0   Other           NaN    Football  12-05-2023      387.0     NaN           1246406.0    108        1      3        3           NaN          NaN     Mumbai   Sunny       Lose     NaN             NaN   81525                             9393.0            33.0              28            NaN  1.000000e+10        787       180
6          1188      5139       Smith        KKR  Sri Lanka  58.0   Other           NaN    Football  23-01-2024        NaN     NaN           1394214.0     30        4      1        1           NaN          NaN        NaN               Draw     2.4             NaN   80328           NaN                  NaN            62.0              11  abc@gmail.com  9.876543e+09       1332        22
7          1020      5187       Virat        CSK  Australia  33.0     Mle           NaN   basktball  07-08-2021        NaN     NaN                 NaN    121        9      1        3        8839.0       3104.0    Chennai  Cloudy        Win     6.9             1.0   82657   credit card                  NaN            66.0              23     user@yahoo  1.000000e+10       4372        57
8          1102      5026         NaN     Lakers  sri lanka  10.0     Mle  Rahul Dravid     Cricket  19-05-2022        NaN  2925.0            730707.0    106        3      1        5       30417.0          NaN    Kolkata   Sunny       Lose     NaN             3.0   84529           upi              17522.0           107.0              23            NaN  9.876543e+09       3147        96
9          1121      5055      Hardik        RCB      INDIA  30.0  Female                       NaN  08-02-2024      761.0     NaN                 NaN     53        7      5        3        3528.0          NaN  Bangalore     NaN       Lose     5.8             NaN   80587  creadit card               5898.0             NaN              18     user@yahoo  1.234500e+04       2345       139
10         1074      5022       Virat        KKR      India  11.0     mal    John Smith      Tennis  03-12-2023        NaN     NaN            835031.0    132        0      6        2       27302.0      13721.0  Bangalore  Cloudy        Win     NaN             3.0   83205                              240.0            59.0              12     user@yahoo           NaN       3449       142
11         1087      5152              Barcelona      INDIA  66.0    Male  Rahul Dravid  Basketball  24-04-2022        NaN  2029.0            330413.0    140        4      5        5           NaN          NaN     Mumbai     NaN        Win     NaN             NaN   81598   credit card                  NaN             NaN              15     user@yahoo  1.000000e+10        432        31
12         1116      5020     Ronaldo     Lakers  Australia   NaN  female           NaN         NaN         NaN      909.0     NaN                 NaN    155        9      1        0       30456.0          NaN  Bangalore     NaN       Lose     NaN             NaN   83851           NaN                  NaN            91.0               7            NaN  1.000000e+10       1009         4
13         1099      5060      Rohit      Lakers    england  66.0     mal           NaN         NaN         NaN     5841.0     NaN            112038.0     42        0      3        1           NaN          NaN        NaN   Sunny        Win     NaN             NaN   82472   credit card                  NaN             NaN              26            NaN  1.000000e+10       3849       109
14         1103      5062      Rohit          MI  sri lanka  38.0   femal           NaN   basktball  14-04-2020    -1593.0     NaN            272289.0     88        9      2        2           NaN          NaN    Kolkata     NaN        Win     NaN             NaN   82817   credit card               3764.0             NaN              26            NaN  1.234500e+04        316       150
15         1151      5121       Virat        RCB  australia  59.0   femal  Rahul Dravid  Basketball         NaN     3145.0     NaN            478307.0    114        9      3        2       54803.0       7150.0  Bangalore                NaN     8.7             0.0   84607                             8135.0             NaN               5  abc@gmail.com           NaN       4216       118
16         1130      5051    Joe Root        RCB  sri lanka  61.0    male                       NaN  11-01-2022        NaN  1485.0                 NaN     98        3      4        5       34862.0          NaN     Mumbai  Cloudy       DRAW     8.1             3.0   81408          cash               9035.0            56.0               9            NaN  9.876543e+09       1365        93
17         1149      5087    Joe Root  Barcelona    England  66.0    Male                            05-12-2023        NaN     NaN                 NaN     46        7      6        4       17867.0          NaN        NaN   rainy       Draw     7.5             NaN   81011           upi                  NaN             NaN              24            NaN  9.876543e+09       4399        99
18         1052      5152      Hardik     Lakers    England  50.0  Female    John Smith     footbal  05-12-2023        NaN  1846.0                 NaN     70        0      8        0       39669.0      18222.0        NaN  Cloudy        NaN     NaN             NaN   84659    netbanking               7545.0             NaN               9  abc@gmail.com  1.234500e+04        935       192
19         1001      5054                    NaN  Sri Lanka  53.0     Mle           NaN      Tennis  03-03-2023        NaN  1890.0            996837.0    165        1      1        1           NaN          NaN      Delhi   rainy        Win     NaN             NaN   84398          cash                  NaN            15.0              28           xyz@           NaN       3518        77
20         1087      5045      Rohit          MI        NaN  56.0  Female    John Smith    Football  07-07-2023        NaN     NaN            597941.0     66        0      7        1           NaN          NaN        NaN   Rainy       lose     5.2             1.0   84044  creadit card              12815.0            65.0               5            NaN  1.234500e+04       3787        83
21         1157      5031      Hardik  Barcelona      india  61.0  Female           NaN  Basketball  25-12-2020     3635.0     NaN                 NaN     61        6      2        1           NaN          NaN        NaN   Sunny       DRAW     7.0             3.0   81329    netbanking                  NaN             NaN               7           xyz@  1.234500e+04       2768       115
22         1037      5054    Joe Root        CSK    england  45.0     Mle    John Smith              05-12-2023        NaN     NaN            811576.0    108        1      8        5       14156.0      10543.0        NaN   Sunny        Win     8.2             3.0   82604          cash              10842.0           112.0              17           xyz@           NaN        495        61
23         1129      5095         NaN        NaN      india  14.0  Female  Rahul Dravid  Basketball  21-08-2022        NaN   122.0           1389593.0    166        0      9        0           NaN       8106.0        NaN     NaN        Win     8.1             NaN   82023                             2254.0             NaN              16  abc@gmail.com  1.000000e+10       3592       100
24         1191      5132      Hardik        NaN  Sri Lanka  62.0     Mle           NaN   basktball  20-05-2023     3154.0  2387.0                 NaN     36        5      3        5       32120.0      10726.0    Kolkata   rainy       Draw     6.8             NaN   84507  creadit card               5780.0             NaN              25     user@yahoo  1.000000e+10       2232       134
25         1187      5035     Ronaldo        KKR    england  41.0  female           NaN      Tennis  13-10-2023    -1689.0   833.0            613316.0    118        5      2        1       33543.0          NaN  Bangalore     NaN       lose     5.0             7.0   83185           NaN                  NaN            27.0               9  abc@gmail.com  1.234500e+04       4018        79
26         1020      5109    Joe Root        CSK  sri lanka  13.0  female           NaN      Tennis  14-11-2021     2632.0     NaN                 NaN     85        9      9        3           NaN       7054.0              Rainy       win      NaN             NaN   84603          cash                  NaN             NaN               1            NaN           NaN       2935       196
27         1160      5176       Dhoni     Lakers  sri lanka  50.0     mal                   footbal  14-05-2022        NaN  2809.0                 NaN    125        1      5        3       51501.0       6375.0    Kolkata     NaN        NaN     3.2             1.0   84151                                NaN            58.0              11            NaN  1.234500e+04       4808         6
28         1057      5105                 Lakers      India  49.0   Other           NaN     footbal  13-07-2022    -1536.0  1926.0                 NaN    135        0      9        0        7536.0          NaN  Bangalore                NaN     9.1             NaN   82593  creadit card               6474.0            56.0              19           xyz@  1.000000e+10       4445        66
29         1021      5057      Bumrah        RCB      INDIA  28.0   femal           NaN              08-12-2020        NaN  -390.0                 NaN     51        9      8        1       55153.0       4251.0    Kolkata     NaN       lose     8.7             5.0   83341   credit card               1380.0             NaN               9            NaN  9.876543e+09       2367       164
30         1088      5038      Rohit      Lakers        NaN  66.0    Male  Rahul Dravid      Tennis  20-10-2023        NaN     NaN                 NaN     90        2      6        5           NaN          NaN      Delhi     NaN        NaN     NaN             2.0   80195           NaN                  NaN             1.0               8           xyz@  1.234500e+04       2584       143
31         1048      5079       Smith  Barcelona  australia  41.0    male           NaN         NaN  12-06-2021     1620.0     NaN                 NaN     32        9      3        4       28270.0          NaN        NaN  Cloudy        Win     9.5             NaN   81790  creadit card              15884.0             0.0              15            NaN  1.000000e+10        905        76
32         1058      5096     Ronaldo        CSK      INDIA  44.0     mal    John Smith      Tennis  05-12-2023     -765.0  1536.0                 NaN     80        4      2        4       17818.0          NaN    Chennai   Rainy       win      8.5             2.0   81106           upi              15918.0            81.0               6            NaN           NaN       3227        40
33         1169      5112       Messi  Barcelona  australia  44.0  female           NaN         NaN  05-12-2023     1427.0     NaN            369706.0     41        5      9        4       38521.0       8764.0     Mumbai     NaN       win      NaN             3.0   82789    netbanking              19875.0             6.0               8           xyz@  9.876543e+09       1827       169
34         1187      5060      Bumrah        CSK      India  52.0    male                            05-12-2023        NaN     NaN            446653.0    111        2      3        3           NaN       2084.0    Chennai  Cloudy        NaN     NaN             NaN   82184           upi               8796.0            19.0              24  abc@gmail.com  1.000000e+10       3722         7
35         1014      5136       Smith        KKR        NaN  42.0    male                       NaN  21-03-2020        NaN  2267.0            474567.0    125        8      2        5           NaN      13454.0        NaN     NaN        NaN     NaN             1.0   80538          cash                  NaN           118.0              24     user@yahoo  9.876543e+09       2580        22
36         1189      5005    Joe Root        NaN      India  41.0  female           NaN   basktball  20-01-2022        NaN   189.0                 NaN    154        4      2        4           NaN          NaN     Mumbai   rainy        Win     7.8             1.0   84784  creadit card               7650.0            38.0              23     user@yahoo           NaN       4597        72
37         1189      5108       Messi         MI  Australia  33.0    male           NaN              19-01-2021    -1896.0   -88.0               740.0    135        1      8        1           NaN       8066.0    Chennai     NaN       Draw     NaN             NaN   80718                             3377.0             NaN               5            NaN  1.234500e+04       1515       106
38         1174      5034       Virat        NaN    england  56.0  Female  Rahul Dravid   basktball  08-06-2023        NaN  2831.0                 NaN    150        9      3        1       14287.0          NaN    Chennai     NaN       Draw     NaN             6.0   83995          cash               5257.0           115.0              29            NaN  1.234500e+04       4622       139
39         1189      5038       Virat  Barcelona  Sri Lanka  42.0  female                       NaN  17-05-2022        NaN     NaN            786510.0    105        5      8        4        1440.0      14806.0        NaN     NaN       DRAW     NaN             1.0   80305    netbanking                  NaN             NaN              26  abc@gmail.com  1.234500e+04       4806       130
40         1050      5149     Ronaldo         MI        NaN  49.0   Other           NaN  Basketball  20-03-2023      646.0     NaN             63586.0    124        7      9        2       48051.0          NaN      Delhi               DRAW     8.1             0.0   80387   credit card                  NaN            56.0               9           xyz@  9.876543e+09       3003        30
41         1107      5168       Virat         MI  sri lanka  20.0     Mle           NaN  Basketball  05-07-2022     3412.0  2620.0            262307.0    112        5      4        4       32080.0       9882.0                NaN        NaN     3.3             1.0   80724          cash              13804.0             NaN               6            NaN  1.234500e+04        111        68
42         1054      5117       Messi        CSK  sri lanka  26.0   femal           NaN   basktball  12-05-2023        NaN     NaN                 NaN     63        3      6        2           NaN          NaN    Chennai   Sunny        Win     NaN             0.0   82596         upiid                  NaN             NaN              17     user@yahoo  9.876543e+09       1672       181
43         1063      5004       Messi        CSK      india  28.0   femal           NaN   basktball  10-01-2020     4086.0  1343.0           1033361.0    122        5      4        0       10987.0      12869.0      Delhi   Rainy        NaN     7.1             NaN   82435          cash              11031.0             NaN              10     user@yahoo           NaN       2302        89
44         1130      5169                    CSK      INDIA  16.0     mal           NaN      Tennis  13-10-2022        NaN  2090.0                 NaN    113        7      0        0           NaN          NaN             Cloudy        Win     NaN             NaN   82340  creadit card              12543.0             NaN               0     user@yahoo  9.876543e+09       1650       149
45         1050      5086      Bumrah  Barcelona  Sri Lanka  36.0  Female           NaN    Football  26-07-2022     -473.0  2706.0                 NaN     19        7      1        1           NaN      13141.0        NaN   rainy       lose     2.1             7.0   80178          cash                  NaN            52.0              28            NaN  1.234500e+04       4395       153
46         1134      5075      Rohit          MI  sri lanka  56.0  Female           NaN     Cricket  13-01-2022     2472.0  2731.0                 NaN     15        9      4        5           NaN          NaN    Chennai  Cloudy       win      9.2             NaN   81903           upi                  NaN            26.0              20            NaN           NaN       2474        73
47         1020      5194       Dhoni        KKR    england  20.0     Mle           NaN   basktball  11-03-2022        NaN  -470.0           1403262.0    144        1      5        3        4808.0         16.0        NaN   Sunny        Win     NaN             6.0   81704  creadit card               9720.0             NaN              23  abc@gmail.com           NaN       3995        72
48         1072      5157      Hardik        NaN  sri lanka  26.0    Male           NaN         NaN  05-12-2023      450.0     NaN                 NaN     18        7      6        5       16432.0          NaN              Sunny       lose     NaN             NaN   83383           NaN               5504.0             NaN              18           xyz@  1.234500e+04       1890       133
49         1166      5056       Virat         MI    england  68.0     Mle                Basketball  12-03-2020        NaN  1015.0           1361568.0    119        5      1        1        8512.0          NaN              rainy        Win     NaN             6.0   84175                            16425.0            67.0              22           xyz@  9.876543e+09        306        66

In [ ]:
df.duplicated().sum()

np.int64(0)

Identifying any Duplicated rows are there in my dataset.

In [ ]:
df['Match_Fee']=df['Match_Fee'].fillna(df['Match_Fee'].mean())

Filling with mean(average) values in the 'Match_Fee' column in the Null values.

In [ ]:
df['Match_Fee']=df['Match_Fee'].round().astype(int)

Changing the datatype og "Match_Fee" column into integer.

In [ ]:
for x in df.index:
  if df.loc[x,'Match_Fee']<0:
    df.drop(x,inplace=True)

Remove rows where 'Match_Fee' column has values less than 0 using for loop function.

In [ ]:
df['Match_Fee'].isna().sum()

np.int64(0)

In [ ]:
df['Bonus']=df['Bonus'].fillna(df['Match_Fee'].mean())

Filling with mean(average) values in the 'Bonus' column in the Null values.

In [ ]:
df['Bonus']=df['Bonus'].round().astype(int)

Changing the datatype og "Bonus" column into integer.

In [ ]:
for x in df.index:
  if df.loc[x,'Bonus']<0:
    df.drop(x,inplace=True)

Remove rows where 'Bonus' column has values in negative i.e less than 0 using for loop function.

In [ ]:
df['Bonus'].isna().sum()

np.int64(0)

In [ ]:
df['Age']=df['Age'].fillna(df['Age'].mean())

Filling with mean(average) values in the 'Age' column in the Null values.

In [ ]:
df['Age']=df['Age'].round().astype(int)

Changing the datatype og "Age" column into integer.

In [ ]:
df['Age'].isna().sum()

np.int64(0)

In [ ]:
for x in df.index:
  if df.loc[x,'Age']<10 or df.loc[x,'Age']>60:
    df.drop(x,inplace=True)

Remove rows where 'Age' column has values Less than 10 and greater than 60 using for loop function.

In [ ]:
df['Feedback_Score']=df['Feedback_Score'].fillna(df['Feedback_Score'].mean())

Filling with mean(average) values in the 'feedback_Score' column in the Null values.

In [ ]:
df['Feedback_Score']=df['Feedback_Score'].round().astype(int)

Changing the datatype og "Feedback_Score" column into integer

In [ ]:
for x in df.index:
  if df.loc[x,'Feedback_Score']<=0 or df.loc[x,'Feedback_Score']>5:
    df.drop(x,inplace=True)

Remove rows where 'Feedback_Score' column has values Outside of 1-5, which is less than 1 and greater than 5 using for loop function.

In [ ]:
df['Ticket_Sales']=df['Ticket_Sales'].fillna(df['Ticket_Sales'].mean())

Filling with mean(average) values in the 'Tick_Sales' column in the Null values.

In [ ]:
df['Ticket_Sales']=df['Ticket_Sales'].round().astype(int)

Changing the datatype og "Ticket_Sales" column into integer

In [ ]:
for x in df.index:
  if df.loc[x,'Ticket_Sales']>50000:
    df.drop(x,inplace=True)

Remove rows where 'Ticket_Sales' column has values greater than 50000 using for loop function.

In [ ]:
df['Player_Name'] = (df['Player_Name'].str.strip())

Removing extra spaces in the 'Player_Name' column values using strip().

In [ ]:
df['Player_Name'] = df['Player_Name'].replace(r'^\s*$', 'Anonymous', regex=True)

Changing all type possible empty, wrong values into 'Anonymous' using replace().

In [ ]:
df['Player_Name']=df['Player_Name'].fillna(method='bfill')

/tmp/ipython-input-1787172918.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Player_Name']=df['Player_Name'].fillna(method='bfill')

Filling missing null values using backfill method.

In [ ]:
df['Player_Name'].unique()

array(['Virat', 'Bumrah', 'Joe Root', 'Smith', 'Hardik', 'Ronaldo',
       'Anonymous', 'Rohit', 'Messi', 'Dhoni'], dtype=object)

Checking the 'Player_Name' column values has unique values.

In [ ]:
df['Player_Name'].isna().sum()

np.int64(0)

In [ ]:
df['Team']=df['Team'].fillna(method='ffill')

/tmp/ipython-input-2775853044.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Team']=df['Team'].fillna(method='ffill')

Filling missing null values using frontfill method.

In [ ]:
df['Team'].isna().sum()

np.int64(0)

In [ ]:
df['Gender'] = (df['Gender'].str.strip().str.title())

Removing extra spaces in column values and column name in the 'Gender' column.

In [ ]:
df['Gender'] = (df['Gender'].replace({'Mal': 'Male', 'Mle': 'Male', 'Femal': 'Female'}))

Correcting the wrong typos in 'Gender' column using replace ().

In [ ]:
df['Gender'].unique()

array(['Male', 'Other', 'Female'], dtype=object)

In [ ]:
df['Gender'].isna().sum()

np.int64(0)

In [ ]:
df['Country'] = (df['Country'].str.strip().str.title())

Removing extra spaces in column values and column name in the 'Country' column.

In [ ]:
df['Country'] = df['Country'].fillna(df['Country'].mode()[0])

Filling the missing null values in the 'Country' column using mode(most repeated value) function.

In [ ]:
df['Country'].unique()

array(['India', 'Australia', 'Sri Lanka', 'England'], dtype=object)

In [ ]:
df['Country'].isna().sum()

np.int64(0)

In [ ]:
m = df.groupby('Player_Name')['Country'].nunique()
m

Player_Name
Anonymous    4
Bumrah       4
Dhoni        4
Hardik       4
Joe Root     4
Messi        4
Rohit        4
Ronaldo      4
Smith        4
Virat        4
Name: Country, dtype: int64

Identifying player names appearing with multiple countries using group by()

In [ ]:
df['Coach_Name'] = (df['Coach_Name'].str.strip().str.title())

Removing extra spaces in column values and column name in the 'Coach_Name' column.

In [ ]:
df['Coach_Name']=df['Coach_Name'].replace({'':'Unknown Coach'})

Filling the empty values(' ') with 'unknown coach' in the coach_name column using replace().

In [ ]:
df['Coach_Name'] = df['Coach_Name'].fillna(df['Coach_Name'].mode()[0])

Filling the missing null values in the 'Coach_Name' column using mode(most repeated value) function.

In [ ]:
df['Coach_Name'].unique()

array(['Rahul Dravid', 'Unknown Coach', 'John Smith'], dtype=object)

In [ ]:
df['Coach_Name'].value_counts()

Coach_Name
Unknown Coach    1718
John Smith        410
Rahul Dravid      392
Name: count, dtype: int64

In [ ]:
df['Coach_Name'].isna().sum()

np.int64(0)

In [ ]:
df['Sport_Type'] = (df['Sport_Type'].replace({'footbal': 'Football', 'basktball': 'Basketball', '': 'other',' ':'other'}))

Identifying the wrong typos and fills with coreect sentences using replce() in the 'Sport_Type' column.

In [ ]:
df['Sport_Type'] = df['Sport_Type'].fillna(df['Sport_Type'].mode()[0])

Filling the missing null values in the 'Sport_Type' column using mode(most repeated value) function.

In [ ]:
df['Sport_Type'].unique()

array(['Football', 'Tennis', 'Basketball', 'Cricket', 'other'],
      dtype=object)

In [ ]:
df['Sport_Type'].isna().sum()

np.int64(0)

In [ ]:
print(df['Sponsorship_Amount'].to_string())

0        287941.0
1             NaN
3       1044184.0
5       1246406.0
6       1394214.0
7             NaN
8        730707.0
9             NaN
10       835031.0
12            NaN
18            NaN
19       996837.0
20       597941.0
22       811576.0
23      1389593.0
26            NaN
31            NaN
33       369706.0
34       446653.0
35       474567.0
36            NaN
39       786510.0
41       262307.0
43      1033361.0
44            NaN
46            NaN
48            NaN
50       220096.0
51      1079252.0
53      1243952.0
54            NaN
56            NaN
58      1239848.0
60       250729.0
63       713588.0
67            NaN
68            NaN
69       369408.0
70       555903.0
72       683275.0
74            NaN
79       534886.0
80            NaN
82            NaN
85      1434217.0
87            NaN
89            NaN
91      1156111.0
92            NaN
94       597878.0
96            NaN
98            NaN
99            NaN
101       96295.0
102           NaN
103           NaN
104     1056510.0
108           NaN
109      907655.0
110           NaN
112           NaN
114           NaN
115           NaN
116     1197282.0
117           NaN
119           NaN
121     1241131.0
126      280722.0
127     1341947.0
129           NaN
131           NaN
133           NaN
135       92163.0
137      146222.0
143     1193620.0
148           NaN
149      499910.0
150     1400441.0
153      990326.0
154      147087.0
155           NaN
156           NaN
157           NaN
162           NaN
164     1212086.0
165           NaN
166           NaN
167           NaN
168      570811.0
172           NaN
174      495605.0
175           NaN
180           NaN
183           NaN
184      337452.0
186      515844.0
187           NaN
188           NaN
190        -501.0
192      910559.0
197           NaN
198     1443871.0
200     1407024.0
201           NaN
204      475305.0
210     1482470.0
211        4237.0
213           NaN
215      863752.0
216           NaN
218           NaN
221     1271596.0
222     1475892.0
223     1014936.0
224           NaN
225           NaN
226           NaN
227      585232.0
229           NaN
230      116736.0
235           NaN
236           NaN
237      230285.0
239           NaN
240     1002591.0
242           NaN
244      693413.0
245           NaN
246           NaN
251           NaN
253      259726.0
256           NaN
260           NaN
263      625961.0
264           NaN
266           NaN
268           NaN
269           NaN
270           NaN
272     1236422.0
274       18786.0
275           NaN
277           NaN
279      622188.0
280           NaN
282           NaN
283      434604.0
284     1060457.0
288           NaN
289      346700.0
290     1344832.0
293       55063.0
295           NaN
296      918324.0
297     1375857.0
300      835627.0
304           NaN
308      737600.0
313      722773.0
314      473995.0
315           NaN
317      595048.0
318      793315.0
319      362824.0
320           NaN
321           NaN
322      448845.0
323           NaN
324     1371652.0
326      683817.0
327           NaN
330     1150486.0
331     1101083.0
334      135601.0
335           NaN
336      160098.0
338           NaN
342      770597.0
343      490041.0
344           NaN
345           NaN
347      537669.0
349           NaN
352           NaN
353           NaN
356       67734.0
361      576482.0
362      747497.0
365     1308374.0
367        5052.0
370      261441.0
371     1003624.0
375           NaN
376           NaN
377     1345947.0
378      924942.0
379     1015137.0
380           NaN
381     1427606.0
383           NaN
384           NaN
386           NaN
389      877612.0
390      244285.0
391           NaN
392           NaN
393      791611.0
394           NaN
395      623558.0
397     1335675.0
401      753413.0
402      603983.0
404           NaN
405       98945.0
406           NaN
407           NaN
414           NaN
415      119454.0
417       16231.0
418           NaN
420     1264232.0
423      729343.0
427      186030.0
428           NaN
430           NaN
431           NaN
433       31265.0
434      603098.0
435           NaN
437           NaN
439      211492.0
441      416048.0
442           NaN
445     1316950.0
447           NaN
450           NaN
454           NaN
458      591346.0
460      585932.0
461           NaN
462           NaN
464           NaN
465           NaN
466           NaN
468           NaN
470     1427762.0
473           NaN
474           NaN
477      725494.0
478     1089773.0
480           NaN
481           NaN
483      708148.0
484           NaN
486           NaN
487      701384.0
488      992176.0
490      841743.0
491           NaN
492      811277.0
494      725410.0
495     1082779.0
496           NaN
497       43251.0
499           NaN
500           NaN
504       23135.0
507      778619.0
509      304207.0
511           NaN
512      605122.0
514      795703.0
519           NaN
520           NaN
522           NaN
524           NaN
525      922931.0
526     1493046.0
528           NaN
530      370428.0
531      384633.0
534     1418862.0
537      226504.0
539      968361.0
541           NaN
544           NaN
545           NaN
546           NaN
547           NaN
550      652018.0
553     1372158.0
554     1008401.0
557           NaN
558      619388.0
559     1229746.0
563           NaN
566           NaN
567     1493427.0
568           NaN
574      362711.0
575       54016.0
577     1491019.0
578           NaN
581           NaN
582           NaN
583           NaN
584           NaN
586           NaN
587           NaN
590      859340.0
593           NaN
598       91900.0
599           NaN
600      557836.0
602           NaN
604           NaN
607      690464.0
610           NaN
611           NaN
613           NaN
614      787197.0
617           NaN
618     1126463.0
619     1275301.0
620       32889.0
621       31360.0
622      505868.0
623       26523.0
624           NaN
625           NaN
629           NaN
630           NaN
631      213162.0
636           NaN
639           NaN
643      895758.0
644           NaN
645           NaN
646     1213502.0
647     1307145.0
649     1426933.0
651           NaN
652           NaN
655      390431.0
656           NaN
657       77392.0
658     1057867.0
664     1294890.0
665           NaN
666           NaN
668           NaN
672      503035.0
673      154216.0
676     1488439.0
678           NaN
680      323825.0
681           NaN
683     1045806.0
685           NaN
686      192065.0
688     1469634.0
690           NaN
694           NaN
695      823324.0
696       97280.0
700      988534.0
704           NaN
705           NaN
706           NaN
712           NaN
714           NaN
719           NaN
725      890525.0
726           NaN
728      994413.0
731      673395.0
732           NaN
733           NaN
735           NaN
740      451316.0
741           NaN
742      314503.0
744     1433798.0
746           NaN
749      454290.0
752     1069096.0
753           NaN
755           NaN
756           NaN
758      970111.0
760           NaN
761           NaN
763     1134304.0
764       28486.0
767           NaN
770     1447029.0
771           NaN
772           NaN
773           NaN
774      167574.0
777           NaN
778           NaN
779           NaN
780     1052322.0
783           NaN
791      176837.0
793           NaN
795           NaN
797      948656.0
799      953039.0
800       75287.0
801           NaN
803     1292070.0
805     1301488.0
808     1104156.0
811           NaN
814           NaN
816      866037.0
822      229095.0
825           NaN
826           NaN
832      428562.0
833           NaN
836      765362.0
837     1042442.0
841     1062789.0
842      907222.0
845           NaN
847     1490213.0
849      879747.0
850      927872.0
851           NaN
852      918302.0
854     1432925.0
857           NaN
858      978435.0
859           NaN
860     1379981.0
862           NaN
863      501594.0
864       73175.0
866      279225.0
867       25392.0
868           NaN
870       53871.0
871     1214549.0
873           NaN
874       30239.0
876     1123265.0
877           NaN
878      374419.0
881           NaN
885           NaN
887     1142604.0
890           NaN
897           NaN
898           NaN
899      593845.0
901           NaN
902           NaN
903      893257.0
904           NaN
905      703425.0
906      154927.0
909           NaN
912           NaN
913           NaN
918      837113.0
919           NaN
921      963506.0
923           NaN
924      388774.0
926       52926.0
927           NaN
928      429544.0
929           NaN
931           NaN
934           NaN
935           NaN
936           NaN
937      940380.0
939           NaN
941           NaN
943      278044.0
945           NaN
947      133721.0
948           NaN
949           NaN
951     1444499.0
955      563916.0
958           NaN
959      635162.0
960     1223601.0
961     1017282.0
962      381936.0
963           NaN
964           NaN
970     1375610.0
971      248857.0
973           NaN
974           NaN
975       83938.0
978           NaN
980           NaN
981           NaN
984      146720.0
985      168742.0
986           NaN
987      414841.0
988           NaN
989           NaN
991           NaN
992           NaN
994           NaN
995           NaN
997           NaN
999           NaN
1000    1453498.0
1002       5374.0
1005          NaN
1008    1451658.0
1009          NaN
1014       7678.0
1015     575704.0
1016     641417.0
1017          NaN
1018    1033208.0
1024    1106023.0
1025          NaN
1026     721186.0
1027          NaN
1029          NaN
1030     942231.0
1031     515898.0
1032      15707.0
1034          NaN
1036          NaN
1043          NaN
1044          NaN
1045     -14591.0
1047    1444076.0
1048          NaN
1050          NaN
1051    1176453.0
1055          NaN
1056     656652.0
1061     252284.0
1062    1386306.0
1063          NaN
1064     401722.0
1066          NaN
1067    1438391.0
1068     965123.0
1069          NaN
1070     688693.0
1073          NaN
1074          NaN
1076     222232.0
1077    1015203.0
1078     982886.0
1080     766200.0
1083          NaN
1085     947556.0
1087    1372906.0
1088     298384.0
1089     405525.0
1090    1495034.0
1092          NaN
1093          NaN
1095          NaN
1096     353994.0
1099     520791.0
1101          NaN
1103    1438675.0
1106          NaN
1107          NaN
1108     760717.0
1109    1278305.0
1111          NaN
1112     601238.0
1114     754837.0
1116          NaN
1117          NaN
1120    1392718.0
1121          NaN
1122          NaN
1125     527168.0
1127          NaN
1130          NaN
1133     985147.0
1134      67895.0
1135     989227.0
1139          NaN
1143          NaN
1148     227329.0
1150     582602.0
1151          NaN
1153    1276032.0
1155          NaN
1157    1096930.0
1158          NaN
1159          NaN
1161      92743.0
1163          NaN
1164          NaN
1166     568420.0
1167     411249.0
1168          NaN
1169    1075801.0
1170    1275827.0
1171          NaN
1172     254079.0
1173     661804.0
1179    1447764.0
1181    1118315.0
1183    1237382.0
1186          NaN
1189     382871.0
1194    1062613.0
1195    1303779.0
1196          NaN
1198     576884.0
1199          NaN
1200          NaN
1202    1309712.0
1203          NaN
1204     212058.0
1205          NaN
1206          NaN
1209          NaN
1210     631160.0
1211          NaN
1212     917809.0
1213    1147256.0
1215          NaN
1216          NaN
1220          NaN
1221          NaN
1223          NaN
1227          NaN
1228          NaN
1230     868596.0
1235      68550.0
1238     740791.0
1240     212707.0
1244          NaN
1248     765019.0
1249     534979.0
1251          NaN
1253     741808.0
1254          NaN
1256     335467.0
1262          NaN
1263     265323.0
1266     352851.0
1267          NaN
1268     919382.0
1269          NaN
1272          NaN
1273     431951.0
1275     -12605.0
1276     903658.0
1277          NaN
1278          NaN
1279     882134.0
1281    1341325.0
1282          NaN
1287          NaN
1290    1328360.0
1291          NaN
1292     804543.0
1293          NaN
1294    1380531.0
1296          NaN
1298          NaN
1301          NaN
1302          NaN
1304          NaN
1305     798448.0
1307          NaN
1308     855165.0
1309       1905.0
1311          NaN
1315     762276.0
1316     979898.0
1317          NaN
1319          NaN
1321          NaN
1322          NaN
1324          NaN
1325    1364139.0
1327          NaN
1328          NaN
1330          NaN
1331          NaN
1332          NaN
1334          NaN
1335    1154700.0
1336      92894.0
1338     220169.0
1339      43077.0
1340          NaN
1341     379657.0
1343          NaN
1345     718964.0
1346     288037.0
1347          NaN
1350     137200.0
1353       5383.0
1354     785395.0
1359     724074.0
1360     164778.0
1361          NaN
1365     932813.0
1367    1062460.0
1368     653767.0
1370     378772.0
1375     588815.0
1377     526328.0
1379          NaN
1380    1131681.0
1381          NaN
1385    1105734.0
1388     835392.0
1389          NaN
1391          NaN
1393     900809.0
1396          NaN
1398     358383.0
1400          NaN
1401    1273504.0
1403          NaN
1410          NaN
1412    1350698.0
1415     139920.0
1416          NaN
1419    1126787.0
1420    1437673.0
1421     971480.0
1426          NaN
1429          NaN
1431     167459.0
1435     739724.0
1436          NaN
1438          NaN
1439          NaN
1444          NaN
1447     626554.0
1448          NaN
1449     327210.0
1450          NaN
1454    1162144.0
1458          NaN
1459     401149.0
1461    1472092.0
1463          NaN
1465     498143.0
1467          NaN
1468    1427769.0
1475          NaN
1480     261749.0
1484     181866.0
1486    1409553.0
1487          NaN
1488          NaN
1490          NaN
1492          NaN
1493          NaN
1494     983511.0
1499          NaN
1506     894078.0
1508          NaN
1518          NaN
1523    1387701.0
1525          NaN
1527          NaN
1529          NaN
1531     714112.0
1533     849675.0
1534     521500.0
1535          NaN
1537     432415.0
1538          NaN
1539     583639.0
1540    1001125.0
1543     904073.0
1545     537341.0
1551          NaN
1552     858248.0
1554          NaN
1557     557782.0
1558          NaN
1576          NaN
1577    1205888.0
1580          NaN
1581          NaN
1582          NaN
1584     966359.0
1585          NaN
1587          NaN
1588     274267.0
1590          NaN
1591          NaN
1592     144058.0
1596          NaN
1597          NaN
1598    1142621.0
1600          NaN
1601    1406595.0
1602     785156.0
1603          NaN
1604    1169313.0
1609          NaN
1611          NaN
1615     113301.0
1617          NaN
1623     659958.0
1626     727900.0
1627    1385283.0
1629          NaN
1630          NaN
1633    1475785.0
1634     786945.0
1635          NaN
1636          NaN
1637          NaN
1640          NaN
1641    1477316.0
1642     120012.0
1644          NaN
1645     413732.0
1648    1342901.0
1649          NaN
1650          NaN
1653          NaN
1654          NaN
1658          NaN
1659          NaN
1664    1435734.0
1665     385433.0
1667          NaN
1672          NaN
1673          NaN
1674     171120.0
1678     207636.0
1679     422668.0
1682     876668.0
1683    1298336.0
1685     239724.0
1686    1013155.0
1688     964347.0
1689    1052967.0
1695    1180403.0
1697          NaN
1698    1206311.0
1703      24049.0
1706    1358119.0
1707    1124207.0
1711     355886.0
1713          NaN
1714          NaN
1715    1029090.0
1716          NaN
1719          NaN
1720          NaN
1721          NaN
1724          NaN
1727          NaN
1728      41407.0
1729    1189663.0
1730          NaN
1731     516130.0
1732          NaN
1733    1142710.0
1734          NaN
1736    1114313.0
1737     822347.0
1738    1337794.0
1739          NaN
1744          NaN
1745          NaN
1749    1347171.0
1750     853659.0
1751          NaN
1754          NaN
1757          NaN
1758          NaN
1760          NaN
1761    1207481.0
1771          NaN
1772          NaN
1773          NaN
1774     718015.0
1776          NaN
1777     585454.0
1783          NaN
1784          NaN
1785          NaN
1787     886534.0
1789    1312368.0
1791     470806.0
1792          NaN
1793     724866.0
1794          NaN
1797     430962.0
1799          NaN
1801          NaN
1802      42332.0
1804     413270.0
1806          NaN
1807          NaN
1810    1438549.0
1812          NaN
1813      22463.0
1814     800448.0
1816          NaN
1817          NaN
1818          NaN
1819     415316.0
1825     858285.0
1826          NaN
1829          NaN
1830     803251.0
1833     616303.0
1834     146890.0
1835          NaN
1836          NaN
1839    1035042.0
1840     951336.0
1841          NaN
1844    1082500.0
1852          NaN
1853    1315450.0
1854          NaN
1859          NaN
1860          NaN
1862    1228778.0
1864     907355.0
1865     248536.0
1866          NaN
1867     909505.0
1868    1413819.0
1869    1498386.0
1871     546972.0
1873          NaN
1874     928088.0
1878     155727.0
1879          NaN
1881          NaN
1882    1161703.0
1883     815680.0
1884          NaN
1885          NaN
1887          NaN
1888      58597.0
1895          NaN
1897          NaN
1898          NaN
1899    1180208.0
1900    1199399.0
1902     794977.0
1903          NaN
1904    1199646.0
1905          NaN
1906    1406223.0
1907          NaN
1911       7627.0
1914      -8547.0
1916    1405855.0
1918          NaN
1920          NaN
1922    1497582.0
1923          NaN
1927    1030360.0
1928          NaN
1929          NaN
1931      -4525.0
1933          NaN
1934          NaN
1941    1254109.0
1944          NaN
1946          NaN
1947          NaN
1949     348686.0
1950          NaN
1951     267606.0
1952     646189.0
1953          NaN
1955     365649.0
1956          NaN
1959    1324040.0
1962          NaN
1963          NaN
1964          NaN
1967          NaN
1968          NaN
1970    1295550.0
1971     347551.0
1973    1360078.0
1974          NaN
1975    1409019.0
1979          NaN
1981          NaN
1983          NaN
1985     554904.0
1987     239780.0
1988     360971.0
1991          NaN
1992     109464.0
1993      33497.0
1994     493198.0
1995     388316.0
1996    1492524.0
1998          NaN
2001    1017900.0
2006     803265.0
2007      89905.0
2008          NaN
2009     449058.0
2011          NaN
2012          NaN
2015     595090.0
2018    1422172.0
2020    1251698.0
2021          NaN
2023    1373699.0
2025          NaN
2026     559564.0
2036    1338222.0
2037    1300722.0
2039    1305142.0
2042     751924.0
2043    1339206.0
2045          NaN
2048          NaN
2050    1277835.0
2051          NaN
2055     183257.0
2056          NaN
2057          NaN
2063    1380156.0
2064          NaN
2065          NaN
2066          NaN
2067          NaN
2069     107377.0
2070    1436728.0
2073     542254.0
2074          NaN
2076          NaN
2080          NaN
2083    1286337.0
2084     834530.0
2085          NaN
2087          NaN
2088    1131942.0
2090          NaN
2091          NaN
2092          NaN
2093    1400203.0
2094     994471.0
2095    1199775.0
2097    1161523.0
2098     637702.0
2101          NaN
2102     417010.0
2103    1262319.0
2104          NaN
2111          NaN
2112     688883.0
2114     515723.0
2117          NaN
2118          NaN
2120          NaN
2123    1457610.0
2124    1419260.0
2125          NaN
2126          NaN
2127          NaN
2128    1243724.0
2129     362891.0
2131          NaN
2132          NaN
2133     545987.0
2136          NaN
2137     600563.0
2139     440431.0
2140          NaN
2141          NaN
2143          NaN
2144          NaN
2146     393635.0
2148          NaN
2151     324252.0
2152          NaN
2155          NaN
2160          NaN
2162          NaN
2166          NaN
2167          NaN
2168          NaN
2170          NaN
2172          NaN
2174    1427323.0
2175          NaN
2179          NaN
2180          NaN
2181          NaN
2184          NaN
2185          NaN
2186     425910.0

In [ ]:
df['Sponsorship_Amount']=df['Sponsorship_Amount'].fillna(df['Sponsorship_Amount'].mean())

Filling with mean(average) values in the 'Sponsorship_Amount' column in the Null values.

In [ ]:
df['Sponsorship_Amount']=df['Sponsorship_Amount'].round().astype(int)

Changing the datatype og "Sponsorshi_Amount" column into integer

In [ ]:
df['Sponsorship_Amount'].mean()

np.float64(740342.130952381)

In [ ]:
for x in df.index:
  if df.loc[x,'Sponsorship_Amount']<=0 or df.loc[x,'Sponsorship_Amount']>=1000000:
    df.loc[x,'Sponsorship_Amount']=740343

Replace unrealistic Sponsorship_Amount (Less than 0 or greater than 1,000,000) with its mean value.

In [ ]:
df['Sponsorship_Amount'].isna().sum()

np.int64(0)

In [ ]:
df['Merch_Sales'] = df['Merch_Sales'].fillna(df['Merch_Sales'].mean())

Filling 'Merch_Sales' column null values with its mean values.

In [ ]:
df['Merch_Sales']=df['Merch_Sales'].round().astype(int)

In [ ]:
df['Merch_Sales'].isna().sum()

np.int64(0)

In [ ]:
df['Venue'] = (df['Venue'].replace({' ':'Gujarat'}))

Replcing the empty(' ') value in the 'Venue' column to 'Gujarat' using replce().

In [ ]:
df['Venue'] = df['Venue'].fillna(df['Venue'].mode()[0])

Filling the missing null values with its mode(most repeatedly values) using fillna().

In [ ]:
df['Venue'].unique()

array(['Chennai', 'Bangalore', 'Mumbai', 'Kolkata', 'Delhi', 'Gujarat'],
      dtype=object)

In [ ]:
df['Venue'].isna().sum()

np.int64(0)

In [ ]:
df['Weather'] = (df['Weather'].str.strip().str.title())

In [ ]:
df['Weather'] = (df['Weather'].replace({'':'Unspecified'}))

Replcing thr empty(' ') values to 'Unspecified' in the 'weather' column.

In [ ]:
df['Weather'] = df['Weather'].fillna(df['Weather'].mode()[0])

Filling the missing null values with its mode() values in the 'Weather' column.

In [ ]:
df['Weather'].value_counts()

Weather
Rainy          1402
Unspecified     382
Sunny           373
Cloudy          363
Name: count, dtype: int64

In [ ]:
df['Weather'].isna().sum()

np.int64(0)

In [ ]:
df['Weather'].unique()

array(['Unspecified', 'Rainy', 'Sunny', 'Cloudy'], dtype=object)

In [ ]:
df['Win_Status'] = (df['Win_Status'].str.strip().str.title())

Removing extra spaces in both the column values and the column header name usign strip() and str().

In [ ]:
df['Win_Status']=df['Win_Status'].fillna('Win')

Filling the missing null values with 'Win' in the 'Win_Status' column

In [ ]:
df['Win_Status'].unique()

array(['Win', 'Draw', 'Lose'], dtype=object)

In [ ]:
df['Win_Status'].isna().sum()

np.int64(0)

In [ ]:
df['Rating'] = df['Rating'].fillna(df['Rating'].mode()[0])

Filling the missing null values with its mode() values in the 'Rating; column.

In [ ]:
df['Rating']=df['Rating'].round().astype(int)

In [ ]:
df['Rating'].isna().sum()

np.int64(0)

In [ ]:
df['Payment_Mode'] = (df['Payment_Mode'].str.strip().str.title())

In [ ]:
df['Payment_Mode'] = (df['Payment_Mode'].replace({'Creadit Card': 'Credit Card', 'Upi': 'UPI', 'Upiid': 'UPI', '':'Netbanking'}))

Replacing the wrong typos into correct sentence using replce().

In [ ]:
df['Payment_Mode']=df['Payment_Mode'].fillna('Cash')

Filing the missing null values with 'Cash' on the 'Payment_Mode' column using fillna().

In [ ]:
df['Payment_Mode'].unique()

array(['Cash', 'Netbanking', 'Credit Card', 'UPI'], dtype=object)

In [ ]:
df['Payment_Mode'].isna().sum()

np.int64(0)

In [ ]:
df['Fan_Purchase_Amount'] = df['Fan_Purchase_Amount'].fillna(df['Fan_Purchase_Amount'].mean())

Filling the 'Fan_Purchae_Amount' column with its mean() values.

In [ ]:
df['Fan_Purchase_Amount']=df['Fan_Purchase_Amount'].round().astype(int)

In [ ]:
df['Fan_Purchase_Amount'].isna().sum()

np.int64(0)

In [ ]:
df['Minutes_Played'] = df['Minutes_Played'].fillna(df['Minutes_Played'].mean())

Filling the 'Minutes_Played' column with its mean() values.

In [ ]:
df['Minutes_Played']=df['Minutes_Played'].round().astype(int)

In [ ]:
df['Minutes_Played'].isna().sum()

np.int64(0)

In [ ]:
df['Match_Date']=df['Match_Date'].fillna(method='ffill')

/tmp/ipython-input-94484209.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Match_Date']=df['Match_Date'].fillna(method='ffill')

Filling the empty null values in the 'Match_Date' column using backfill method.

In [ ]:
print(df['Match_Date'].to_string())

0       13-02-2023
1       05-12-2022
3       22-01-2024
5       12-05-2023
6       23-01-2024
7       07-08-2021
8       19-05-2022
9       08-02-2024
10      03-12-2023
12      03-12-2023
18      05-12-2023
19      03-03-2023
20      07-07-2023
22      05-12-2023
23      21-08-2022
26      14-11-2021
31      12-06-2021
33      05-12-2023
34      05-12-2023
35      21-03-2020
36      20-01-2022
39      17-05-2022
41      05-07-2022
43      10-01-2020
44      13-10-2022
46      13-01-2022
48      05-12-2023
50      22-11-2021
51      22-11-2021
53      02-03-2023
54      04-03-2021
56      25-04-2023
58      25-04-2023
60      27-05-2021
63      05-12-2020
67      20-11-2023
68      22-03-2020
69      12-05-2023
70      09-12-2021
72      05-12-2023
74      18-09-2022
79      16-09-2021
80      10-04-2023
82      31-05-2021
85      07-04-2020
87      17-05-2022
89      22-08-2023
91      08-11-2021
92      12-06-2021
94      12-06-2021
96      18-11-2023
98      09-06-2022
99      20-09-2023
101     25-05-2021
102     05-12-2023
103     17-12-2022
104     22-05-2023
108     15-12-2023
109     07-05-2020
110     27-02-2020
112     20-04-2021
114     05-09-2021
115     12-05-2023
116     26-12-2020
117     05-01-2024
119     05-08-2021
121     03-08-2020
126     15-10-2021
127     29-06-2023
129     29-10-2021
131     29-10-2021
133     05-12-2023
135     11-04-2023
137     03-01-2024
143     11-02-2023
148     11-09-2022
149     11-09-2022
150     23-11-2021
153     23-11-2021
154     16-09-2022
155     04-07-2021
156     04-07-2021
157     25-09-2023
162     16-07-2022
164     26-11-2021
165     20-08-2022
166     04-08-2022
167     16-09-2020
168     06-07-2022
172     20-04-2022
174     10-07-2022
175     22-08-2023
180     21-04-2021
183     25-06-2021
184     12-04-2021
186     29-11-2020
187     22-12-2021
188     15-06-2022
190     13-06-2023
192     22-11-2020
197     16-05-2021
198     16-05-2021
200     08-02-2022
201     29-12-2021
204     27-08-2020
210     19-01-2022
211     23-01-2022
213     10-10-2022
215     02-12-2021
216     10-11-2023
218     07-09-2021
221     05-12-2023
222     05-12-2023
223     05-12-2023
224     01-10-2023
225     22-10-2022
226     18-03-2022
227     18-03-2022
229     05-02-2022
230     16-10-2021
235     16-10-2021
236     05-12-2023
237     10-05-2021
239     08-08-2021
240     08-04-2023
242     15-02-2020
244     20-03-2020
245     03-12-2020
246     08-04-2023
251     25-06-2020
253     03-02-2024
256     30-06-2023
260     30-06-2023
263     03-04-2021
264     17-09-2021
266     13-04-2020
268     24-04-2022
269     20-01-2021
270     16-10-2023
272     28-01-2021
274     24-06-2022
275     01-06-2022
277     28-12-2023
279     21-03-2021
280     07-07-2020
282     02-03-2020
283     21-11-2020
284     24-05-2021
288     11-03-2022
289     12-10-2022
290     10-11-2020
293     03-03-2021
295     08-08-2023
296     08-08-2023
297     14-11-2023
300     25-02-2021
304     05-01-2024
308     19-01-2020
313     11-04-2022
314     02-10-2022
315     14-01-2023
317     12-05-2023
318     08-02-2024
319     16-01-2021
320     27-10-2021
321     16-10-2020
322     22-11-2021
323     18-08-2020
324     25-03-2023
326     04-12-2020
327     12-10-2022
330     29-01-2021
331     04-02-2020
334     14-07-2021
335     28-12-2023
336     02-10-2022
338     25-07-2022
342     05-12-2023
343     11-06-2020
344     11-06-2020
345     27-12-2023
347     30-08-2020
349     04-06-2020
352     23-12-2023
353     19-12-2021
356     19-04-2021
361     20-04-2022
362     05-12-2023
365     05-12-2023
367     30-06-2021
370     10-03-2022
371     22-01-2022
375     23-05-2023
376     08-01-2022
377     05-12-2023
378     20-11-2023
379     09-02-2020
380     10-07-2023
381     28-08-2022
383     12-05-2023
384     08-11-2021
386     01-05-2023
389     27-11-2023
390     25-12-2021
391     05-12-2023
392     05-12-2023
393     17-08-2020
394     11-01-2024
395     04-07-2022
397     15-10-2021
401     26-05-2023
402     26-05-2023
404     26-05-2023
405     30-07-2020
406     04-08-2021
407     09-04-2022
414     14-01-2023
415     12-12-2020
417     04-10-2022
418     12-09-2023
420     29-07-2023
423     12-05-2020
427     27-03-2023
428     01-09-2020
430     16-06-2020
431     30-10-2022
433     07-02-2024
434     29-09-2022
435     05-10-2023
437     13-01-2021
439     13-10-2023
441     21-02-2023
442     28-11-2021
445     01-02-2023
447     03-05-2020
450     12-01-2024
454     30-09-2020
458     13-02-2020
460     13-02-2020
461     03-05-2022
462     09-06-2022
464     17-12-2023
465     20-11-2022
466     01-05-2023
468     20-06-2022
470     30-08-2022
473     08-01-2022
474     08-01-2022
477     08-01-2020
478     31-01-2021
480     02-01-2021
481     07-04-2021
483     07-06-2021
484     30-01-2022
486     08-03-2020
487     12-06-2021
488     12-05-2023
490     18-08-2023
491     07-09-2022
492     07-09-2022
494     06-05-2020
495     05-03-2021
496     15-04-2022
497     05-10-2020
499     27-12-2021
500     27-12-2021
504     01-03-2021
507     01-03-2021
509     10-03-2020
511     06-02-2021
512     05-01-2023
514     17-06-2020
519     08-11-2023
520     12-05-2022
522     01-03-2022
524     16-11-2023
525     25-09-2023
526     07-08-2022
528     05-12-2023
530     05-12-2023
531     20-12-2022
534     18-03-2020
537     08-03-2021
539     05-02-2022
541     14-06-2020
544     09-12-2022
545     16-03-2020
546     01-09-2021
547     01-09-2021
550     14-06-2023
553     19-02-2022
554     05-12-2023
557     29-04-2022
558     13-06-2023
559     15-01-2020
563     17-11-2022
566     12-05-2023
567     17-02-2022
568     09-12-2020
574     09-12-2020
575     09-03-2020
577     29-01-2024
578     11-11-2020
581     12-05-2023
582     11-06-2023
583     06-07-2020
584     29-04-2020
586     29-04-2022
587     19-12-2023
590     07-05-2022
593     10-01-2023
598     06-02-2023
599     12-09-2021
600     30-04-2023
602     17-05-2021
604     21-06-2023
607     21-06-2023
610     05-12-2023
611     20-04-2021
613     17-01-2021
614     07-03-2022
617     09-05-2022
618     02-01-2020
619     30-04-2020
620     22-06-2022
621     08-04-2023
622     16-06-2020
623     16-06-2020
624     31-03-2020
625     22-03-2023
629     01-08-2023
630     11-09-2021
631     29-03-2021
636     13-09-2022
639     25-12-2021
643     04-07-2020
644     30-03-2023
645     04-07-2023
646     30-12-2021
647     07-10-2023
649     26-12-2022
651     03-01-2023
652     29-10-2020
655     18-01-2022
656     08-12-2023
657     10-11-2020
658     14-10-2020
664     12-10-2022
665     28-02-2022
666     12-01-2023
668     06-01-2021
672     01-10-2022
673     01-10-2022
676     28-09-2023
678     23-10-2023
680     05-12-2023
681     06-11-2022
683     28-03-2021
685     09-09-2023
686     03-08-2020
688     12-05-2023
690     05-12-2021
694     12-11-2023
695     02-06-2021
696     13-04-2022
700     28-02-2023
704     12-03-2020
705     12-05-2023
706     26-03-2022
712     09-09-2023
714     26-06-2022
719     05-12-2023
725     02-07-2022
726     12-05-2023
728     23-01-2021
731     14-10-2023
732     12-09-2020
733     16-10-2022
735     05-12-2023
740     10-03-2020
741     06-12-2022
742     10-03-2022
744     26-11-2021
746     11-04-2021
749     11-04-2021
752     27-12-2023
753     27-10-2020
755     11-08-2020
756     01-12-2023
758     07-01-2023
760     07-02-2021
761     13-09-2022
763     05-12-2023
764     05-12-2023
767     04-03-2023
770     26-10-2023
771     05-12-2023
772     12-05-2023
773     06-08-2022
774     10-06-2022
777     18-09-2020
778     07-09-2021
779     21-10-2020
780     08-10-2022
783     31-10-2021
791     22-12-2023
793     04-09-2021
795     21-09-2020
797     16-03-2021
799     05-12-2023
800     14-07-2020
801     05-12-2023
803     26-03-2021
805     05-12-2023
808     09-07-2021
811     12-01-2022
814     15-08-2022
816     20-07-2023
822     19-04-2020
825     23-07-2022
826     20-11-2022
832     05-11-2023
833     11-12-2022
836     28-03-2021
837     24-12-2021
841     05-12-2023
842     13-08-2023
845     03-12-2020
847     17-03-2021
849     18-01-2024
850     01-06-2022
851     16-03-2020
852     24-03-2022
854     05-12-2023
857     25-02-2023
858     09-09-2023
859     05-06-2022
860     05-12-2023
862     26-04-2021
863     28-08-2022
864     28-08-2022
866     19-12-2022
867     28-01-2024
868     10-01-2022
870     12-06-2021
871     20-10-2022
873     19-04-2022
874     20-11-2021
876     30-11-2022
877     09-03-2023
878     20-05-2022
881     11-02-2023
885     23-10-2023
887     23-10-2023
890     22-09-2021
897     07-02-2020
898     10-09-2023
899     02-12-2021
901     12-05-2023
902     18-03-2023
903     03-03-2022
904     11-04-2023
905     05-12-2023
906     27-07-2022
909     20-11-2020
912     28-10-2023
913     12-05-2023
918     10-01-2020
919     06-11-2022
921     01-02-2023
923     23-05-2023
924     22-10-2022
926     28-11-2023
927     21-04-2022
928     14-04-2020
929     30-09-2022
931     19-12-2021
934     15-06-2021
935     25-06-2022
936     10-07-2023
937     26-06-2022
939     02-06-2021
941     12-01-2020
943     09-04-2021
945     16-12-2021
947     15-01-2020
948     10-02-2021
949     05-04-2022
951     12-05-2023
955     23-04-2020
958     17-12-2023
959     17-12-2023
960     05-12-2023
961     23-11-2022
962     17-07-2023
963     19-08-2021
964     19-08-2023
970     19-04-2020
971     03-08-2021
973     12-05-2023
974     16-09-2022
975     16-09-2022
978     22-07-2023
980     22-07-2023
981     16-03-2021
984     30-11-2021
985     05-12-2021
986     06-11-2023
987     12-05-2023
988     12-05-2023
989     21-08-2022
991     03-12-2023
992     23-11-2020
994     05-12-2023
995     17-09-2020
997     01-09-2021
999     23-05-2021
1000    02-07-2022
1002    02-07-2022
1005    02-03-2020
1008    09-09-2021
1009    15-11-2022
1014    24-06-2023
1015    24-06-2023
1016    22-01-2021
1017    02-11-2022
1018    09-03-2022
1024    19-02-2020
1025    19-02-2020
1026    31-01-2022
1027    01-12-2021
1029    27-02-2021
1030    23-09-2020
1031    28-06-2023
1032    28-06-2023
1034    29-03-2022
1036    29-04-2023
1043    22-09-2023
1044    22-09-2023
1045    19-11-2023
1047    19-11-2023
1048    20-11-2023
1050    22-12-2022
1051    23-11-2022
1055    30-07-2023
1056    02-08-2020
1061    20-07-2020
1062    05-12-2023
1063    14-08-2022
1064    13-12-2022
1066    14-05-2021
1067    23-03-2023
1068    24-06-2023
1069    24-10-2022
1070    05-12-2023
1073    05-12-2023
1074    11-11-2022
1076    01-05-2021
1077    12-05-2023
1078    09-01-2022
1080    24-01-2022
1083    12-05-2023
1085    09-07-2023
1087    05-12-2023
1088    28-08-2020
1089    30-10-2020
1090    23-05-2021
1092    05-12-2023
1093    15-01-2022
1095    03-08-2022
1096    04-08-2020
1099    11-11-2020
1101    11-07-2022
1103    05-12-2023
1106    02-08-2021
1107    21-11-2023
1108    13-10-2022
1109    11-04-2020
1111    16-08-2021
1112    19-11-2021
1114    18-05-2022
1116    09-09-2023
1117    29-04-2022
1120    03-04-2023
1121    09-01-2024
1122    28-08-2022
1125    24-07-2022
1127    24-07-2022
1130    26-11-2022
1133    04-02-2023
1134    04-02-2023
1135    23-02-2021
1139    20-03-2021
1143    28-11-2022
1148    23-05-2021
1150    04-09-2021
1151    05-12-2023
1153    11-09-2022
1155    11-06-2021
1157    12-05-2023
1158    24-06-2022
1159    27-11-2022
1161    12-07-2021
1163    21-09-2023
1164    10-06-2021
1166    07-07-2020
1167    14-06-2022
1168    05-02-2021
1169    05-12-2023
1170    09-04-2023
1171    03-03-2023
1172    21-04-2023
1173    29-11-2022
1179    15-01-2021
1181    06-07-2021
1183    04-10-2022
1186    06-11-2021
1189    31-01-2022
1194    07-06-2021
1195    28-04-2022
1196    28-04-2022
1198    30-01-2021
1199    29-12-2020
1200    28-06-2020
1202    25-01-2022
1203    18-06-2020
1204    18-06-2020
1205    08-09-2023
1206    05-02-2022
1209    19-01-2021
1210    24-12-2023
1211    01-09-2022
1212    23-02-2021
1213    25-04-2023
1215    05-12-2023
1216    04-01-2020
1220    04-01-2020
1221    05-12-2023
1223    03-04-2023
1227    19-08-2020
1228    28-10-2022
1230    08-09-2022
1235    22-07-2022
1238    13-11-2020
1240    27-06-2020
1244    26-11-2021
1248    09-04-2022
1249    27-04-2020
1251    30-12-2021
1253    26-03-2020
1254    12-05-2023
1256    12-05-2023
1262    12-07-2021
1263    06-12-2023
1266    20-01-2021
1267    20-01-2021
1268    29-10-2020
1269    26-06-2021
1272    26-06-2021
1273    29-08-2023
1275    05-12-2023
1276    05-12-2023
1277    05-08-2021
1278    22-05-2021
1279    02-05-2021
1281    02-05-2021
1282    02-05-2021
1287    05-12-2023
1290    05-12-2023
1291    09-07-2023
1292    08-07-2020
1293    09-01-2023
1294    18-07-2022
1296    05-12-2023
1298    21-05-2020
1301    27-01-2023
1302    30-05-2020
1304    29-11-2022
1305    20-01-2024
1307    27-12-2021
1308    15-11-2021
1309    24-01-2022
1311    05-12-2023
1315    05-12-2023
1316    20-09-2020
1317    08-09-2023
1319    10-02-2020
1321    27-03-2021
1322    27-03-2021
1324    31-08-2023
1325    05-12-2023
1327    16-12-2022
1328    30-09-2023
1330    11-04-2020
1331    08-08-2022
1332    22-09-2020
1334    19-08-2023
1335    01-04-2022
1336    12-05-2023
1338    10-03-2022
1339    17-08-2020
1340    01-11-2020
1341    03-09-2020
1343    11-03-2023
1345    02-06-2023
1346    12-05-2023
1347    19-05-2022
1350    05-12-2023
1353    12-07-2022
1354    11-06-2023
1359    13-06-2020
1360    12-05-2023
1361    22-05-2022
1365    04-05-2021
1367    14-02-2023
1368    16-03-2022
1370    27-04-2021
1375    05-12-2023
1377    24-01-2022
1379    05-12-2023
1380    12-05-2023
1381    18-11-2021
1385    20-08-2023
1388    28-07-2022
1389    05-12-2023
1391    17-12-2021
1393    21-12-2021
1396    18-02-2022
1398    16-01-2021
1400    12-02-2022
1401    10-01-2020
1403    11-07-2021
1410    11-07-2021
1412    01-05-2022
1415    19-10-2021
1416    26-10-2022
1419    12-05-2023
1420    18-04-2020
1421    23-04-2022
1426    17-04-2021
1429    09-01-2020
1431    19-07-2021
1435    26-05-2021
1436    06-06-2020
1438    05-12-2023
1439    05-12-2023
1444    24-06-2020
1447    06-01-2022
1448    06-01-2022
1449    08-05-2023
1450    12-05-2023
1454    12-12-2023
1458    23-11-2020
1459    07-07-2021
1461    07-07-2021
1463    05-04-2023
1465    11-11-2020
1467    03-03-2020
1468    28-03-2020
1475    25-07-2022
1480    25-07-2022
1484    28-12-2022
1486    04-01-2024
1487    29-10-2020
1488    30-05-2021
1490    19-11-2020
1492    02-06-2021
1493    22-06-2022
1494    28-08-2022
1499    21-12-2023
1506    28-01-2022
1508    06-10-2022
1518    03-02-2023
1523    22-03-2020
1525    25-08-2023
1527    14-06-2020
1529    05-12-2023
1531    09-12-2021
1533    13-01-2020
1534    01-09-2021
1535    02-06-2023
1537    30-10-2022
1538    13-09-2020
1539    24-01-2020
1540    04-01-2022
1543    05-12-2023
1545    21-01-2021
1551    28-05-2022
1552    24-05-2023
1554    14-10-2022
1557    12-08-2022
1558    23-12-2023
1576    05-12-2023
1577    26-12-2022
1580    01-04-2020
1581    15-09-2021
1582    19-01-2023
1584    15-05-2022
1585    21-08-2022
1587    30-07-2021
1588    23-01-2020
1590    12-08-2023
1591    12-03-2021
1592    22-09-2020
1596    14-08-2020
1597    20-01-2022
1598    15-03-2023
1600    27-10-2020
1601    05-12-2023
1602    01-01-2022
1603    19-11-2023
1604    28-09-2022
1609    15-06-2022
1611    05-06-2020
1615    05-04-2021
1617    23-10-2022
1623    19-10-2023
1626    10-03-2023
1627    29-07-2023
1629    25-07-2021
1630    27-04-2021
1633    11-05-2022
1634    11-05-2022
1635    24-07-2023
1636    28-07-2022
1637    22-04-2020
1640    14-03-2020
1641    23-11-2022
1642    22-07-2022
1644    03-12-2020
1645    04-10-2020
1648    05-12-2023
1649    05-12-2023
1650    19-05-2020
1653    01-02-2020
1654    17-02-2020
1658    05-12-2023
1659    16-10-2022
1664    06-04-2020
1665    04-04-2021
1667    12-05-2023
1672    17-11-2022
1673    24-06-2022
1674    21-10-2022
1678    24-10-2023
1679    12-05-2023
1682    31-01-2022
1683    06-12-2020
1685    10-05-2021
1686    09-02-2021
1688    18-08-2022
1689    11-11-2023
1695    11-11-2023
1697    21-02-2021
1698    05-12-2023
1703    03-10-2023
1706    15-03-2023
1707    17-10-2020
1711    17-10-2020
1713    29-12-2022
1714    03-04-2023
1715    05-03-2020
1716    05-12-2023
1719    03-10-2023
1720    13-08-2023
1721    19-11-2021
1724    15-07-2023
1727    28-07-2021
1728    27-09-2022
1729    14-07-2021
1730    17-04-2023
1731    01-08-2021
1732    01-08-2021
1733    25-12-2022
1734    10-03-2022
1736    01-03-2021
1737    25-02-2023
1738    17-08-2021
1739    08-04-2023
1744    12-05-2023
1745    12-05-2023
1749    12-05-2023
1750    30-08-2021
1751    26-04-2020
1754    12-10-2023
1757    14-11-2020
1758    04-07-2020
1760    19-11-2021
1761    01-12-2023
1771    18-03-2022
1772    01-09-2022
1773    08-07-2021
1774    20-07-2021
1776    14-06-2020
1777    30-10-2022
1783    31-12-2021
1784    13-12-2022
1785    24-06-2022
1787    26-02-2021
1789    01-08-2023
1791    01-12-2022
1792    30-03-2023
1793    06-12-2021
1794    12-05-2023
1797    07-07-2023
1799    26-09-2023
1801    09-01-2022
1802    16-08-2020
1804    14-05-2020
1806    15-04-2020
1807    22-04-2021
1810    17-07-2021
1812    23-11-2020
1813    03-02-2022
1814    27-11-2023
1816    01-01-2020
1817    19-12-2020
1818    05-09-2022
1819    05-09-2022
1825    19-12-2021
1826    25-06-2023
1829    12-05-2023
1830    24-05-2023
1833    05-12-2023
1834    06-04-2020
1835    16-05-2022
1836    05-12-2023
1839    17-07-2020
1840    17-07-2020
1841    15-06-2022
1844    25-11-2021
1852    23-05-2023
1853    09-08-2021
1854    04-01-2024
1859    27-12-2022
1860    03-06-2020
1862    13-06-2022
1864    06-07-2020
1865    30-08-2023
1866    11-10-2021
1867    28-05-2020
1868    11-03-2021
1869    05-12-2023
1871    13-06-2021
1873    06-01-2020
1874    21-04-2023
1878    21-04-2023
1879    27-03-2021
1881    02-12-2021
1882    05-12-2023
1883    17-09-2022
1884    12-11-2020
1885    12-11-2020
1887    15-12-2021
1888    05-12-2023
1895    24-02-2021
1897    18-05-2021
1898    01-09-2023
1899    23-10-2021
1900    30-06-2021
1902    26-02-2020
1903    22-05-2022
1904    11-02-2022
1905    05-05-2021
1906    14-04-2020
1907    11-06-2020
1911    09-12-2023
1914    13-01-2020
1916    06-09-2020
1918    15-07-2021
1920    26-01-2024
1922    12-06-2021
1923    05-12-2023
1927    18-02-2020
1928    08-09-2020
1929    17-09-2023
1931    20-12-2021
1933    27-09-2023
1934    09-08-2022
1941    01-02-2022
1944    18-01-2020
1946    12-05-2023
1947    18-10-2021
1949    18-10-2021
1950    29-11-2022
1951    29-11-2022
1952    21-10-2020
1953    18-07-2021
1955    08-02-2023
1956    08-02-2023
1959    05-11-2023
1962    03-06-2022
1963    05-12-2023
1964    28-06-2020
1967    04-05-2021
1968    04-05-2021
1970    07-11-2022
1971    05-12-2023
1973    16-10-2021
1974    29-12-2021
1975    04-12-2021
1979    12-05-2023
1981    30-12-2023
1983    18-05-2022
1985    16-01-2023
1987    22-09-2023
1988    29-12-2022
1991    09-04-2023
1992    04-06-2022
1993    19-05-2023
1994    12-12-2023
1995    16-03-2022
1996    04-01-2023
1998    23-04-2023
2001    25-09-2020
2006    12-05-2023
2007    05-12-2023
2008    05-12-2023
2009    17-03-2023
2011    16-09-2021
2012    04-05-2022
2015    27-04-2021
2018    23-02-2022
2020    26-04-2021
2021    03-10-2021
2023    05-12-2023
2025    01-09-2021
2026    10-04-2020
2036    28-09-2022
2037    29-09-2022
2039    27-06-2022
2042    03-01-2021
2043    04-08-2020
2045    18-09-2020
2048    20-07-2020
2050    13-06-2022
2051    10-01-2023
2055    10-01-2023
2056    28-03-2021
2057    28-03-2021
2063    11-10-2023
2064    12-05-2023
2065    17-01-2024
2066    03-04-2020
2067    29-05-2021
2069    06-03-2021
2070    27-02-2023
2073    07-08-2022
2074    12-05-2023
2076    12-05-2023
2080    23-03-2021
2083    25-09-2023

In [ ]:
df = df.drop(columns=['Fan_Phone', 'Merch_ID', 'Fan_Email'])
# In my opinion, this columns are unwanted for this dataset. So I dropped from the table

There is question in my dataset as "Drop irrelevant columns after cleaning".

In [ ]:
df.columns = df.columns.str.strip().str.title()

In [ ]:
df.reset_index(drop=True,inplace=True)

Fetching all matches where Match_Fee > 4000.

In [ ]:

print(df[df['Match_Fee'] > 4000].to_string())

      Player_Id  Match_Id Player_Name       Team    Country  Age  Gender     Coach_Name  Sport_Type  Match_Date  Match_Fee  Bonus  Sponsorship_Amount  Score  Assists  Goals  Wickets  Ticket_Sales  Merch_Sales      Venue      Weather Win_Status  Rating  Feedback_Score  Fan_Id Payment_Mode  Fan_Purchase_Amount  Minutes_Played  Matches_Played  Fan_Count
23         1063      5004       Messi        CSK      India   28  Female  Unknown Coach  Basketball  10-01-2020       4086   1343              740343    122        5      4        0         10987        12869      Delhi        Rainy        Win       7               4   82435         Cash                11031              60              10       2302
42         1145      5027       Virat        CSK      India   27  Female     John Smith      Tennis  10-04-2023       5231   2338              740342    196        1      4        5         38750        10825  Bangalore        Sunny       Lose       1               4   80066  Credit Card                 9722              32              24       3376
51         1040      5194       Messi     Lakers  Sri Lanka   20    Male  Unknown Coach       other  09-06-2022       4629   2338              740342    136        7      2        1         47973        16805     Mumbai        Rainy        Win       9               4   81056          UPI                 9722              60              12       2071
55         1088      5156   Anonymous  Barcelona  Australia   60    Male  Unknown Coach    Football  17-12-2022       5287   2338              740342     21        6      1        4         36935        10057  Bangalore        Rainy       Draw       9               4   81884  Credit Card                19837              60              11       1534
56         1070      5177       Messi        KKR    England   60    Male  Unknown Coach  Basketball  22-05-2023       4012   2669              740343    191        9      3        1         12738        10057  Bangalore       Cloudy       Draw       1               3   82264  Credit Card                 2743              60              26        180
61         1162      5060    Joe Root  Barcelona  Sri Lanka   31  Female  Unknown Coach    Football  05-09-2021       4016   1747              740342     74        7      5        3         30278          231    Chennai        Rainy       Lose       9               4   84150         Cash                 9722              60              12       3194
64         1004      5127      Bumrah         MI      India   10  Female  Unknown Coach    Football  05-01-2024       5218   1701              740342    160        7      0        0         46273        10057    Gujarat       Cloudy       Draw       1               4   81006          UPI                 7490              73              15       2193
74         1014      5143      Hardik     Lakers      India   15  Female     John Smith       other  11-02-2023       5764   2338              740343    137        1      4        4         30278         9162  Bangalore        Sunny       Lose       1               4   80971          UPI                 9722              80               2       4423
95         1115      5048       Virat         MI      India   25    Male  Unknown Coach  Basketball  29-11-2020       5256   2338              515844    137        1      9        2         33050        10057     Mumbai        Rainy        Win       1               4   81508         Cash                 9722              60              15       3474
105        1130      5106      Hardik        RCB  Sri Lanka   36  Female     John Smith     Cricket  19-01-2022       5348   1246              740343     34        0      8        2         30278        10057      Delhi        Rainy       Draw       1               4   82604          UPI                12534               8              22        993
108        1080      5061       Virat        RCB  Sri Lanka   12    Male  Unknown Coach    Football  02-12-2021       4606   1668              863752     22        4      9        3         30278        10057    Chennai        Rainy       Draw       2               4   82812  Credit Card                 9687              60              15       4994
112        1128      5047    Joe Root         MI  Australia   39    Male  Unknown Coach       other  05-12-2023       4836   2338              740343     33        8      1        4         36638        18343  Bangalore        Rainy        Win       1               4   82891         Cash                 9722              60              22       3946
118        1197      5172       Rohit  Barcelona      India   55    Male  Unknown Coach    Football  05-02-2022       4251   2261              740342     30        7      9        1         11106        15568  Bangalore        Rainy       Lose       6               4   80404          UPI                 9722              94              18       1064
128        1186      5143    Joe Root        RCB      India   15    Male  Unknown Coach      Tennis  08-04-2023       5274   1896              740342    148        3      5        3         30278        10057     Mumbai        Rainy       Lose       4               4   80747   Netbanking                 1574             115               0       4439
129        1186      5035       Messi         MI      India   20    Male  Unknown Coach    Football  25-06-2020       5357   2338              740342    101        8      5        0         30278        10057  Bangalore        Sunny       Draw       5               4   84789         Cash                13602             114              28       4269
142        1089      5114      Hardik        RCB      India   47    Male  Unknown Coach    Football  28-12-2023       5714   2338              740342    198        5      5        2         22201        10057  Bangalore        Sunny       Lose       1               4   81836   Netbanking                 2725              10              22       1868
143        1059      5022       Rohit     Lakers      India   36   Other  Unknown Coach    Football  21-03-2021       5909   2437              622188    126        3      7        0         30278         1888     Mumbai        Rainy       Lose       8               4   81382   Netbanking                 8201              22              22       3827
151        1147      5148     Ronaldo     Lakers    England   21   Other   Rahul Dravid     Cricket  03-03-2021       4551   1004               55063    194        6      1        1         48465        16709    Chennai  Unspecified        Win       1               4   81559   Netbanking                 9722              27               7       4815
164        1160      5095      Hardik         MI  Sri Lanka   22    Male  Unknown Coach     Cricket  27-10-2021       5980   2338              740342     80        2      3        1         44521        10057  Bangalore        Sunny        Win       1               3   80292          UPI                 6504              60               9       1152
187        1171      5034       Virat     Lakers      India   51  Female  Unknown Coach    Football  05-12-2023       4217   2853              747497     39        1      4        3         30278        10057  Bangalore       Cloudy       Draw       9               4   83830   Netbanking                 1517              60              22       2671
193        1187      5159      Bumrah     Lakers  Sri Lanka   56  Female  Unknown Coach    Football  08-01-2022       5033   2338              740342     42        9      9        4         30278         1184    Chennai        Rainy        Win       3               3   84216   Netbanking                 9722              60              22       1380
195        1190      5185      Hardik        KKR  Sri Lanka   10    Male  Unknown Coach    Football  20-11-2023       4362    352              924942     22        9      9        5         49575         5841  Bangalore        Sunny        Win       5               4   84340         Cash                 1863              23               9       3159
197        1160      5002       Rohit  Barcelona    England   42    Male  Unknown Coach  Basketball  10-07-2023       5519    262              740342    185        0      1        3         30278        10057      Delhi  Unspecified       Lose       1               4   82989  Credit Card                12425              40              19       4991
205        1031      5170      Bumrah        KKR  Sri Lanka   51    Male   Rahul Dravid    Football  05-12-2023       5387    513              740342     89        4      6        0         30278        10057      Delhi        Rainy        Win       1               4   81039          UPI                15187              61              15       2602
225        1085      5132       Smith  Barcelona    England   59    Male     John Smith       other  30-10-2022       4433   2338              740342    197        5      2        4         30278        16663    Kolkata        Rainy       Draw       1               4   84054   Netbanking                  313              60              17       3527
237        1108      5042       Smith        KKR  Australia   32   Other  Unknown Coach  Basketball  13-02-2020       5202   2338              591346     93        5      9        2         43453        10057     Mumbai        Rainy       Lose       5               4   84983  Credit Card                 9096              93              28       4263
239        1046      5117       Rohit        KKR      India   29  Female   Rahul Dravid      Tennis  03-05-2022       5731   2338              740342    138        7      5        4         17416        13195    Gujarat        Sunny       Draw       9               2   84264   Netbanking                 1184             103              27       1823
254        1139      5039       Virat        RCB      India   56  Female  Unknown Coach      Tennis  08-03-2020       4089    543              740342    187        6      1        0          5013        11631  Bangalore  Unspecified       Draw       1               4   80923   Netbanking                 9722              27               9       1251
261        1047      5006       Messi        CSK  Australia   38   Other  Unknown Coach    Football  05-03-2021       4627   2338              740343    165        7      4        3         30278        11110     Mumbai        Sunny        Win       1               4   82376   Netbanking                 9722              60              28       3823
264        1015      5175      Hardik        KKR  Sri Lanka   36    Male     John Smith    Football  27-12-2021       5557   2338              740342    162        7      4        4         29970        10057  Bangalore        Sunny       Lose       1               5   83501          UPI                13482              65              12       2925
290        1188      5092       Dhoni        RCB      India   39  Female  Unknown Coach    Football  19-02-2022       4865   1560              740343    105        6      8        0         30278        10057      Delhi        Sunny        Win       1               4   80975  Credit Card                 9722              60              21       1270
294        1064      5027       Smith        RCB  Sri Lanka   41  Female  Unknown Coach       other  15-01-2020       4672   2338              740343      6        8      3        3         16395        15411  Bangalore  Unspecified        Win       8               4   80010  Credit Card                 9722             119              16       3823
297        1011      5085       Messi        RCB  Australia   12    Male  Unknown Coach    Football  17-02-2022       5389   2338              740343     80        8      1        1         24686        10057  Bangalore       Cloudy       Lose       1               4   84064   Netbanking                 9722             101               9       3913
298        1094      5003       Virat  Barcelona    England   13  Female   Rahul Dravid       other  09-12-2020       4516   2338              740342    191        1      3        1         30278        10057  Bangalore        Rainy        Win       1               4   81471         Cash                 9722              82               3       1048
310        1151      5059       Virat     Lakers      India   28  Female  Unknown Coach  Basketball  10-01-2023       4945   2338              740342     34        4      3        2         21713        13061     Mumbai  Unspecified       Lose       1               2   80007   Netbanking                 9722              30               4       1231
312        1151      5182       Rohit        CSK    England   29    Male   Rahul Dravid       other  12-09-2021       5513   1385              740342    136        7      9        4         48658        14886  Bangalore        Rainy        Win       3               4   81285  Credit Card                12525              72              15        596
313        1150      5105      Hardik  Barcelona      India   53    Male  Unknown Coach     Cricket  30-04-2023       4470   2338              557836    187        7      8        2         10386        14139    Gujarat        Rainy        Win       1               4   83620         Cash                 7556              60              22       1070
318        1016      5144       Dhoni        CSK  Sri Lanka   18   Other   Rahul Dravid  Basketball  20-04-2021       5180   2338              740342    150        2      5        1         30278        10057    Kolkata        Sunny       Lose       1               4   81053          UPI                 9722              28               9        765
327        1188      5081      Bumrah        KKR    England   52    Male  Unknown Coach      Tennis  16-06-2020       5995   2078               26523    187        2      6        1         30278        12745    Gujarat        Rainy       Draw       8               4   83547  Credit Card                 7494              60              14       3721
332        1082      5047      Bumrah     Lakers      India   15   Other     John Smith      Tennis  29-03-2021       5409   2825              213162     13        6      2        5         45528        11649  Bangalore        Rainy       Lose       1               4   84375          UPI                 9722             105               6        919
337        1038      5187     Ronaldo     Lakers    England   38    Male  Unknown Coach    Football  04-07-2023       5272   2527              740342    169        6      9        4         43938        10057  Bangalore  Unspecified        Win       8               1   84525         Cash                 3364              60               9        600
351        1004      5031     Ronaldo         MI      India   12  Female     John Smith    Football  01-10-2022       4845   2338              503035      9        8      7        4         30278        13545    Chennai        Sunny       Lose       6               4   84880         Cash                 -839              60              27       1535
353        1082      5186       Messi  Barcelona      India   27    Male  Unknown Coach     Cricket  28-09-2023       4937   1420              740343     76        0      5        4         30278        10057    Kolkata       Cloudy       Lose       7               4   84674  Credit Card                 5067              60               4       1878
354        1108      5176       Smith  Barcelona    England   33  Female     John Smith    Football  23-10-2023       4345   2338              740342    132        3      4        1         45343        16503    Chennai        Sunny       Draw       3               2   81787          UPI                10876              60              22       1084
392        1059      5071      Hardik        KKR    England   32  Female  Unknown Coach       other  05-12-2023       5472   2338              740343    158        7      6        0         40816         1445    Gujarat        Rainy       Draw       7               4   83132  Credit Card                18493              60              14        730
405        1117      5114      Bumrah        CSK    England   50    Male   Rahul Dravid    Football  22-12-2023       4203   2338              176837     18        4      4        5         30278        10057     Mumbai        Rainy       Lose       1               4   82091          UPI                 9722              60              24       4990
408        1025      5193    Joe Root        CSK      India   15    Male     John Smith       other  16-03-2021       5600   2977              948656     46        7      7        5         30278        10057    Kolkata       Cloudy        Win       1               2   82841          UPI                 9722              61              28       1625
426        1002      5110      Hardik        RCB      India   11   Other  Unknown Coach  Basketball  13-08-2023       4605   2338              907222     28        3      7        3         34681         2636      Delhi        Sunny       Draw       3               4   80850         Cash                 9722              99              10       2529
434        1074      5191      Hardik        CSK      India   58    Male  Unknown Coach       other  25-02-2023       4599   2647              740342    190        2      6        5         44694        10057      Delhi       Cloudy       Draw       1               3   82017          UPI                 8194              22              21       1317
438        1037      5004      Bumrah        KKR      India   53  Female  Unknown Coach  Basketball  26-04-2021       5632   2338              740342    194        4      0        4         23916        10057      Delhi        Rainy       Draw       5               2   82534         Cash                 9366              60              24       1394
439        1049      5194   Anonymous  Barcelona    England   13  Female     John Smith      Tennis  28-08-2022       4827   2338              501594     85        1      9        4         25406        10057  Bangalore        Rainy       Draw       1               4   82812         Cash                 3659              60              11       3168
440        1097      5185      Hardik        KKR  Australia   32    Male  Unknown Coach    Football  28-08-2022       4703   2338               73175    144        8      9        1         30278        15113  Bangalore        Rainy        Win       1               4   80622         Cash                 9722              60              22       3559
447        1029      5161       Rohit        CSK      India   46  Female  Unknown Coach  Basketball  20-11-2021       5184   2396               30239     52        5      6        4         30278         1096      Delhi       Cloudy        Win       9               3   83495   Netbanking                 9722              60              22       4665
450        1132      5139       Rohit        CSK    England   26    Male   Rahul Dravid    Football  20-05-2022       4952   2338              374419    135        0      2        3         28401        10057    Gujarat        Rainy        Win       6               4   80518   Netbanking                 7077              60               4       4302
453        1068      5157   Anonymous         MI      India   40  Female     John Smith       other  23-10-2023       4470   2338              740343     47        3      2        0         30278        10057    Chennai       Cloudy        Win       1               3   83228         Cash                 9722              69              10        750

Fetching all feddback_score' <3

In [ ]:
print(df[df['Feedback_Score'] < 3].to_string())

      Player_Id  Match_Id Player_Name       Team    Country  Age  Gender     Coach_Name  Sport_Type  Match_Date  Match_Fee  Bonus  Sponsorship_Amount  Score  Assists  Goals  Wickets  Ticket_Sales  Merch_Sales      Venue      Weather Win_Status  Rating  Feedback_Score  Fan_Id Payment_Mode  Fan_Purchase_Amount  Minutes_Played  Matches_Played  Fan_Count
5          1020      5187       Virat        CSK  Australia   33    Male  Unknown Coach  Basketball  07-08-2021       1907   2338              740342    121        9      1        3          8839         3104    Chennai       Cloudy        Win       7               1   82657  Credit Card                 9722              66              23       4372
12         1087      5045       Rohit         MI      India   56  Female     John Smith    Football  07-07-2023       1907   2338              597941     66        0      7        1         30278        10057  Bangalore        Rainy       Lose       5               1   84044  Credit Card                12815              65               5       3787
19         1014      5136       Smith        KKR      India   42    Male  Unknown Coach    Football  21-03-2020       1907   2267              474567    125        8      2        5         30278        13454  Bangalore        Rainy        Win       1               1   80538         Cash                 9722             118              24       2580
20         1189      5005    Joe Root        KKR      India   41  Female  Unknown Coach  Basketball  20-01-2022       1907    189              740342    154        4      2        4         30278        10057     Mumbai        Rainy        Win       8               1   84784  Credit Card                 7650              38              23       4597
21         1189      5038       Virat  Barcelona  Sri Lanka   42  Female  Unknown Coach    Football  17-05-2022       1907   2338              786510    105        5      8        4          1440        14806  Bangalore        Rainy       Draw       1               1   80305   Netbanking                 9722              60              26       4806
22         1107      5168       Virat         MI  Sri Lanka   20    Male  Unknown Coach  Basketball  05-07-2022       3412   2620              262307    112        5      4        4         32080         9882    Gujarat        Rainy        Win       3               1   80724         Cash                13804              60               6        111
30         1013      5140       Messi  Barcelona      India   32    Male   Rahul Dravid    Football  04-03-2021       1907   2777              740342     92        9      1        3         28501        10696      Delhi        Rainy       Lose       9               2   81283         Cash                 9722               1              23       3102
35         1034      5017     Ronaldo        RCB  Australia   58    Male     John Smith    Football  20-11-2023       1907   2365              740342    175        1      4        0         22991        10057     Mumbai        Sunny        Win       6               1   81433  Credit Card                13058             120               7       2858
60         1135      5176      Bumrah  Barcelona  Australia   19    Male  Unknown Coach  Basketball  20-04-2021       3702   2338              740342    177        1      8        5         30278          125  Bangalore        Rainy       Draw       1               1   81968         Cash                16083              60              10        611
66         1071      5070     Ronaldo         MI      India   37   Other  Unknown Coach    Football  03-08-2020       1907   2338              740343    171        5      5        3         30278        19171    Kolkata        Rainy        Win       7               1   84866  Credit Card                 9722             114              21       2200
67         1150      5194       Dhoni  Barcelona  Sri Lanka   53    Male  Unknown Coach    Football  15-10-2021       1907   1319              280722     61        2      5        0         14556        10057  Bangalore       Cloudy       Lose       6               2   81617  Credit Card                 1699              60              25       2114
73         1000      5130     Ronaldo  Barcelona    England   10   Other     John Smith    Football  03-01-2024       1907   1783              146222     43        9      1        0         42973        10057    Chennai       Cloudy       Lose       1               2   82848         Cash                 9722              60              25       2216
97         1102      5081       Dhoni     Lakers      India   52  Female  Unknown Coach     Cricket  15-06-2022        556   1441              740342    109        9      8        2         23181        10057    Chennai        Rainy        Win       8               2   84329         Cash                 6323              15              15       1865
101        1058      5002      Hardik        CSK      India   60    Male  Unknown Coach    Football  16-05-2021       1907   1473              740343     24        6      9        5         30278        10057    Gujarat  Unspecified       Lose       1               2   80356   Netbanking                 9722              60              23       4814
107        1112      5157    Joe Root     Lakers      India   52  Female  Unknown Coach     Cricket  10-10-2022       1907    488              740342    184        9      1        3         30278         2429    Kolkata        Sunny        Win       1               2   80063   Netbanking                 9722              62               4       2123
119        1159      5061       Messi     Lakers  Australia   24  Female   Rahul Dravid    Football  16-10-2021       2828   1595              116736    129        7      7        3         30278        15764    Gujarat  Unspecified       Draw       1               2   82873  Credit Card                14897              60              17        517
123        1115      5091       Smith         MI  Australia   26    Male   Rahul Dravid    Football  08-08-2021         89   2338              740342     28        1      5        4         30278        12881      Delhi        Rainy        Win       3               2   81540   Netbanking                  667              60               9        810
134        1038      5056    Joe Root        CSK      India   15   Other   Rahul Dravid    Football  17-09-2021        537   2874              740342    106        0      4        1         30278        10057  Bangalore  Unspecified       Draw       1               1   81145  Credit Card                 9722              60               1       1867
144        1112      5145       Rohit         MI    England   55   Other  Unknown Coach       other  07-07-2020       1907   2125              740342    192        6      1        3         30278        10057      Delhi        Sunny        Win       6               1   81770  Credit Card                  949              60              29       3480
149        1098      5060    Joe Root     Lakers      India   57  Female  Unknown Coach       other  12-10-2022       1907   2338              346700    100        2      3        4         46249        10057  Bangalore       Cloudy       Lose       1               2   84302   Netbanking                  822              60              15       1103
163        1168      5148       Rohit        CSK    England   12  Female  Unknown Coach    Football  16-01-2021       1907   2519              362824     55        4      0        5         16088        10057  Bangalore       Cloudy       Lose       1               2   81459          UPI                 9722              60              23       1871
165        1067      5162       Virat     Lakers      India   19   Other  Unknown Coach       other  16-10-2020       1907   2338              740342    148        3      1        5         44020        15588    Chennai        Rainy       Draw       1               2   80654   Netbanking                 9722              60              27       4990
183        1191      5060      Bumrah        RCB    England   54   Other  Unknown Coach  Basketball  23-12-2023       1907   2338              740342     62        9      8        1         30278         5403  Bangalore        Rainy       Draw       1               1   80178         Cash                 7959              60               2        567
191        1092      5158       Messi         MI    England   57   Other  Unknown Coach    Football  22-01-2022       1907   2338              740343     73        0      2        0         18577         8437      Delhi        Rainy        Win       1               2   84808   Netbanking                 6828              13               2       3200
208        1150      5060    Joe Root  Barcelona    England   36  Female   Rahul Dravid    Football  04-07-2022       1907   2338              623558    175        4      0        5         26587        14988  Bangalore       Cloudy       Lose       1               1   80513          UPI                 9722              36               7        155
209        1126      5152    Joe Root        KKR      India   55    Male     John Smith  Basketball  15-10-2021       1907   2338              740343    197        7      9        0         30278         6757  Bangalore        Rainy       Draw       1               1   83132          UPI                 9722              60              25       3911
214        1038      5196     Ronaldo        CSK      India   37  Female   Rahul Dravid    Football  04-08-2021       1907   2338              740342     11        3      1        5         30278        11656  Bangalore       Cloudy       Draw       1               2   84450         Cash                 3260              92              17       1069
217        1134      5112       Smith        CSK      India   22   Other  Unknown Coach    Football  12-12-2020       1907   2338              119454    140        9      8        3         30278         2192      Delhi  Unspecified       Lose       7               2   82242  Credit Card                13051              60               1       3740
218        1035      5165      Hardik        KKR    England   26    Male   Rahul Dravid    Football  04-10-2022       1907    460               16231    168        8      4        4         22975        12156    Gujarat       Cloudy        Win       1               1   81358  Credit Card                18885              60              15       2793
220        1064      5031       Rohit  Barcelona      India   19  Female   Rahul Dravid    Football  29-07-2023       1907    684              740343    151        5      8        3         30278        10057  Bangalore        Rainy       Draw       1               2   81450          UPI                 9722              60              24       4820
222        1097      5119   Anonymous  Barcelona    England   31    Male  Unknown Coach    Football  27-03-2023       1907    337              186030     14        1      7        5         26831        18304     Mumbai       Cloudy       Draw       4               1   84072   Netbanking                 9722             100              19       3212
232        1048      5003       Messi        CSK      India   33    Male  Unknown Coach  Basketball  28-11-2021       1907   2338              740342     56        1      7        2         30278        10057    Gujarat        Rainy       Draw       1               1   83651         Cash                 9722              60              25       1259
233        1069      5103   Anonymous  Barcelona      India   48  Female   Rahul Dravid    Football  01-02-2023        362   2568              740343    142        8      5        4         29927        10057  Bangalore        Rainy       Draw       2               2   84749          UPI                 9722              60              17       4008
236        1004      5111     Ronaldo        KKR  Sri Lanka   54  Female  Unknown Coach     Cricket  30-09-2020       1907   2338              740342     42        5      5        4         30278         8313      Delhi       Cloudy       Lose       1               2   84846          UPI                 3958              51               0        204
239        1046      5117       Rohit        KKR      India   29  Female   Rahul Dravid      Tennis  03-05-2022       5731   2338              740342    138        7      5        4         17416        13195    Gujarat        Sunny       Draw       9               2   84264   Netbanking                 1184             103              27       1823
243        1143      5183       Messi     Lakers      India   54    Male     John Smith      Tennis  01-05-2023       2969   2338              740342    129        2      0        3         30278         1368  Bangalore  Unspecified       Lose       4               2   80205   Netbanking                 9188              79               9       4703
249        1057      5199       Messi  Barcelona    England   50  Female  Unknown Coach     Cricket  31-01-2021       1907   2338              740343     29        9      7        1          8097         6338    Chennai        Rainy       Lose       1               1   82157         Cash                 9722              60              18       4896
260        1117      5061     Ronaldo        KKR      India   17  Female  Unknown Coach     Cricket  06-05-2020       2772   2338              725410     79        7      8        5         30278         2713    Kolkata  Unspecified        Win       1               1   83126         Cash                 5927              44              27       1678
267        1075      5118       Rohit  Barcelona      India   34    Male     John Smith     Cricket  01-03-2021       1907   1560              778619     41        9      5        3         30104         9505    Gujarat        Rainy        Win       6               2   83722          UPI                 9722              60               1       1491
274        1038      5093      Bumrah  Barcelona      India   36  Female  Unknown Coach     Cricket  01-03-2022        284   2338              740342     25        0      8        3         30278         1690    Chennai  Unspecified        Win       3               1   81753  Credit Card                 9722              60              17        505
288        1139      5150     Ronaldo  Barcelona      India   23    Male   Rahul Dravid      Tennis  01-09-2021       1907   2338              740342     44        2      8        4         26874        10057    Gujarat  Unspecified       Lose       1               1   83474  Credit Card                14001              60              19       2546
293        1066      5038       Dhoni        KKR  Australia   47    Male  Unknown Coach    Football  13-06-2023       1907    308              619388    125        6      9        4         32578        10057    Chennai        Sunny       Lose       1               1   84460          UPI                16886              27               8       4139
296        1140      5025   Anonymous        RCB    England   58    Male  Unknown Coach    Football  12-05-2023       1907   2338              740342    124        7      5        3         30278         3618      Delhi        Rainy       Lose       2               2   83747  Credit Card                 9722              40               8       2985
305        1057      5189   Anonymous        RCB  Sri Lanka   55  Female  Unknown Coach    Football  06-07-2020       1907   2338              740342    131        8      8        3         30278        11961  Bangalore       Cloudy       Lose       1               1   80052          UPI                 9679              60               0       1921
310        1151      5059       Virat     Lakers      India   28  Female  Unknown Coach  Basketball  10-01-2023       4945   2338              740342     34        4      3        2         21713        13061     Mumbai  Unspecified       Lose       1               2   80007   Netbanking                 9722              30               4       1231
315        1112      5021       Smith        RCB      India   14  Female   Rahul Dravid    Football  21-06-2023        632   1537              740342     68        6      9        0         30278         8180  Bangalore        Rainy       Lose       6               2   80017  Credit Card                 9722             112              13       3371
321        1140      5012       Smith        CSK    England   34  Female  Unknown Coach      Tennis  09-05-2022       1907    666              740342    190        0      9        1         30278         3772  Bangalore       Cloudy       Draw       1               1   82715   Netbanking                11182              12               8        443
337        1038      5187     Ronaldo     Lakers    England   38    Male  Unknown Coach    Football  04-07-2023       5272   2527              740342    169        6      9        4         43938        10057  Bangalore  Unspecified        Win       8               1   84525         Cash                 3364              60               9        600
338        1108      5089     Ronaldo        RCB  Sri Lanka   18    Male     John Smith      Tennis  30-12-2021       3475   2761              740343    100        4      9        4         40625        14516    Chennai        Sunny        Win       6               2   82616   Netbanking                 6958              18               6       3166
339        1180      5013       Messi     Lakers  Australia   57    Male  Unknown Coach    Football  07-10-2023       1907   2338              740343     28        1      8        5         35995        10057     Mumbai        Rainy        Win       7               1   82377         Cash                 9722              60              11       3942
344        1145      5186       Rohit        RCB      India   44    Male  Unknown Coach     Cricket  08-12-2023       1907   2338              740342     64        4      8        1         16457        10057  Bangalore        Rainy        Win       3               1   80677          UPI                 9722              25              28       3442
345        1075      5190   Anonymous        RCB      India   19    Male  Unknown Coach     Cricket  10-11-2020       1727   2338               77392     14        9      9        3         30278        13130      Delhi        Rainy        Win       1               2   80550          UPI                15692              93               5       1754
354        1108      5176       Smith  Barcelona    England   33  Female     John Smith    Football  23-10-2023       4345   2338              740342    132        3      4        1         45343        16503    Chennai        Sunny       Draw       3               2   81787          UPI                10876              60              22       1084
356        1144      5092       Dhoni         MI  Sri Lanka   15    Male     John Smith  Basketball  06-11-2022       1907   2343              740342     27        7      7        2         38682         1069  Bangalore        Rainy       Lose      10               2   82460          UPI                12974              60              11       2914
360        1018      5030   Anonymous        KKR      India   48    Male     John Smith  Basketball  12-05-2023       1907   2514              740343    140        0      3        0         10439        10057    Chennai        Sunny        Win       2               2   80954         Cash                 9722              53              23       3600

Fetching players from India with matches > 10.

In [ ]:
df.loc[(df['Country'] == 'India') & (df['Matches_Played'] > 10), ['Player_Name']]

     Player_Name
1          Virat
7         Hardik
8          Virat
14      Joe Root
18        Bumrah
...          ...
2505       Messi
2508     Ronaldo
2513    Joe Root
2515       Smith
2516      Bumrah

[721 rows x 1 columns]

Fetching VIP ticket buyers where Ticket_Sales > 5000.

In [ ]:
print(df[df['Ticket_Sales'] > 5000].to_string())

      Player_Id  Match_Id Player_Name       Team    Country  Age  Gender     Coach_Name  Sport_Type  Match_Date  Match_Fee  Bonus  Sponsorship_Amount  Score  Assists  Goals  Wickets  Ticket_Sales  Merch_Sales      Venue      Weather Win_Status  Rating  Feedback_Score  Fan_Id Payment_Mode  Fan_Purchase_Amount  Minutes_Played  Matches_Played  Fan_Count
0          1102      5082       Virat        CSK      India   17    Male   Rahul Dravid    Football  13-02-2023       1907   2338              287941     13        0      1        5         37356        10057    Chennai  Unspecified        Win       5               4   81006         Cash                 8970               1               3       2337
1          1179      5034       Virat        KKR      India   23    Male  Unknown Coach      Tennis  05-12-2022       1907   2338              740342     90        9      7        0         18655         7745  Bangalore  Unspecified       Draw      10               4   80048   Netbanking                 9722              60              11        805
2          1014      5068      Bumrah        KKR      India   60    Male  Unknown Coach  Basketball  22-01-2024       1907     67              740343     76        9      8        0         30278        14535  Bangalore        Rainy       Draw       1               4   81929  Credit Card                 9722              12               2        278
3          1071      5195    Joe Root     Lakers  Australia   20   Other  Unknown Coach    Football  12-05-2023        387   2338              740343    108        1      3        3         30278        10057     Mumbai        Sunny       Lose       1               4   81525   Netbanking                 9393              33              28        787
4          1188      5139       Smith        KKR  Sri Lanka   58   Other  Unknown Coach    Football  23-01-2024       1907   2338              740343     30        4      1        1         30278        10057  Bangalore  Unspecified       Draw       2               4   80328         Cash                 9722              62              11       1332
5          1020      5187       Virat        CSK  Australia   33    Male  Unknown Coach  Basketball  07-08-2021       1907   2338              740342    121        9      1        3          8839         3104    Chennai       Cloudy        Win       7               1   82657  Credit Card                 9722              66              23       4372
6          1102      5026      Hardik     Lakers  Sri Lanka   10    Male   Rahul Dravid     Cricket  19-05-2022       1907   2925              730707    106        3      1        5         30417        10057    Kolkata        Sunny       Lose       1               3   84529          UPI                17522             107              23       3147
8          1074      5022       Virat        KKR      India   11    Male     John Smith      Tennis  03-12-2023       1907   2338              835031    132        0      6        2         27302        13721  Bangalore       Cloudy        Win       1               3   83205   Netbanking                  240              59              12       3449
9          1116      5020     Ronaldo     Lakers  Australia   38  Female  Unknown Coach    Football  03-12-2023        909   2338              740342    155        9      1        0         30456        10057  Bangalore        Rainy       Lose       1               4   83851         Cash                 9722              91               7       1009
10         1052      5152      Hardik     Lakers    England   50  Female     John Smith    Football  05-12-2023       1907   1846              740342     70        0      8        0         39669        18222  Bangalore       Cloudy        Win       1               4   84659   Netbanking                 7545              60               9        935
11         1001      5054   Anonymous     Lakers  Sri Lanka   53    Male  Unknown Coach      Tennis  03-03-2023       1907   1890              996837    165        1      1        1         30278        10057      Delhi        Rainy        Win       1               4   84398         Cash                 9722              15              28       3518
12         1087      5045       Rohit         MI      India   56  Female     John Smith    Football  07-07-2023       1907   2338              597941     66        0      7        1         30278        10057  Bangalore        Rainy       Lose       5               1   84044  Credit Card                12815              65               5       3787
13         1037      5054    Joe Root        CSK    England   45    Male     John Smith       other  05-12-2023       1907   2338              811576    108        1      8        5         14156        10543  Bangalore        Sunny        Win       8               3   82604         Cash                10842             112              17        495
14         1129      5095    Joe Root        CSK      India   14  Female   Rahul Dravid  Basketball  21-08-2022       1907    122              740343    166        0      9        0         30278         8106  Bangalore        Rainy        Win       8               4   82023   Netbanking                 2254              60              16       3592
15         1020      5109    Joe Root        CSK  Sri Lanka   13  Female  Unknown Coach      Tennis  14-11-2021       2632   2338              740342     85        9      9        3         30278         7054    Gujarat        Rainy        Win       1               4   84603         Cash                 9722              60               1       2935
16         1048      5079       Smith  Barcelona  Australia   41    Male  Unknown Coach    Football  12-06-2021       1620   2338              740342     32        9      3        4         28270        10057  Bangalore       Cloudy        Win      10               4   81790  Credit Card                15884               0              15        905
17         1169      5112       Messi  Barcelona  Australia   44  Female  Unknown Coach    Football  05-12-2023       1427   2338              369706     41        5      9        4         38521         8764     Mumbai        Rainy        Win       1               3   82789   Netbanking                19875               6               8       1827
18         1187      5060      Bumrah        CSK      India   52    Male  Unknown Coach       other  05-12-2023       1907   2338              446653    111        2      3        3         30278         2084    Chennai       Cloudy        Win       1               4   82184          UPI                 8796              19              24       3722
19         1014      5136       Smith        KKR      India   42    Male  Unknown Coach    Football  21-03-2020       1907   2267              474567    125        8      2        5         30278        13454  Bangalore        Rainy        Win       1               1   80538         Cash                 9722             118              24       2580
20         1189      5005    Joe Root        KKR      India   41  Female  Unknown Coach  Basketball  20-01-2022       1907    189              740342    154        4      2        4         30278        10057     Mumbai        Rainy        Win       8               1   84784  Credit Card                 7650              38              23       4597
22         1107      5168       Virat         MI  Sri Lanka   20    Male  Unknown Coach  Basketball  05-07-2022       3412   2620              262307    112        5      4        4         32080         9882    Gujarat        Rainy        Win       3               1   80724         Cash                13804              60               6        111
23         1063      5004       Messi        CSK      India   28  Female  Unknown Coach  Basketball  10-01-2020       4086   1343              740343    122        5      4        0         10987        12869      Delhi        Rainy        Win       7               4   82435         Cash                11031              60              10       2302
24         1130      5169   Anonymous        CSK      India   16    Male  Unknown Coach      Tennis  13-10-2022       1907   2090              740342    113        7      0        0         30278        10057    Gujarat       Cloudy        Win       1               4   82340  Credit Card                12543              60               0       1650
25         1134      5075       Rohit         MI  Sri Lanka   56  Female  Unknown Coach     Cricket  13-01-2022       2472   2731              740342     15        9      4        5         30278        10057    Chennai       Cloudy        Win       9               4   81903          UPI                 9722              26              20       2474
26         1072      5157      Hardik         MI  Sri Lanka   26    Male  Unknown Coach    Football  05-12-2023        450   2338              740342     18        7      6        5         16432        10057    Gujarat        Sunny       Lose       1               4   83383         Cash                 5504              60              18       1890
28         1131      5028       Virat     Lakers      India   35    Male  Unknown Coach     Cricket  22-11-2021       1907   1687              740343    165        0      8        5         30278        10057      Delhi        Rainy       Draw       1               4   84861          UPI                 1251              60              27       3101
29         1059      5086      Bumrah     Lakers  Australia   35  Female  Unknown Coach  Basketball  02-03-2023       3030   1080              740343    180        6      1        1         30278        10057     Mumbai        Rainy        Win       8               4   80095         Cash                12429              73              28       1427
30         1013      5140       Messi  Barcelona      India   32    Male   Rahul Dravid    Football  04-03-2021       1907   2777              740342     92        9      1        3         28501        10696      Delhi        Rainy       Lose       9               2   81283         Cash                 9722               1              23       3102
31         1089      5045       Messi  Barcelona      India   39  Female  Unknown Coach    Football  25-04-2023       2535   2338              740342     99        9      0        0         30278        17623    Kolkata        Rainy        Win       8               4   80981   Netbanking                 9722              88              21       1455
32         1129      5111    Joe Root         MI  Australia   39    Male   Rahul Dravid    Football  25-04-2023       3026   2338              740343    158        8      9        1         32600        13146  Bangalore        Rainy        Win       1               4   81565   Netbanking                 9722               7              22       1346
33         1091      5044       Rohit        KKR      India   28    Male  Unknown Coach     Cricket  27-05-2021       3066   2338              250729    187        6      4        4         30278        15677     Mumbai        Rainy       Draw       1               4   80735         Cash                14758              60              25       1214
34         1198      5084      Bumrah  Barcelona  Sri Lanka   47  Female  Unknown Coach       other  05-12-2020       1907   1768              713588     78        1      2        3         23059         1988      Delhi       Cloudy       Draw       6               4   80448  Credit Card                 8922              60               9       4612
35         1034      5017     Ronaldo        RCB  Australia   58    Male     John Smith    Football  20-11-2023       1907   2365              740342    175        1      4        0         22991        10057     Mumbai        Sunny        Win       6               1   81433  Credit Card                13058             120               7       2858
36         1080      5093      Bumrah        RCB  Australia   57  Female  Unknown Coach      Tennis  22-03-2020       1907   1730              740342    139        3      0        0         30278         2525     Mumbai  Unspecified        Win       1               5   80876          UPI                 9722              68              21        761
37         1163      5149       Dhoni     Lakers  Australia   26    Male  Unknown Coach     Cricket  12-05-2023       1907   2338              369408     95        2      1        0         30278         2000  Bangalore        Sunny        Win       9               4   82575         Cash                12407              60              26       2366
38         1049      5032       Smith        RCB  Sri Lanka   57  Female  Unknown Coach       other  09-12-2021       1907   2338              555903     88        3      0        5         30278        10057    Kolkata       Cloudy       Draw       1               4   81133         Cash                 9722              60              12       4206
39         1131      5125       Smith        RCB      India   52    Male  Unknown Coach  Basketball  05-12-2023       1132   2338              683275    145        6      8        0         37459        14224  Bangalore        Rainy       Draw       1               5   80671  Credit Card                13833              88               6       4902
42         1145      5027       Virat        CSK      India   27  Female     John Smith      Tennis  10-04-2023       5231   2338              740342    196        1      4        5         38750        10825  Bangalore        Sunny       Lose       1               4   80066  Credit Card                 9722              32              24       3376
43         1161      5166    Joe Root        CSK      India   45  Female  Unknown Coach  Basketball  31-05-2021       1907    923              740342    135        4      4        4         43841        10057     Mumbai  Unspecified       Lose       1               4   82090   Netbanking                 9722              60              21        834
44         1094      5146    Joe Root        CSK      India   44    Male   Rahul Dravid  Basketball  07-04-2020       1907   2338              740343    125        8      6        3         30278        10057  Bangalore        Sunny        Win       1               4   80233         Cash                 9722              18              13       1564
45         1014      5142       Dhoni  Barcelona  Australia   19  Female     John Smith       other  17-05-2022         55   1360              740342     85        6      1        4         48081        10057    Gujarat  Unspecified       Lose       7               4   82544         Cash                 9722              53              25        496
46         1189      5155      Bumrah        CSK      India   28    Male  Unknown Coach  Basketball  22-08-2023       1907   2338              740342    137        2      7        0         30278        12492     Mumbai        Rainy       Lose       1               4   84554          UPI                 9722              60              29       2263
47         1081      5071      Hardik         MI      India   11    Male  Unknown Coach       other  08-11-2021         16   2954              740343    120        4      5        2         28982          855    Chennai        Rainy        Win       4               3   81169  Credit Card                 9722              60               5        915
48         1110      5106    Joe Root        KKR    England   42  Female  Unknown Coach       other  12-06-2021       1907   2338              740342     75        2      9        4         42916          209    Kolkata        Rainy       Draw       6               4   84101   Netbanking                 9722              63              21       1801
49         1023      5174       Messi        KKR      India   11   Other   Rahul Dravid      Tennis  12-06-2021       2396   2338              597878     69        2      6        1         20896         5586      Delhi        Rainy        Win       4               3   83179   Netbanking                 9722              48               6         81
50         1187      5189    Joe Root        KKR    England   27    Male     John Smith  Basketball  18-11-2023       1907   2338              740342    132        0      6        1         29759        10057     Mumbai        Rainy        Win       1               3   81363  Credit Card                 9722              60              24        165
51         1040      5194       Messi     Lakers  Sri Lanka   20    Male  Unknown Coach       other  09-06-2022       4629   2338              740342    136        7      2        1         47973        16805     Mumbai        Rainy        Win       9               4   81056          UPI                 9722              60              12       2071
52         1156      5073     Ronaldo        RCB  Australia   30    Male  Unknown Coach     Cricket  20-09-2023       1907   2338              740342     57        2      1        4         30278         2185      Delhi  Unspecified       Lose      10               5   80142          UPI                 7883              61              28        806
53         1044      5174       Virat         MI    England   42  Female  Unknown Coach    Football  25-05-2021       1907   2032               96295    181        1      3        2         30278        10057    Gujarat        Rainy       Draw       3               4   84831  Credit Card                18399              69               8        331
54         1064      5192    Joe Root         MI      India   11  Female     John Smith  Basketball  05-12-2023       2005    190              740342     45        1      7        1         30278        10057    Kolkata        Rainy        Win       1               3   82773          UPI                 9722              60              14       3590
55         1088      5156   Anonymous  Barcelona  Australia   60    Male  Unknown Coach    Football  17-12-2022       5287   2338              740342     21        6      1        4         36935        10057  Bangalore        Rainy       Draw       9               4   81884  Credit Card                19837              60              11       1534
56         1070      5177       Messi        KKR    England   60    Male  Unknown Coach  Basketball  22-05-2023       4012   2669              740343    191        9      3        1         12738        10057  Bangalore       Cloudy       Draw       1               3   82264  Credit Card                 2743              60              26        180
57         1135      5161     Ronaldo        CSK    England   55    Male     John Smith    Football  15-12-2023       1907   2338              740342    178        5      0        0         30278        12520     Mumbai        Rainy       Draw       6               4   81890  Credit Card                 9722              15               4       2486
58         1062      5092       Dhoni     Lakers  Australia   40  Female  Unknown Coach       other  07-05-2020       1907   2338              907655     77        9      3        0         30278         4723    Kolkata        Rainy        Win       1               3   83125   Netbanking                 9722              59               6       2590
59         1138      5175       Dhoni  Barcelona  Australia   41   Other   Rahul Dravid  Basketball  27-02-2020       1907   2014              740342     38        2      1        1         30278        10057    Gujarat        Rainy        Win       1               4   80941         Cash                16349              53              27       2240

Fetching matches where Win_Status="Win" and Score > 100.

In [ ]:
print(df[(df['Win_Status'] == 'Win') & (df['Score'] > 100)].to_string())

      Player_Id  Match_Id Player_Name       Team    Country  Age  Gender     Coach_Name  Sport_Type  Match_Date  Match_Fee  Bonus  Sponsorship_Amount  Score  Assists  Goals  Wickets  Ticket_Sales  Merch_Sales      Venue      Weather Win_Status  Rating  Feedback_Score  Fan_Id Payment_Mode  Fan_Purchase_Amount  Minutes_Played  Matches_Played  Fan_Count
5          1020      5187       Virat        CSK  Australia   33    Male  Unknown Coach  Basketball  07-08-2021       1907   2338              740342    121        9      1        3          8839         3104    Chennai       Cloudy        Win       7               1   82657  Credit Card                 9722              66              23       4372
8          1074      5022       Virat        KKR      India   11    Male     John Smith      Tennis  03-12-2023       1907   2338              835031    132        0      6        2         27302        13721  Bangalore       Cloudy        Win       1               3   83205   Netbanking                  240              59              12       3449
11         1001      5054   Anonymous     Lakers  Sri Lanka   53    Male  Unknown Coach      Tennis  03-03-2023       1907   1890              996837    165        1      1        1         30278        10057      Delhi        Rainy        Win       1               4   84398         Cash                 9722              15              28       3518
13         1037      5054    Joe Root        CSK    England   45    Male     John Smith       other  05-12-2023       1907   2338              811576    108        1      8        5         14156        10543  Bangalore        Sunny        Win       8               3   82604         Cash                10842             112              17        495
14         1129      5095    Joe Root        CSK      India   14  Female   Rahul Dravid  Basketball  21-08-2022       1907    122              740343    166        0      9        0         30278         8106  Bangalore        Rainy        Win       8               4   82023   Netbanking                 2254              60              16       3592
18         1187      5060      Bumrah        CSK      India   52    Male  Unknown Coach       other  05-12-2023       1907   2338              446653    111        2      3        3         30278         2084    Chennai       Cloudy        Win       1               4   82184          UPI                 8796              19              24       3722
19         1014      5136       Smith        KKR      India   42    Male  Unknown Coach    Football  21-03-2020       1907   2267              474567    125        8      2        5         30278        13454  Bangalore        Rainy        Win       1               1   80538         Cash                 9722             118              24       2580
20         1189      5005    Joe Root        KKR      India   41  Female  Unknown Coach  Basketball  20-01-2022       1907    189              740342    154        4      2        4         30278        10057     Mumbai        Rainy        Win       8               1   84784  Credit Card                 7650              38              23       4597
22         1107      5168       Virat         MI  Sri Lanka   20    Male  Unknown Coach  Basketball  05-07-2022       3412   2620              262307    112        5      4        4         32080         9882    Gujarat        Rainy        Win       3               1   80724         Cash                13804              60               6        111
23         1063      5004       Messi        CSK      India   28  Female  Unknown Coach  Basketball  10-01-2020       4086   1343              740343    122        5      4        0         10987        12869      Delhi        Rainy        Win       7               4   82435         Cash                11031              60              10       2302
24         1130      5169   Anonymous        CSK      India   16    Male  Unknown Coach      Tennis  13-10-2022       1907   2090              740342    113        7      0        0         30278        10057    Gujarat       Cloudy        Win       1               4   82340  Credit Card                12543              60               0       1650
29         1059      5086      Bumrah     Lakers  Australia   35  Female  Unknown Coach  Basketball  02-03-2023       3030   1080              740343    180        6      1        1         30278        10057     Mumbai        Rainy        Win       8               4   80095         Cash                12429              73              28       1427
32         1129      5111    Joe Root         MI  Australia   39    Male   Rahul Dravid    Football  25-04-2023       3026   2338              740343    158        8      9        1         32600        13146  Bangalore        Rainy        Win       1               4   81565   Netbanking                 9722               7              22       1346
35         1034      5017     Ronaldo        RCB  Australia   58    Male     John Smith    Football  20-11-2023       1907   2365              740342    175        1      4        0         22991        10057     Mumbai        Sunny        Win       6               1   81433  Credit Card                13058             120               7       2858
36         1080      5093      Bumrah        RCB  Australia   57  Female  Unknown Coach      Tennis  22-03-2020       1907   1730              740342    139        3      0        0         30278         2525     Mumbai  Unspecified        Win       1               5   80876          UPI                 9722              68              21        761
40         1133      5169       Messi        KKR      India   41  Female  Unknown Coach  Basketball  18-09-2022       1907   2338              740342    121        7      4        2          2826        17165      Delhi       Cloudy        Win       6               4   83318         Cash                 6443              98               3       3919
44         1094      5146    Joe Root        CSK      India   44    Male   Rahul Dravid  Basketball  07-04-2020       1907   2338              740343    125        8      6        3         30278        10057  Bangalore        Sunny        Win       1               4   80233         Cash                 9722              18              13       1564
47         1081      5071      Hardik         MI      India   11    Male  Unknown Coach       other  08-11-2021         16   2954              740343    120        4      5        2         28982          855    Chennai        Rainy        Win       4               3   81169  Credit Card                 9722              60               5        915
50         1187      5189    Joe Root        KKR    England   27    Male     John Smith  Basketball  18-11-2023       1907   2338              740342    132        0      6        1         29759        10057     Mumbai        Rainy        Win       1               3   81363  Credit Card                 9722              60              24        165
51         1040      5194       Messi     Lakers  Sri Lanka   20    Male  Unknown Coach       other  09-06-2022       4629   2338              740342    136        7      2        1         47973        16805     Mumbai        Rainy        Win       9               4   81056          UPI                 9722              60              12       2071
63         1122      5038      Hardik  Barcelona      India   52  Female   Rahul Dravid       other  26-12-2020       1907   2338              740343    103        0      6        3         49301         5226    Gujarat        Rainy        Win       1               4   81058  Credit Card                 9722              47               3       1456
66         1071      5070     Ronaldo         MI      India   37   Other  Unknown Coach    Football  03-08-2020       1907   2338              740343    171        5      5        3         30278        19171    Kolkata        Rainy        Win       7               1   84866  Credit Card                 9722             114              21       2200
71         1192      5061   Anonymous         MI    England   44    Male  Unknown Coach     Cricket  05-12-2023       1907   2564              740342    130        7      2        5         30278        19550    Gujarat       Cloudy        Win       6               4   81673   Netbanking                 9722              77              16       2984
79         1142      5168     Ronaldo  Barcelona  Australia   19    Male  Unknown Coach  Basketball  16-09-2022       1253   2338              147087    159        9      9        0         31725        10057  Bangalore        Sunny        Win       8               4   84227         Cash                 -851              42               7       1567
82         1035      5117       Rohit        RCB    England   22    Male  Unknown Coach  Basketball  25-09-2023       1907   1575              740342    101        2      9        1          9326        10057  Bangalore       Cloudy        Win       4               4   80581          UPI                 9722              47              13        363
93         1026      5078       Rohit        KKR  Australia   49  Female   Rahul Dravid    Football  25-06-2021       1907   1061              740342    176        0      0        2         34155        10057    Gujarat        Sunny        Win       5               4   81141  Credit Card                 7287              60              25       2190
95         1115      5048       Virat         MI      India   25    Male  Unknown Coach  Basketball  29-11-2020       5256   2338              515844    137        1      9        2         33050        10057     Mumbai        Rainy        Win       1               4   81508         Cash                 9722              60              15       3474
97         1102      5081       Dhoni     Lakers      India   52  Female  Unknown Coach     Cricket  15-06-2022        556   1441              740342    109        9      8        2         23181        10057    Chennai        Rainy        Win       8               2   84329         Cash                 6323              15              15       1865
104        1061      5061      Bumrah     Lakers      India   48   Other  Unknown Coach    Football  27-08-2020       1907    838              475305    198        0      8        1         13882         5681    Kolkata        Rainy        Win       1               4   83199          UPI                15318              60              25       3881
107        1112      5157    Joe Root     Lakers      India   52  Female  Unknown Coach     Cricket  10-10-2022       1907    488              740342    184        9      1        3         30278         2429    Kolkata        Sunny        Win       1               2   80063   Netbanking                 9722              62               4       2123
116        1052      5057       Rohit  Barcelona    England   28    Male  Unknown Coach     Cricket  18-03-2022       2229   1046              740342    127        7      4        3         30278        10057  Bangalore  Unspecified        Win       1               4   82728  Credit Card                13047              60              11       1366
117        1171      5100    Joe Root  Barcelona      India   18    Male  Unknown Coach  Basketball  18-03-2022       1907   2338              585232    189        4      1        1         30278        10057  Bangalore        Rainy        Win       2               4   82692          UPI                15335              60              16       2926
131        1146      5188       Rohit         MI      India   39    Male     John Smith      Tennis  30-06-2023       1907   2338              740342    197        1      0        1         45326        10057  Bangalore       Cloudy        Win       2               3   82422          UPI                 9722              98              20       1332
132        1051      5015       Rohit        CSK      India   10    Male  Unknown Coach  Basketball  30-06-2023       1907   2338              740342    102        3      1        5         30278         1381    Chennai        Rainy        Win       6               4   84485  Credit Card                 9722              60              13       1244
133        1127      5058       Virat        CSK  Australia   14   Other     John Smith      Tennis  03-04-2021       1907   2338              625961    156        9      0        5         10330         5253  Bangalore       Cloudy        Win       1               4   81708         Cash                 9722               7              27        336
144        1112      5145       Rohit         MI    England   55   Other  Unknown Coach       other  07-07-2020       1907   2125              740342    192        6      1        3         30278        10057      Delhi        Sunny        Win       6               1   81770  Credit Card                  949              60              29       3480
151        1147      5148     Ronaldo     Lakers    England   21   Other   Rahul Dravid     Cricket  03-03-2021       4551   1004               55063    194        6      1        1         48465        16709    Chennai  Unspecified        Win       1               4   81559   Netbanking                 9722              27               7       4815
159        1081      5164   Anonymous     Lakers  Sri Lanka   32    Male  Unknown Coach    Football  02-10-2022       3755   2338              473995    153        8      4        1         18870        18299    Chennai        Rainy        Win      10               5   84602          UPI                 9722              60              22       3810
161        1162      5069      Hardik     Lakers      India   26    Male  Unknown Coach     Cricket  12-05-2023       1907    231              595048    160        0      4        5         30278         4011      Delhi        Rainy        Win       4               4   83144         Cash                 9722              60               0        576
170        1127      5177    Joe Root        CSK  Australia   36  Female     John Smith       other  12-10-2022        390    982              740342    156        8      7        0         29621        13373  Bangalore        Sunny        Win       1               4   84014   Netbanking                 9722              60              28       2133
181        1020      5139    Joe Root        CSK      India   34   Other  Unknown Coach     Cricket  30-08-2020       2388   2221              537669    127        2      4        3         30278        10057    Kolkata        Rainy        Win       2               4   80202          UPI                 9722              28              22       1112
184        1196      5194      Bumrah         MI    England   18  Female  Unknown Coach  Basketball  19-12-2021       1907    988              740342    112        4      1        1         30278        10057    Chennai        Sunny        Win       1               4   81979   Netbanking                 9722              45              14       3809
185        1146      5162       Virat         MI      India   28   Other  Unknown Coach     Cricket  19-04-2021       2067   1942               67734    190        3      3        3         30278        19348    Gujarat        Sunny        Win       1               5   83984         Cash                 9722              60              21       1353
186        1016      5112       Virat         MI      India   14    Male  Unknown Coach    Football  20-04-2022       1907   2338              576482    144        0      2        4         26726        10057    Gujarat        Rainy        Win       1               4   83418  Credit Card                 9722              60              24       3164
196        1159      5098      Hardik        KKR    England   44  Female     John Smith  Basketball  09-02-2020       1907   2338              740343    154        4      2        5         26920         9950      Delhi        Rainy        Win       1               4   80065          UPI                 9722              18               2       1523
200        1024      5137       Smith  Barcelona  Australia   60   Other     John Smith  Basketball  08-11-2021       3557   1197              740342    133        6      4        0          7407        10057    Kolkata        Rainy        Win       1               3   82241         Cash                 8609               1              12        895
206        1174      5193      Bumrah        CSK      India   47    Male  Unknown Coach  Basketball  17-08-2020       1907    320              791611    199        6      8        3         30278         1165    Kolkata       Cloudy        Win       1               4   81101  Credit Card                 9722              22              22       2183
215        1169      5190     Ronaldo        KKR  Australia   38  Female  Unknown Coach     Cricket  09-04-2022       1907   2338              740342    169        9      6        4          8892        10057    Chennai        Rainy        Win       5               4   83116   Netbanking                12586              78               6       4017
218        1035      5165      Hardik        KKR    England   26    Male   Rahul Dravid    Football  04-10-2022       1907    460               16231    168        8      4        4         22975        12156    Gujarat       Cloudy        Win       1               1   81358  Credit Card                18885              60              15       2793
229        1124      5149    Joe Root  Barcelona      India   53    Male  Unknown Coach      Tennis  13-01-2021       1907    161              740342    115        3      7        3         26044         9288    Gujarat        Rainy        Win       2               4   80409          UPI                 9737              60              28        218
230        1057      5064    Joe Root        KKR    England   42    Male  Unknown Coach    Football  13-10-2023       1907    952              211492    137        6      9        0         49210        10057      Delhi        Rainy        Win       3               3   80215  Credit Card                 4776              60               2       3729
238        1093      5039     Ronaldo  Barcelona      India   31   Other  Unknown Coach    Football  13-02-2020        410    159              585932    132        3      0        0         13321        12980    Gujarat        Rainy        Win       2               4   81012   Netbanking                 9722              60              17       1105
241        1167      5130    Joe Root     Lakers      India   33   Other     John Smith  Basketball  17-12-2023       1907    184              740342    119        5      3        5         30278        10057  Bangalore        Sunny        Win       7               4   81704         Cash                 9722              60              14         88
261        1047      5006       Messi        CSK  Australia   38   Other  Unknown Coach    Football  05-03-2021       4627   2338              740343    165        7      4        3         30278        11110     Mumbai        Sunny        Win       1               4   82376   Netbanking                 9722              60              28       3823
270        1184      5109    Joe Root        CSK      India   43  Female  Unknown Coach     Cricket  05-01-2023       1907   1096              605122    137        7      6        2         30278         5523  Bangalore        Sunny        Win       8               4   83307          UPI                 9722              90               0       4132

Fetching cricket players with Wickets > 3.

In [ ]:
print(df[(df['Sport_Type'] == 'Cricket') & (df['Wickets'] > 3)].to_string())

      Player_Id  Match_Id Player_Name       Team    Country  Age  Gender     Coach_Name Sport_Type  Match_Date  Match_Fee  Bonus  Sponsorship_Amount  Score  Assists  Goals  Wickets  Ticket_Sales  Merch_Sales      Venue      Weather Win_Status  Rating  Feedback_Score  Fan_Id Payment_Mode  Fan_Purchase_Amount  Minutes_Played  Matches_Played  Fan_Count
6          1102      5026      Hardik     Lakers  Sri Lanka   10    Male   Rahul Dravid    Cricket  19-05-2022       1907   2925              730707    106        3      1        5         30417        10057    Kolkata        Sunny       Lose       1               3   84529          UPI                17522             107              23       3147
25         1134      5075       Rohit         MI  Sri Lanka   56  Female  Unknown Coach    Cricket  13-01-2022       2472   2731              740342     15        9      4        5         30278        10057    Chennai       Cloudy        Win       9               4   81903          UPI                 9722              26              20       2474
28         1131      5028       Virat     Lakers      India   35    Male  Unknown Coach    Cricket  22-11-2021       1907   1687              740343    165        0      8        5         30278        10057      Delhi        Rainy       Draw       1               4   84861          UPI                 1251              60              27       3101
33         1091      5044       Rohit        KKR      India   28    Male  Unknown Coach    Cricket  27-05-2021       3066   2338              250729    187        6      4        4         30278        15677     Mumbai        Rainy       Draw       1               4   80735         Cash                14758              60              25       1214
52         1156      5073     Ronaldo        RCB  Australia   30    Male  Unknown Coach    Cricket  20-09-2023       1907   2338              740342     57        2      1        4         30278         2185      Delhi  Unspecified       Lose      10               5   80142          UPI                 7883              61              28        806
71         1192      5061   Anonymous         MI    England   44    Male  Unknown Coach    Cricket  05-12-2023       1907   2564              740342    130        7      2        5         30278        19550    Gujarat       Cloudy        Win       6               4   81673   Netbanking                 9722              77              16       2984
94         1189      5115    Joe Root         MI      India   55    Male  Unknown Coach    Cricket  12-04-2021       1907   2338              337452    112        2      7        4         30278        16954  Bangalore        Rainy       Draw       1               4   83052  Credit Card                13322              18              12       4149
146        1047      5127       Virat        CSK      India   46    Male   Rahul Dravid    Cricket  21-11-2020       1907   1253              434604     17        1      4        4          9628         2345  Bangalore  Unspecified        Win       1               4   80034         Cash                13860              16               5       4167
161        1162      5069      Hardik     Lakers      India   26    Male  Unknown Coach    Cricket  12-05-2023       1907    231              595048    160        0      4        5         30278         4011      Delhi        Rainy        Win       4               4   83144         Cash                 9722              60               0        576
177        1050      5124       Messi         MI    England   28    Male  Unknown Coach    Cricket  05-12-2023       2610   1426              770597     32        9      0        5         30278        10057      Delhi  Unspecified       Draw       1               4   83390          UPI                 1404               1               2       4345
192        1098      5099      Hardik         MI      India   22  Female  Unknown Coach    Cricket  23-05-2023       1907   2281              740342     99        2      5        5         38770         9747  Bangalore        Rainy       Draw       8               4   80382   Netbanking                 9722              69               7       1383
215        1169      5190     Ronaldo        KKR  Australia   38  Female  Unknown Coach    Cricket  09-04-2022       1907   2338              740342    169        9      6        4          8892        10057    Chennai        Rainy        Win       5               4   83116   Netbanking                12586              78               6       4017
236        1004      5111     Ronaldo        KKR  Sri Lanka   54  Female  Unknown Coach    Cricket  30-09-2020       1907   2338              740342     42        5      5        4         30278         8313      Delhi       Cloudy       Lose       1               2   84846          UPI                 3958              51               0        204
246        1144      5065     Ronaldo        CSK  Australia   44    Male  Unknown Coach    Cricket  08-01-2022       3248    798              740342    139        4      9        4         30278        10737    Kolkata        Rainy       Draw       1               4   82475  Credit Card                 6081              60              22       4671
247        1119      5035       Messi         MI    England   20    Male  Unknown Coach    Cricket  08-01-2022       1907   2338              740342     21        0      1        4         30278        10057      Delhi        Rainy       Draw       1               4   84545          UPI                 4604              38              10       2080
260        1117      5061     Ronaldo        KKR      India   17  Female  Unknown Coach    Cricket  06-05-2020       2772   2338              725410     79        7      8        5         30278         2713    Kolkata  Unspecified        Win       1               1   83126         Cash                 5927              44              27       1678
331        1051      5070       Virat     Lakers  Sri Lanka   38   Other     John Smith    Cricket  11-09-2021       1907   2019              740342    185        4      4        4         30278         9038      Delhi        Sunny        Win       1               5   81382         Cash                15520              29              17       1584
353        1082      5186       Messi  Barcelona      India   27    Male  Unknown Coach    Cricket  28-09-2023       4937   1420              740343     76        0      5        4         30278        10057    Kolkata       Cloudy       Lose       7               4   84674  Credit Card                 5067              60               4       1878
370        1112      5058       Messi        CSK      India   41    Male  Unknown Coach    Cricket  26-06-2022       1907   1065              740342     99        1      7        4         30278        10057    Gujarat        Rainy        Win       7               4   84174          UPI                 9722               9              15       3674
400        1133      5159       Dhoni        CSK      India   54  Female  Unknown Coach    Cricket  18-09-2020       1907    198              740342    178        7      7        4         30278        10057    Kolkata        Rainy        Win       7               4   84272          UPI                12978              46               2       1247
407        1010      5148      Bumrah        CSK  Sri Lanka   40   Other  Unknown Coach    Cricket  21-09-2020       1907   2338              740342    168        7      4        4         30278        10057     Mumbai        Rainy       Lose       1               2   81191   Netbanking                 9722              76              26       2803
425        1117      5136      Hardik         MI    England   15   Other     John Smith    Cricket  05-12-2023       1761   2338              740343    194        4      4        5         30278         1724     Mumbai       Cloudy       Draw       2               4   82208  Credit Card                 9722              64              16        987
465        1092      5195       Virat        KKR  Australia   33  Female   Rahul Dravid    Cricket  28-10-2023       1907   2064              740342     27        2      2        4         30278        10057      Delhi        Rainy        Win       4               4   80269   Netbanking                 1392              69              29       3296
466        1159      5090      Hardik  Barcelona      India   48    Male  Unknown Coach    Cricket  12-05-2023       1907   2338              740342     65        4      9        4         30278        17893    Gujarat        Sunny        Win       1               4   81855  Credit Card                18292              52              13       4570
540        1178      5060       Rohit         MI    England   33  Female     John Smith    Cricket  19-11-2023       1907   2338              740343    190        8      9        5         30278        10057  Bangalore        Sunny       Draw       2               4   80636         Cash                 9491              60              10       4145
543        1078      5106   Anonymous        RCB      India   29    Male   Rahul Dravid    Cricket  23-11-2022       1907   2338              740343    167        3      7        4         30278        10057     Mumbai       Cloudy        Win       1               4   81415  Credit Card                 6108              60              26       4082
575        1177      5121   Anonymous     Lakers      India   35    Male  Unknown Coach    Cricket  21-11-2023        141   1704              740342     89        6      0        5         24717         1118    Kolkata        Rainy        Win       6               4   82520   Netbanking                 6772              51              29       4771
583        1063      5005       Messi  Barcelona    England   16    Male  Unknown Coach    Cricket  03-04-2023       1907   2338              740343     71        6      7        4         30278        10057  Bangalore       Cloudy        Win       8               2   81135   Netbanking                 9722              60              11       1525
593        1038      5111       Virat     Lakers      India   38   Other  Unknown Coach    Cricket  28-11-2022       1907    853              740342    159        7      4        5         30278        10057    Kolkata        Rainy       Lose       6               2   81226         Cash                13467             105              16         59
653        1163      5069       Virat        CSK    England   26    Male     John Smith    Cricket  06-12-2023       1907   2338              265323     97        4      3        4         49089        10057    Kolkata       Cloudy       Lose       1               4   83103         Cash                 1926             119               5       3983
665        1168      5099       Smith         MI  Australia   46    Male  Unknown Coach    Cricket  02-05-2021       1907   2338              740343     75        6      2        4         22564        19129     Mumbai        Rainy        Win       8               1   82038         Cash                 1438              60              16       4768
695        1061      5115       Dhoni        KKR  Sri Lanka   10    Male  Unknown Coach    Cricket  22-09-2020       1907   2338              740342    137        5      0        4         30278        10057  Bangalore  Unspecified        Win       1               1   84014         Cash                18531             109               7       4976
697        1028      5193     Ronaldo        RCB      India   11   Other  Unknown Coach    Cricket  01-04-2022       2951    208              740343    176        1      5        4         30278         5607    Chennai        Rainy       Lose       1               4   81891          UPI                 9722              60              17        309
711        1031      5180     Ronaldo        RCB      India   29    Male  Unknown Coach    Cricket  12-05-2023        450    232              164778     12        6      1        5         23289        10057  Bangalore        Sunny        Win       6               4   80882  Credit Card                 9722              60              21       2343
733        1001      5065       Rohit        KKR      India   32    Male  Unknown Coach    Cricket  01-05-2022       1907    577              740343    186        4      4        5         30278        10057      Delhi        Rainy        Win       1               4   83172  Credit Card                 9722              53              11       3856
757        1121      5095   Anonymous         MI  Australia   46    Male  Unknown Coach    Cricket  03-03-2020       1907   2992              740342     64        4      2        5         30278         7492      Delhi        Rainy        Win       1               4   80442   Netbanking                 9722             104               4       3163
785        1100      5015      Hardik         MI  Sri Lanka   33    Male  Unknown Coach    Cricket  05-12-2023       1907   1781              904073     51        0      9        4         30278        16889    Gujarat        Rainy       Lose       1               4   82219   Netbanking                16421              60              13       3051
820        1159      5010      Hardik        CSK  Sri Lanka   37    Male  Unknown Coach    Cricket  27-04-2021       2680   1338              740342    180        2      5        5         26409        10675  Bangalore       Cloudy       Lose       1               3   80248          UPI                 9722              60              12       1200
859        1122      5003       Dhoni        KKR    England   42    Male  Unknown Coach    Cricket  29-12-2022       2656   1064              740342    195        9      7        4         47648        10057    Kolkata        Rainy       Lose       1               4   80203  Credit Card                 2660              76              29       4117
919        1191      5184    Joe Root        CSK  Sri Lanka   33  Female     John Smith    Cricket  19-12-2021       2123   2338              858285    136        5      4        4         49884        10057  Bangalore        Sunny        Win       1               4   82129  Credit Card                 9722              32               0       4195
920        1087      5084       Smith         MI      India   41    Male   Rahul Dravid    Cricket  25-06-2023       1907    444              740342    105        4      7        5         30278        10057  Bangalore        Rainy        Win       1               4   84116         Cash                 9722              60               2       2714
981        1016      5012   Anonymous     Lakers      India   39  Female     John Smith    Cricket  12-05-2023       1907   1886              740342    167        4      0        4         30278         1633    Kolkata        Rainy        Win       1               5   81001          UPI                14571              60              20        256
986        1187      5110    Joe Root        CSK      India   42  Female  Unknown Coach    Cricket  21-10-2020        177   2591              646189    110        7      9        5         25658        10057  Bangalore       Cloudy       Draw       9               4   82742         Cash                 5957              81              11       4892
1016       1121      5187       Rohit        CSK  Sri Lanka   24  Female  Unknown Coach    Cricket  05-12-2023        599   2631               89905    154        4      9        4         30278        10057  Bangalore        Sunny        Win       1               4   83588   Netbanking                 -557              89              20       3721
1056       1023      5124       Messi         MI    England   25    Male  Unknown Coach    Cricket  09-05-2021       1907   2338              740342     42        5      0        5         12122        10057  Bangalore        Rainy        Win       1               3   83426          UPI                 2311              49              15       4438
1076       1007      5047       Dhoni     Lakers      India   24  Female     John Smith    Cricket  11-10-2023       1654   2752              740342    193        2      9        5         30278        10021    Gujarat        Rainy       Draw       6               4   83380          UPI                 9722              60               9       4482
1092       1088      5051    Joe Root     Lakers      India   40  Female  Unknown Coach    Cricket  14-09-2021       1907   2338              740342      7        0      9        4          4080        10057    Chennai        Rainy       Lose       5               4   80274          UPI                 9722              30              24       3706
1125       1178      5098   Anonymous        RCB  Sri Lanka   11    Male   Rahul Dravid    Cricket  29-01-2024       3723   2338              849709    184        0      6        5         30278         1735  Bangalore        Rainy        Win       1               4   81747   Netbanking                 9722             109              16       2035
1211       1142      5033       Smith        KKR  Australia   51    Male   Rahul Dravid    Cricket  04-07-2021       2876   2338              124411    133        1      6        5         37647        10057  Bangalore        Rainy        Win       1               4   81712         Cash                 9722              95              21        196
1326       1192      5001    Joe Root        KKR    England   32    Male  Unknown Coach    Cricket  04-02-2020       1907    110              740342    193        7      0        4         30278        10057  Bangalore        Rainy        Win       1               4   84171   Netbanking                 9722              48               7       1191
1331       1054      5031      Bumrah  Barcelona    England   12  Female  Unknown Coach    Cricket  12-05-2020       3700    935              285843    147        2      0        5         30278        10057    Kolkata        Sunny       Draw       1               4   83583  Credit Card                17989              54              18       2490
1362       1077      5187       Smith     Lakers  Sri Lanka   20   Other  Unknown Coach    Cricket  28-11-2023       3136   2134              740342      6        0      5        4         30278        15392      Delhi       Cloudy        Win       1               2   84567  Credit Card                 9722              60              11       3169
1366       1042      5055      Bumrah     Lakers  Australia   22  Female  Unknown Coach    Cricket  29-12-2023       1907   1458               93402     33        1      9        4         26100        10057    Chennai        Rainy        Win       1               4   81658   Netbanking                 -864              67              12       2681
1395       1182      5148     Ronaldo        RCB  Sri Lanka   18    Male  Unknown Coach    Cricket  01-02-2024       3657   2435              740342    155        1      6        5         30278        15724     Mumbai        Rainy        Win       5               2   82192          UPI                 9722              70              19       2430
1404       1187      5131   Anonymous        KKR    England   57  Female  Unknown Coach    Cricket  14-12-2021       1907   2338              740342    166        4      8        5          2487        10057    Gujarat       Cloudy       Lose       1               5   81226  Credit Card                 9722              60               6       1781

Fetching football players with Goals >= 2.

In [ ]:
print(df[(df['Sport_Type'] == 'Football') & (df['Goals'] >= 2)].to_string())

      Player_Id  Match_Id Player_Name       Team    Country  Age  Gender     Coach_Name Sport_Type  Match_Date  Match_Fee  Bonus  Sponsorship_Amount  Score  Assists  Goals  Wickets  Ticket_Sales  Merch_Sales      Venue      Weather Win_Status  Rating  Feedback_Score  Fan_Id Payment_Mode  Fan_Purchase_Amount  Minutes_Played  Matches_Played  Fan_Count
3          1071      5195    Joe Root     Lakers  Australia   20   Other  Unknown Coach   Football  12-05-2023        387   2338              740343    108        1      3        3         30278        10057     Mumbai        Sunny       Lose       1               4   81525   Netbanking                 9393              33              28        787
7          1121      5055      Hardik        RCB      India   30  Female  Unknown Coach   Football  08-02-2024        761   2338              740342     53        7      5        3          3528        10057  Bangalore        Rainy       Lose       6               4   80587  Credit Card                 5898              60              18       2345
10         1052      5152      Hardik     Lakers    England   50  Female     John Smith   Football  05-12-2023       1907   1846              740342     70        0      8        0         39669        18222  Bangalore       Cloudy        Win       1               4   84659   Netbanking                 7545              60               9        935
12         1087      5045       Rohit         MI      India   56  Female     John Smith   Football  07-07-2023       1907   2338              597941     66        0      7        1         30278        10057  Bangalore        Rainy       Lose       5               1   84044  Credit Card                12815              65               5       3787
16         1048      5079       Smith  Barcelona  Australia   41    Male  Unknown Coach   Football  12-06-2021       1620   2338              740342     32        9      3        4         28270        10057  Bangalore       Cloudy        Win      10               4   81790  Credit Card                15884               0              15        905
17         1169      5112       Messi  Barcelona  Australia   44  Female  Unknown Coach   Football  05-12-2023       1427   2338              369706     41        5      9        4         38521         8764     Mumbai        Rainy        Win       1               3   82789   Netbanking                19875               6               8       1827
19         1014      5136       Smith        KKR      India   42    Male  Unknown Coach   Football  21-03-2020       1907   2267              474567    125        8      2        5         30278        13454  Bangalore        Rainy        Win       1               1   80538         Cash                 9722             118              24       2580
21         1189      5038       Virat  Barcelona  Sri Lanka   42  Female  Unknown Coach   Football  17-05-2022       1907   2338              786510    105        5      8        4          1440        14806  Bangalore        Rainy       Draw       1               1   80305   Netbanking                 9722              60              26       4806
26         1072      5157      Hardik         MI  Sri Lanka   26    Male  Unknown Coach   Football  05-12-2023        450   2338              740342     18        7      6        5         16432        10057    Gujarat        Sunny       Lose       1               4   83383         Cash                 5504              60              18       1890
32         1129      5111    Joe Root         MI  Australia   39    Male   Rahul Dravid   Football  25-04-2023       3026   2338              740343    158        8      9        1         32600        13146  Bangalore        Rainy        Win       1               4   81565   Netbanking                 9722               7              22       1346
35         1034      5017     Ronaldo        RCB  Australia   58    Male     John Smith   Football  20-11-2023       1907   2365              740342    175        1      4        0         22991        10057     Mumbai        Sunny        Win       6               1   81433  Credit Card                13058             120               7       2858
41         1190      5161       Virat        RCB      India   13  Female  Unknown Coach   Football  16-09-2021       1907   2036              534886     61        0      8        4          4787        10623  Bangalore  Unspecified        Win       1               4   81783          UPI                 9576              15              20       2043
53         1044      5174       Virat         MI    England   42  Female  Unknown Coach   Football  25-05-2021       1907   2032               96295    181        1      3        2         30278        10057    Gujarat        Rainy       Draw       3               4   84831  Credit Card                18399              69               8        331
61         1162      5060    Joe Root  Barcelona  Sri Lanka   31  Female  Unknown Coach   Football  05-09-2021       4016   1747              740342     74        7      5        3         30278          231    Chennai        Rainy       Lose       9               4   84150         Cash                 9722              60              12       3194
62         1032      5156      Hardik        KKR      India   51  Female  Unknown Coach   Football  12-05-2023        690   1154              740342    117        7      2        3         11761        18699    Kolkata        Rainy       Draw       1               4   81471          UPI                 5321               5              27       1397
66         1071      5070     Ronaldo         MI      India   37   Other  Unknown Coach   Football  03-08-2020       1907   2338              740343    171        5      5        3         30278        19171    Kolkata        Rainy        Win       7               1   84866  Credit Card                 9722             114              21       2200
67         1150      5194       Dhoni  Barcelona  Sri Lanka   53    Male  Unknown Coach   Football  15-10-2021       1907   1319              280722     61        2      5        0         14556        10057  Bangalore       Cloudy       Lose       6               2   81617  Credit Card                 1699              60              25       2114
69         1098      5048       Virat        KKR  Australia   53    Male  Unknown Coach   Football  29-10-2021       1907   1444              740342     55        4      7        2         31902          236     Mumbai        Rainy        Win       7               4   83757          UPI                 9722              60              26        377
76         1095      5055      Bumrah         MI  Sri Lanka   50    Male  Unknown Coach   Football  11-09-2022       3597   1349              499910    186        2      3        2         17244        19931  Bangalore       Cloudy       Draw       8               4   84151   Netbanking                 9722              45              12       4657
77         1051      5064      Bumrah        CSK      India   60  Female   Rahul Dravid   Football  23-11-2021       1907   2338              740343     61        8      5        0         30278        10057    Chennai        Rainy        Win       9               4   83659  Credit Card                 9722              60               0       4608
81         1028      5178       Dhoni     Lakers      India   60    Male  Unknown Coach   Football  04-07-2021       1151   1076              740342     10        5      5        4          1411         7571    Chennai        Rainy       Lose       8               4   82157   Netbanking                 9722              60              22        966
84         1065      5172      Bumrah        RCB    England   17    Male  Unknown Coach   Football  26-11-2021       1504    782              740343    144        3      7        3         30278        10057    Chennai        Rainy       Draw       1               4   83268   Netbanking                 9722              20              18       3865
88         1184      5180    Joe Root        RCB    England   50    Male  Unknown Coach   Football  06-07-2022       2375   2338              570811     18        3      2        5          8352         2914    Chennai        Sunny       Lose       4               5   81206          UPI                 9722              60              20       3521
90         1083      5127       Rohit        CSK      India   44  Female     John Smith   Football  10-07-2022       1907   2338              495605     46        3      9        1         32405        10057    Chennai        Sunny       Lose       1               4   84005         Cash                13572              84              16       2270
99         1136      5078       Smith        CSK  Sri Lanka   34  Female   Rahul Dravid   Football  22-11-2020       1907   2338              910559    163        3      9        1         30278        10057  Bangalore        Rainy       Draw       1               4   81750         Cash                 9722              38              23       3391
101        1058      5002      Hardik        CSK      India   60    Male  Unknown Coach   Football  16-05-2021       1907   1473              740343     24        6      9        5         30278        10057    Gujarat  Unspecified       Lose       1               2   80356   Netbanking                 9722              60              23       4814
104        1061      5061      Bumrah     Lakers      India   48   Other  Unknown Coach   Football  27-08-2020       1907    838              475305    198        0      8        1         13882         5681    Kolkata        Rainy        Win       1               4   83199          UPI                15318              60              25       3881
106        1112      5095       Dhoni  Barcelona      India   16  Female  Unknown Coach   Football  23-01-2022       2163   2960                4237    190        5      2        0         30278        16579  Bangalore        Rainy       Draw       3               4   83195         Cash                 5675              76              24       3096
108        1080      5061       Virat        RCB  Sri Lanka   12    Male  Unknown Coach   Football  02-12-2021       4606   1668              863752     22        4      9        3         30278        10057    Chennai        Rainy       Draw       2               4   82812  Credit Card                 9687              60              15       4994
118        1197      5172       Rohit  Barcelona      India   55    Male  Unknown Coach   Football  05-02-2022       4251   2261              740342     30        7      9        1         11106        15568  Bangalore        Rainy       Lose       6               4   80404          UPI                 9722              94              18       1064
119        1159      5061       Messi     Lakers  Australia   24  Female   Rahul Dravid   Football  16-10-2021       2828   1595              116736    129        7      7        3         30278        15764    Gujarat  Unspecified       Draw       1               2   82873  Credit Card                14897              60              17        517
123        1115      5091       Smith         MI  Australia   26    Male   Rahul Dravid   Football  08-08-2021         89   2338              740342     28        1      5        4         30278        12881      Delhi        Rainy        Win       3               2   81540   Netbanking                  667              60               9        810
125        1138      5133       Dhoni        KKR    England   44    Male  Unknown Coach   Football  15-02-2020       2546   2338              740342    166        8      4        3         30278        10057    Chennai  Unspecified       Lose       5               4   82463          UPI                15147              76              12         76
126        1096      5185       Dhoni        CSK      India   14    Male   Rahul Dravid   Football  20-03-2020       1907   2338              693413     36        7      4        2         15688        15317  Bangalore        Rainy       Lose       1               3   82985         Cash                 9722              60              10       1025
129        1186      5035       Messi         MI      India   20    Male  Unknown Coach   Football  25-06-2020       5357   2338              740342    101        8      5        0         30278        10057  Bangalore        Sunny       Draw       5               4   84789         Cash                13602             114              28       4269
134        1038      5056    Joe Root        CSK      India   15   Other   Rahul Dravid   Football  17-09-2021        537   2874              740342    106        0      4        1         30278        10057  Bangalore  Unspecified       Draw       1               1   81145  Credit Card                 9722              60               1       1867
137        1184      5137       Smith        CSK  Sri Lanka   19    Male   Rahul Dravid   Football  20-01-2021       3692   2338              740342    185        8      4        0         30278        10057  Bangalore        Sunny       Lose       6               4   83224         Cash                 9722              14               6        160
139        1158      5079      Bumrah     Lakers  Australia   52    Male  Unknown Coach   Football  28-01-2021       2399   2338              740343     56        6      8        0         30278        10057    Chennai        Rainy       Draw       1               4   84938         Cash                 -964              88              13       1507
142        1089      5114      Hardik        RCB      India   47    Male  Unknown Coach   Football  28-12-2023       5714   2338              740342    198        5      5        2         22201        10057  Bangalore        Sunny       Lose       1               4   81836   Netbanking                 2725              10              22       1868
143        1059      5022       Rohit     Lakers      India   36   Other  Unknown Coach   Football  21-03-2021       5909   2437              622188    126        3      7        0         30278         1888     Mumbai        Rainy       Lose       8               4   81382   Netbanking                 8201              22              22       3827
148        1008      5194       Dhoni        RCB      India   40    Male   Rahul Dravid   Football  11-03-2022       1907   2338              740342     76        7      5        3         30278        10057    Kolkata        Rainy        Win       4               3   84491  Credit Card                 9722              87               3       3332
150        1146      5128     Ronaldo     Lakers    England   38  Female  Unknown Coach   Football  10-11-2020       1907   1995              740343     83        6      7        5         26052        10057    Chennai        Rainy        Win       1               4   81780   Netbanking                 9722              60               6       3177
159        1081      5164   Anonymous     Lakers  Sri Lanka   32    Male  Unknown Coach   Football  02-10-2022       3755   2338              473995    153        8      4        1         18870        18299    Chennai        Rainy        Win      10               5   84602          UPI                 9722              60              22       3810
160        1193      5062       Dhoni        KKR  Australia   17  Female   Rahul Dravid   Football  14-01-2023       1929    959              740342    182        3      7        4         30278         6953     Mumbai        Rainy       Lose       1               4   83204          UPI                 9722              60               7        583
179        1007      5175    Joe Root  Barcelona  Australia   15    Male  Unknown Coach   Football  11-06-2020       1907   2338              740342     76        6      8        5         30278        16910  Bangalore        Rainy        Win       6               4   84288   Netbanking                 9722              31              19       1886
186        1016      5112       Virat         MI      India   14    Male  Unknown Coach   Football  20-04-2022       1907   2338              576482    144        0      2        4         26726        10057    Gujarat        Rainy        Win       1               4   83418  Credit Card                 9722              60              24       3164
187        1171      5034       Virat     Lakers      India   51  Female  Unknown Coach   Football  05-12-2023       4217   2853              747497     39        1      4        3         30278        10057  Bangalore       Cloudy       Draw       9               4   83830   Netbanking                 1517              60              22       2671
188        1116      5181      Hardik  Barcelona      India   32  Female     John Smith   Football  05-12-2023       1907   2338              740343     56        0      8        4         30278        10057  Bangalore        Sunny       Draw       2               4   82224   Netbanking                 9722             112               0        193
190        1023      5165    Joe Root         MI      India   32  Female  Unknown Coach   Football  10-03-2022        490   2338              261441    120        3      7        4         30278        10057      Delhi        Rainy       Lose       7               4   84311  Credit Card                 3535              60              20       1300
191        1092      5158       Messi         MI    England   57   Other  Unknown Coach   Football  22-01-2022       1907   2338              740343     73        0      2        0         18577         8437      Delhi        Rainy        Win       1               2   84808   Netbanking                 6828              13               2       3200
193        1187      5159      Bumrah     Lakers  Sri Lanka   56  Female  Unknown Coach   Football  08-01-2022       5033   2338              740342     42        9      9        4         30278         1184    Chennai        Rainy        Win       3               3   84216   Netbanking                 9722              60              22       1380
194        1115      5182   Anonymous        KKR  Australia   48  Female  Unknown Coach   Football  05-12-2023       1907   2619              740343    118        3      3        3         30278         5798    Gujarat       Cloudy       Lose       7               4   80406   Netbanking                 9722              56              12       3537
195        1190      5185      Hardik        KKR  Sri Lanka   10    Male  Unknown Coach   Football  20-11-2023       4362    352              924942     22        9      9        5         49575         5841  Bangalore        Sunny        Win       5               4   84340         Cash                 1863              23               9       3159
203        1023      5126      Hardik         MI      India   32   Other     John Smith   Football  25-12-2021       1907   1320              244285    124        5      3        2         30278         2577     Mumbai  Unspecified       Draw       1               4   82603         Cash                 9722              55              29        604
205        1031      5170      Bumrah        KKR  Sri Lanka   51    Male   Rahul Dravid   Football  05-12-2023       5387    513              740342     89        4      6        0         30278        10057      Delhi        Rainy        Win       1               4   81039          UPI                15187              61              15       2602

Fetching matches with Bonus + Match_Fee > 6000.

In [ ]:
df[df['Bonus'] + df['Match_Fee'] > 6000]

,Player_Id,Match_Id,Player_Name,Team,Country,Age,Gender,Coach_Name,Sport_Type,Match_Date,...,Weather,Win_Status,Rating,Feedback_Score,Fan_Id,Payment_Mode,Fan_Purchase_Amount,Minutes_Played,Matches_Played,Fan_Count
22,1107,5168,Virat,MI,Sri Lanka,20,Male,Unknown Coach,Basketball,05-07-2022,...,Rainy,Win,3,1,80724,Cash,13804,60,6,111
42,1145,5027,Virat,CSK,India,27,Female,John Smith,Tennis,10-04-2023,...,Sunny,Lose,1,4,80066,Credit Card,9722,32,24,3376
51,1040,5194,Messi,Lakers,Sri Lanka,20,Male,Unknown Coach,other,09-06-2022,...,Rainy,Win,9,4,81056,UPI,9722,60,12,2071
55,1088,5156,Anonymous,Barcelona,Australia,60,Male,Unknown Coach,Football,17-12-2022,...,Rainy,Draw,9,4,81884,Credit Card,19837,60,11,1534
56,1070,5177,Messi,KKR,England,60,Male,Unknown Coach,Basketball,22-05-2023,...,Cloudy,Draw,1,3,82264,Credit Card,2743,60,26,180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2480,1037,5056,Hardik,KKR,Australia,13,Other,Unknown Coach,Basketball,05-12-2023,...,Rainy,Lose,9,4,84335,Cash,-755,2,22,4123
2481,1126,5045,Smith,Lakers,India,14,Male,Unknown Coach,Basketball,05-12-2023,...,Rainy,Win,7,4,82051,Netbanking,9722,97,0,685
2494,1081,5076,Hardik,RCB,India,28,Male,Unknown Coach,Basketball,25-12-2023,...,Sunny,Draw,7,4,82078,Cash,163,60,6,2564
2499,1122,5134,Bumrah,MI,England,12,Male,Unknown Coach,Football,05-12-2023,...,Sunny,Lose,1,1,83689,UPI,19995,60,26,1779
2507,1185,5089,Dhoni,KKR,Australia,37,Female,Unknown Coach,Football,06-02-2020,...,Rainy,Win,2,4,83481,Cash,4211,17,15,3549

Fetching players with average Rating < 4.

In [ ]:
df.groupby('Player_Name')['Rating'].mean().loc[lambda x: x < 4]

Player_Name
Anonymous    2.871094
Bumrah       3.062044
Dhoni        3.465021
Hardik       3.106719
Joe Root     3.054264
Messi        3.291139
Rohit        3.387500
Ronaldo      3.270588
Smith        3.449799
Virat        3.219608
Name: Rating, dtype: float64

Fetching matches played in Rainy weather

In [ ]:
print(df[df['Weather'] == 'Rainy'].to_string())

      Player_Id  Match_Id Player_Name       Team    Country  Age  Gender     Coach_Name  Sport_Type  Match_Date  Match_Fee  Bonus  Sponsorship_Amount  Score  Assists  Goals  Wickets  Ticket_Sales  Merch_Sales      Venue Weather Win_Status  Rating  Feedback_Score  Fan_Id Payment_Mode  Fan_Purchase_Amount  Minutes_Played  Matches_Played  Fan_Count
2          1014      5068      Bumrah        KKR      India   60    Male  Unknown Coach  Basketball  22-01-2024       1907     67              740343     76        9      8        0         30278        14535  Bangalore   Rainy       Draw       1               4   81929  Credit Card                 9722              12               2        278
7          1121      5055      Hardik        RCB      India   30  Female  Unknown Coach    Football  08-02-2024        761   2338              740342     53        7      5        3          3528        10057  Bangalore   Rainy       Lose       6               4   80587  Credit Card                 5898              60              18       2345
9          1116      5020     Ronaldo     Lakers  Australia   38  Female  Unknown Coach    Football  03-12-2023        909   2338              740342    155        9      1        0         30456        10057  Bangalore   Rainy       Lose       1               4   83851         Cash                 9722              91               7       1009
11         1001      5054   Anonymous     Lakers  Sri Lanka   53    Male  Unknown Coach      Tennis  03-03-2023       1907   1890              996837    165        1      1        1         30278        10057      Delhi   Rainy        Win       1               4   84398         Cash                 9722              15              28       3518
12         1087      5045       Rohit         MI      India   56  Female     John Smith    Football  07-07-2023       1907   2338              597941     66        0      7        1         30278        10057  Bangalore   Rainy       Lose       5               1   84044  Credit Card                12815              65               5       3787
14         1129      5095    Joe Root        CSK      India   14  Female   Rahul Dravid  Basketball  21-08-2022       1907    122              740343    166        0      9        0         30278         8106  Bangalore   Rainy        Win       8               4   82023   Netbanking                 2254              60              16       3592
15         1020      5109    Joe Root        CSK  Sri Lanka   13  Female  Unknown Coach      Tennis  14-11-2021       2632   2338              740342     85        9      9        3         30278         7054    Gujarat   Rainy        Win       1               4   84603         Cash                 9722              60               1       2935
17         1169      5112       Messi  Barcelona  Australia   44  Female  Unknown Coach    Football  05-12-2023       1427   2338              369706     41        5      9        4         38521         8764     Mumbai   Rainy        Win       1               3   82789   Netbanking                19875               6               8       1827
19         1014      5136       Smith        KKR      India   42    Male  Unknown Coach    Football  21-03-2020       1907   2267              474567    125        8      2        5         30278        13454  Bangalore   Rainy        Win       1               1   80538         Cash                 9722             118              24       2580
20         1189      5005    Joe Root        KKR      India   41  Female  Unknown Coach  Basketball  20-01-2022       1907    189              740342    154        4      2        4         30278        10057     Mumbai   Rainy        Win       8               1   84784  Credit Card                 7650              38              23       4597
21         1189      5038       Virat  Barcelona  Sri Lanka   42  Female  Unknown Coach    Football  17-05-2022       1907   2338              786510    105        5      8        4          1440        14806  Bangalore   Rainy       Draw       1               1   80305   Netbanking                 9722              60              26       4806
22         1107      5168       Virat         MI  Sri Lanka   20    Male  Unknown Coach  Basketball  05-07-2022       3412   2620              262307    112        5      4        4         32080         9882    Gujarat   Rainy        Win       3               1   80724         Cash                13804              60               6        111
23         1063      5004       Messi        CSK      India   28  Female  Unknown Coach  Basketball  10-01-2020       4086   1343              740343    122        5      4        0         10987        12869      Delhi   Rainy        Win       7               4   82435         Cash                11031              60              10       2302
27         1017      5126     Ronaldo         MI    England   48    Male   Rahul Dravid      Tennis  22-11-2021        178   2338              220096    135        1      9        1          4958        10057  Bangalore   Rainy       Draw       1               4   84542          UPI                15724              96               4        120
28         1131      5028       Virat     Lakers      India   35    Male  Unknown Coach     Cricket  22-11-2021       1907   1687              740343    165        0      8        5         30278        10057      Delhi   Rainy       Draw       1               4   84861          UPI                 1251              60              27       3101
29         1059      5086      Bumrah     Lakers  Australia   35  Female  Unknown Coach  Basketball  02-03-2023       3030   1080              740343    180        6      1        1         30278        10057     Mumbai   Rainy        Win       8               4   80095         Cash                12429              73              28       1427
30         1013      5140       Messi  Barcelona      India   32    Male   Rahul Dravid    Football  04-03-2021       1907   2777              740342     92        9      1        3         28501        10696      Delhi   Rainy       Lose       9               2   81283         Cash                 9722               1              23       3102
31         1089      5045       Messi  Barcelona      India   39  Female  Unknown Coach    Football  25-04-2023       2535   2338              740342     99        9      0        0         30278        17623    Kolkata   Rainy        Win       8               4   80981   Netbanking                 9722              88              21       1455
32         1129      5111    Joe Root         MI  Australia   39    Male   Rahul Dravid    Football  25-04-2023       3026   2338              740343    158        8      9        1         32600        13146  Bangalore   Rainy        Win       1               4   81565   Netbanking                 9722               7              22       1346
33         1091      5044       Rohit        KKR      India   28    Male  Unknown Coach     Cricket  27-05-2021       3066   2338              250729    187        6      4        4         30278        15677     Mumbai   Rainy       Draw       1               4   80735         Cash                14758              60              25       1214
39         1131      5125       Smith        RCB      India   52    Male  Unknown Coach  Basketball  05-12-2023       1132   2338              683275    145        6      8        0         37459        14224  Bangalore   Rainy       Draw       1               5   80671  Credit Card                13833              88               6       4902
46         1189      5155      Bumrah        CSK      India   28    Male  Unknown Coach  Basketball  22-08-2023       1907   2338              740342    137        2      7        0         30278        12492     Mumbai   Rainy       Lose       1               4   84554          UPI                 9722              60              29       2263
47         1081      5071      Hardik         MI      India   11    Male  Unknown Coach       other  08-11-2021         16   2954              740343    120        4      5        2         28982          855    Chennai   Rainy        Win       4               3   81169  Credit Card                 9722              60               5        915
48         1110      5106    Joe Root        KKR    England   42  Female  Unknown Coach       other  12-06-2021       1907   2338              740342     75        2      9        4         42916          209    Kolkata   Rainy       Draw       6               4   84101   Netbanking                 9722              63              21       1801
49         1023      5174       Messi        KKR      India   11   Other   Rahul Dravid      Tennis  12-06-2021       2396   2338              597878     69        2      6        1         20896         5586      Delhi   Rainy        Win       4               3   83179   Netbanking                 9722              48               6         81
50         1187      5189    Joe Root        KKR    England   27    Male     John Smith  Basketball  18-11-2023       1907   2338              740342    132        0      6        1         29759        10057     Mumbai   Rainy        Win       1               3   81363  Credit Card                 9722              60              24        165
51         1040      5194       Messi     Lakers  Sri Lanka   20    Male  Unknown Coach       other  09-06-2022       4629   2338              740342    136        7      2        1         47973        16805     Mumbai   Rainy        Win       9               4   81056          UPI                 9722              60              12       2071
53         1044      5174       Virat         MI    England   42  Female  Unknown Coach    Football  25-05-2021       1907   2032               96295    181        1      3        2         30278        10057    Gujarat   Rainy       Draw       3               4   84831  Credit Card                18399              69               8        331
54         1064      5192    Joe Root         MI      India   11  Female     John Smith  Basketball  05-12-2023       2005    190              740342     45        1      7        1         30278        10057    Kolkata   Rainy        Win       1               3   82773          UPI                 9722              60              14       3590
55         1088      5156   Anonymous  Barcelona  Australia   60    Male  Unknown Coach    Football  17-12-2022       5287   2338              740342     21        6      1        4         36935        10057  Bangalore   Rainy       Draw       9               4   81884  Credit Card                19837              60              11       1534
57         1135      5161     Ronaldo        CSK    England   55    Male     John Smith    Football  15-12-2023       1907   2338              740342    178        5      0        0         30278        12520     Mumbai   Rainy       Draw       6               4   81890  Credit Card                 9722              15               4       2486
58         1062      5092       Dhoni     Lakers  Australia   40  Female  Unknown Coach       other  07-05-2020       1907   2338              907655     77        9      3        0         30278         4723    Kolkata   Rainy        Win       1               3   83125   Netbanking                 9722              59               6       2590
59         1138      5175       Dhoni  Barcelona  Australia   41   Other   Rahul Dravid  Basketball  27-02-2020       1907   2014              740342     38        2      1        1         30278        10057    Gujarat   Rainy        Win       1               4   80941         Cash                16349              53              27       2240
60         1135      5176      Bumrah  Barcelona  Australia   19    Male  Unknown Coach  Basketball  20-04-2021       3702   2338              740342    177        1      8        5         30278          125  Bangalore   Rainy       Draw       1               1   81968         Cash                16083              60              10        611
61         1162      5060    Joe Root  Barcelona  Sri Lanka   31  Female  Unknown Coach    Football  05-09-2021       4016   1747              740342     74        7      5        3         30278          231    Chennai   Rainy       Lose       9               4   84150         Cash                 9722              60              12       3194
62         1032      5156      Hardik        KKR      India   51  Female  Unknown Coach    Football  12-05-2023        690   1154              740342    117        7      2        3         11761        18699    Kolkata   Rainy       Draw       1               4   81471          UPI                 5321               5              27       1397
63         1122      5038      Hardik  Barcelona      India   52  Female   Rahul Dravid       other  26-12-2020       1907   2338              740343    103        0      6        3         49301         5226    Gujarat   Rainy        Win       1               4   81058  Credit Card                 9722              47               3       1456
66         1071      5070     Ronaldo         MI      India   37   Other  Unknown Coach    Football  03-08-2020       1907   2338              740343    171        5      5        3         30278        19171    Kolkata   Rainy        Win       7               1   84866  Credit Card                 9722             114              21       2200
68         1061      5006       Virat  Barcelona  Australia   28    Male  Unknown Coach     Cricket  29-06-2023       1907   2338              740343     22        0      0        3         30278         9196    Kolkata   Rainy       Lose       9               4   84517          UPI                12059              60              20       2136
69         1098      5048       Virat        KKR  Australia   53    Male  Unknown Coach    Football  29-10-2021       1907   1444              740342     55        4      7        2         31902          236     Mumbai   Rainy        Win       7               4   83757          UPI                 9722              60              26        377
70         1103      5052   Anonymous        RCB      India   39    Male  Unknown Coach  Basketball  29-10-2021       1907   1368              740342    117        6      5        3         30278        16054  Bangalore   Rainy       Lose       1               4   83210         Cash                 5528              60              15       4844
72         1174      5170   Anonymous  Barcelona  Sri Lanka   47    Male  Unknown Coach  Basketball  11-04-2023       1907   2338               92163    161        4      4        1         24314         5377      Delhi   Rainy       Lose       2               4   82091   Netbanking                 9722             100              24       1146
75         1062      5119      Hardik  Barcelona      India   23    Male  Unknown Coach       other  11-09-2022       1907    621              740342    107        3      4        3         30569          647  Bangalore   Rainy       Draw       4               4   83417  Credit Card                 9722              60               9       2548
77         1051      5064      Bumrah        CSK      India   60  Female   Rahul Dravid    Football  23-11-2021       1907   2338              740343     61        8      5        0         30278        10057    Chennai   Rainy        Win       9               4   83659  Credit Card                 9722              60               0       4608
78         1150      5079      Bumrah  Barcelona      India   29  Female     John Smith      Tennis  23-11-2021       1907   2338              990326    190        0      0        0         30278        12597  Bangalore   Rainy       Draw       4               4   84552   Netbanking                 9722              60              20       4762
80         1170      5107       Smith        RCB      India   32  Female     John Smith  Basketball  04-07-2021       1907   1486              740342    137        0      3        3         30278         5965     Mumbai   Rainy       Lose       8               4   84588          UPI                 9722              60              25       1448
81         1028      5178       Dhoni     Lakers      India   60    Male  Unknown Coach    Football  04-07-2021       1151   1076              740342     10        5      5        4          1411         7571    Chennai   Rainy       Lose       8               4   82157   Netbanking                 9722              60              22        966
83         1085      5193       Virat        RCB      India   10    Male  Unknown Coach     Cricket  16-07-2022       1907   2338              740342     33        5      7        3          4353         4363     Mumbai   Rainy       Lose       8               4   80809   Netbanking                 2582              24              21        509
84         1065      5172      Bumrah        RCB    England   17    Male  Unknown Coach    Football  26-11-2021       1504    782              740343    144        3      7        3         30278        10057    Chennai   Rainy       Draw       1               4   83268   Netbanking                 9722              20              18       3865
85         1169      5014      Hardik         MI  Australia   46    Male   Rahul Dravid  Basketball  20-08-2022       1907   1896              740342    103        7      7        4         30278         9342  Bangalore   Rainy       Lose       1               3   84868  Credit Card                 9722              82              19        303
86         1044      5130      Hardik         MI  Sri Lanka   23  Female  Unknown Coach  Basketball  04-08-2022       3971    685              740342    181        1      5        5         20180         9526    Kolkata   Rainy       Lose       1               4   82984          UPI                 9722              63              23        968
87         1061      5138   Anonymous     Lakers      India   47   Other   Rahul Dravid      Tennis  16-09-2020       1788   1011              740342     39        6      8        3          6589        13934  Bangalore   Rainy        Win       1               4   80572          UPI                 9722              60              27       1438
89         1107      5145      Hardik  Barcelona      India   35  Female  Unknown Coach     Cricket  20-04-2022       1907   1244              740342     63        3      3        0         34154        10057  Bangalore   Rainy       Lose       1               4   82460         Cash                 9722              60              13       4354
92         1189      5184       Messi        CSK      India   21    Male  Unknown Coach      Tennis  21-04-2021       1907   2953              740342    175        0      1        0         40472        12980    Chennai   Rainy       Lose       6               4   81833  Credit Card                16107              33               8        977
94         1189      5115    Joe Root         MI      India   55    Male  Unknown Coach     Cricket  12-04-2021       1907   2338              337452    112        2      7        4         30278        16954  Bangalore   Rainy       Draw       1               4   83052  Credit Card                13322              18              12       4149
95         1115      5048       Virat         MI      India   25    Male  Unknown Coach  Basketball  29-11-2020       5256   2338              515844    137        1      9        2         33050        10057     Mumbai   Rainy        Win       1               4   81508         Cash                 9722              60              15       3474

In [ ]:

df['Total_Earning'] = (df['Match_Fee'] + df['Bonus'] + df['Sponsorship_Amount'])

Add Total_Earning = Match_Fee + Bonus + Sponsorship_Amount.

In [ ]:
df['Performance_Score'] = (df['Score'] + (df['Assists'] * 2) + (df['Goals'] * 3) + (df['Wickets'] * 4))

Add Performance_Score = Score + (Assists2) + (Goals3) + (Wickets*4).

In [ ]:
df['Revenue'] = (df['Ticket_Sales'] + df['Merch_Sales'])

Add Revenue = Ticket_Sales + Merch_Sales

In [ ]:
df['Gender_Numeric'] = df['Gender'].replace({'Male': 1,'Female': 2,'Other': 3})

/tmp/ipython-input-2397959886.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender_Numeric'] = df['Gender'].replace({'Male': 1,'Female': 2,'Other': 3})

Encode Gender numerically (Male=1,Female=2,Other=3).

In [ ]:
df['Win_Status Numerical'] = df['Win_Status'].replace({'Win': 1,'Draw': 0.5,'Lose': 0})

/tmp/ipython-input-3773348818.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Win_Status Numerical'] = df['Win_Status'].replace({'Win': 1,'Draw': 0.5,'Lose': 0})

Encode Win_Status numerically (Win=1,Draw=0.5,Lose=0).

In [ ]:
print(df.to_string())

      Player_Id  Match_Id Player_Name       Team    Country  Age  Gender     Coach_Name  Sport_Type  Match_Date  Match_Fee  Bonus  Sponsorship_Amount  Score  Assists  Goals  Wickets  Ticket_Sales  Merch_Sales      Venue      Weather Win_Status  Rating  Feedback_Score  Fan_Id Payment_Mode  Fan_Purchase_Amount  Minutes_Played  Matches_Played  Fan_Count  Total_Earning  Performance_Score  Revenue  Gender_Numeric  Win_Status Numerical
0          1102      5082       Virat        CSK      India   17    Male   Rahul Dravid    Football  13-02-2023       1907   2338              287941     13        0      1        5         37356        10057    Chennai  Unspecified        Win       5               4   81006         Cash                 8970               1               3       2337         292186                 36    47413               1                   1.0
1          1179      5034       Virat        KKR      India   23    Male  Unknown Coach      Tennis  05-12-2022       1907   2338              740342     90        9      7        0         18655         7745  Bangalore  Unspecified       Draw      10               4   80048   Netbanking                 9722              60              11        805         744587                129    26400               1                   0.5
2          1014      5068      Bumrah        KKR      India   60    Male  Unknown Coach  Basketball  22-01-2024       1907     67              740343     76        9      8        0         30278        14535  Bangalore        Rainy       Draw       1               4   81929  Credit Card                 9722              12               2        278         742317                118    44813               1                   0.5
3          1071      5195    Joe Root     Lakers  Australia   20   Other  Unknown Coach    Football  12-05-2023        387   2338              740343    108        1      3        3         30278        10057     Mumbai        Sunny       Lose       1               4   81525   Netbanking                 9393              33              28        787         743068                131    40335               3                   0.0
4          1188      5139       Smith        KKR  Sri Lanka   58   Other  Unknown Coach    Football  23-01-2024       1907   2338              740343     30        4      1        1         30278        10057  Bangalore  Unspecified       Draw       2               4   80328         Cash                 9722              62              11       1332         744588                 45    40335               3                   0.5
5          1020      5187       Virat        CSK  Australia   33    Male  Unknown Coach  Basketball  07-08-2021       1907   2338              740342    121        9      1        3          8839         3104    Chennai       Cloudy        Win       7               1   82657  Credit Card                 9722              66              23       4372         744587                154    11943               1                   1.0
6          1102      5026      Hardik     Lakers  Sri Lanka   10    Male   Rahul Dravid     Cricket  19-05-2022       1907   2925              730707    106        3      1        5         30417        10057    Kolkata        Sunny       Lose       1               3   84529          UPI                17522             107              23       3147         735539                135    40474               1                   0.0
7          1121      5055      Hardik        RCB      India   30  Female  Unknown Coach    Football  08-02-2024        761   2338              740342     53        7      5        3          3528        10057  Bangalore        Rainy       Lose       6               4   80587  Credit Card                 5898              60              18       2345         743441                 94    13585               2                   0.0
8          1074      5022       Virat        KKR      India   11    Male     John Smith      Tennis  03-12-2023       1907   2338              835031    132        0      6        2         27302        13721  Bangalore       Cloudy        Win       1               3   83205   Netbanking                  240              59              12       3449         839276                158    41023               1                   1.0
9          1116      5020     Ronaldo     Lakers  Australia   38  Female  Unknown Coach    Football  03-12-2023        909   2338              740342    155        9      1        0         30456        10057  Bangalore        Rainy       Lose       1               4   83851         Cash                 9722              91               7       1009         743589                176    40513               2                   0.0
10         1052      5152      Hardik     Lakers    England   50  Female     John Smith    Football  05-12-2023       1907   1846              740342     70        0      8        0         39669        18222  Bangalore       Cloudy        Win       1               4   84659   Netbanking                 7545              60               9        935         744095                 94    57891               2                   1.0
11         1001      5054   Anonymous     Lakers  Sri Lanka   53    Male  Unknown Coach      Tennis  03-03-2023       1907   1890              996837    165        1      1        1         30278        10057      Delhi        Rainy        Win       1               4   84398         Cash                 9722              15              28       3518        1000634                174    40335               1                   1.0
12         1087      5045       Rohit         MI      India   56  Female     John Smith    Football  07-07-2023       1907   2338              597941     66        0      7        1         30278        10057  Bangalore        Rainy       Lose       5               1   84044  Credit Card                12815              65               5       3787         602186                 91    40335               2                   0.0
13         1037      5054    Joe Root        CSK    England   45    Male     John Smith       other  05-12-2023       1907   2338              811576    108        1      8        5         14156        10543  Bangalore        Sunny        Win       8               3   82604         Cash                10842             112              17        495         815821                154    24699               1                   1.0
14         1129      5095    Joe Root        CSK      India   14  Female   Rahul Dravid  Basketball  21-08-2022       1907    122              740343    166        0      9        0         30278         8106  Bangalore        Rainy        Win       8               4   82023   Netbanking                 2254              60              16       3592         742372                193    38384               2                   1.0
15         1020      5109    Joe Root        CSK  Sri Lanka   13  Female  Unknown Coach      Tennis  14-11-2021       2632   2338              740342     85        9      9        3         30278         7054    Gujarat        Rainy        Win       1               4   84603         Cash                 9722              60               1       2935         745312                142    37332               2                   1.0
16         1048      5079       Smith  Barcelona  Australia   41    Male  Unknown Coach    Football  12-06-2021       1620   2338              740342     32        9      3        4         28270        10057  Bangalore       Cloudy        Win      10               4   81790  Credit Card                15884               0              15        905         744300                 75    38327               1                   1.0
17         1169      5112       Messi  Barcelona  Australia   44  Female  Unknown Coach    Football  05-12-2023       1427   2338              369706     41        5      9        4         38521         8764     Mumbai        Rainy        Win       1               3   82789   Netbanking                19875               6               8       1827         373471                 94    47285               2                   1.0
18         1187      5060      Bumrah        CSK      India   52    Male  Unknown Coach       other  05-12-2023       1907   2338              446653    111        2      3        3         30278         2084    Chennai       Cloudy        Win       1               4   82184          UPI                 8796              19              24       3722         450898                136    32362               1                   1.0
19         1014      5136       Smith        KKR      India   42    Male  Unknown Coach    Football  21-03-2020       1907   2267              474567    125        8      2        5         30278        13454  Bangalore        Rainy        Win       1               1   80538         Cash                 9722             118              24       2580         478741                167    43732               1                   1.0
20         1189      5005    Joe Root        KKR      India   41  Female  Unknown Coach  Basketball  20-01-2022       1907    189              740342    154        4      2        4         30278        10057     Mumbai        Rainy        Win       8               1   84784  Credit Card                 7650              38              23       4597         742438                184    40335               2                   1.0
21         1189      5038       Virat  Barcelona  Sri Lanka   42  Female  Unknown Coach    Football  17-05-2022       1907   2338              786510    105        5      8        4          1440        14806  Bangalore        Rainy       Draw       1               1   80305   Netbanking                 9722              60              26       4806         790755                155    16246               2                   0.5
22         1107      5168       Virat         MI  Sri Lanka   20    Male  Unknown Coach  Basketball  05-07-2022       3412   2620              262307    112        5      4        4         32080         9882    Gujarat        Rainy        Win       3               1   80724         Cash                13804              60               6        111         268339                150    41962               1                   1.0
23         1063      5004       Messi        CSK      India   28  Female  Unknown Coach  Basketball  10-01-2020       4086   1343              740343    122        5      4        0         10987        12869      Delhi        Rainy        Win       7               4   82435         Cash                11031              60              10       2302         745772                144    23856               2                   1.0
24         1130      5169   Anonymous        CSK      India   16    Male  Unknown Coach      Tennis  13-10-2022       1907   2090              740342    113        7      0        0         30278        10057    Gujarat       Cloudy        Win       1               4   82340  Credit Card                12543              60               0       1650         744339                127    40335               1                   1.0
25         1134      5075       Rohit         MI  Sri Lanka   56  Female  Unknown Coach     Cricket  13-01-2022       2472   2731              740342     15        9      4        5         30278        10057    Chennai       Cloudy        Win       9               4   81903          UPI                 9722              26              20       2474         745545                 65    40335               2                   1.0
26         1072      5157      Hardik         MI  Sri Lanka   26    Male  Unknown Coach    Football  05-12-2023        450   2338              740342     18        7      6        5         16432        10057    Gujarat        Sunny       Lose       1               4   83383         Cash                 5504              60              18       1890         743130                 70    26489               1                   0.0
27         1017      5126     Ronaldo         MI    England   48    Male   Rahul Dravid      Tennis  22-11-2021        178   2338              220096    135        1      9        1          4958        10057  Bangalore        Rainy       Draw       1               4   84542          UPI                15724              96               4        120         222612                168    15015               1                   0.5
28         1131      5028       Virat     Lakers      India   35    Male  Unknown Coach     Cricket  22-11-2021       1907   1687              740343    165        0      8        5         30278        10057      Delhi        Rainy       Draw       1               4   84861          UPI                 1251              60              27       3101         743937                209    40335               1                   0.5
29         1059      5086      Bumrah     Lakers  Australia   35  Female  Unknown Coach  Basketball  02-03-2023       3030   1080              740343    180        6      1        1         30278        10057     Mumbai        Rainy        Win       8               4   80095         Cash                12429              73              28       1427         744453                199    40335               2                   1.0
30         1013      5140       Messi  Barcelona      India   32    Male   Rahul Dravid    Football  04-03-2021       1907   2777              740342     92        9      1        3         28501        10696      Delhi        Rainy       Lose       9               2   81283         Cash                 9722               1              23       3102         745026                125    39197               1                   0.0
31         1089      5045       Messi  Barcelona      India   39  Female  Unknown Coach    Football  25-04-2023       2535   2338              740342     99        9      0        0         30278        17623    Kolkata        Rainy        Win       8               4   80981   Netbanking                 9722              88              21       1455         745215                117    47901               2                   1.0
32         1129      5111    Joe Root         MI  Australia   39    Male   Rahul Dravid    Football  25-04-2023       3026   2338              740343    158        8      9        1         32600        13146  Bangalore        Rainy        Win       1               4   81565   Netbanking                 9722               7              22       1346         745707                205    45746               1                   1.0
33         1091      5044       Rohit        KKR      India   28    Male  Unknown Coach     Cricket  27-05-2021       3066   2338              250729    187        6      4        4         30278        15677     Mumbai        Rainy       Draw       1               4   80735         Cash                14758              60              25       1214         256133                227    45955               1                   0.5
34         1198      5084      Bumrah  Barcelona  Sri Lanka   47  Female  Unknown Coach       other  05-12-2020       1907   1768              713588     78        1      2        3         23059         1988      Delhi       Cloudy       Draw       6               4   80448  Credit Card                 8922              60               9       4612         717263                 98    25047               2                   0.5
35         1034      5017     Ronaldo        RCB  Australia   58    Male     John Smith    Football  20-11-2023       1907   2365              740342    175        1      4        0         22991        10057     Mumbai        Sunny        Win       6               1   81433  Credit Card                13058             120               7       2858         744614                189    33048               1                   1.0
36         1080      5093      Bumrah        RCB  Australia   57  Female  Unknown Coach      Tennis  22-03-2020       1907   1730              740342    139        3      0        0         30278         2525     Mumbai  Unspecified        Win       1               5   80876          UPI                 9722              68              21        761         743979                145    32803               2                   1.0
37         1163      5149       Dhoni     Lakers  Australia   26    Male  Unknown Coach     Cricket  12-05-2023       1907   2338              369408     95        2      1        0         30278         2000  Bangalore        Sunny        Win       9               4   82575         Cash                12407              60              26       2366         373653                102    32278               1                   1.0
38         1049      5032       Smith        RCB  Sri Lanka   57  Female  Unknown Coach       other  09-12-2021       1907   2338              555903     88        3      0        5         30278        10057    Kolkata       Cloudy       Draw       1               4   81133         Cash                 9722              60              12       4206         560148                114    40335               2                   0.5
39         1131      5125       Smith        RCB      India   52    Male  Unknown Coach  Basketball  05-12-2023       1132   2338              683275    145        6      8        0         37459        14224  Bangalore        Rainy       Draw       1               5   80671  Credit Card                13833              88               6       4902         686745                181    51683               1                   0.5
40         1133      5169       Messi        KKR      India   41  Female  Unknown Coach  Basketball  18-09-2022       1907   2338              740342    121        7      4        2          2826        17165      Delhi       Cloudy        Win       6               4   83318         Cash                 6443              98               3       3919         744587                155    19991               2                   1.0
41         1190      5161       Virat        RCB      India   13  Female  Unknown Coach    Football  16-09-2021       1907   2036              534886     61        0      8        4          4787        10623  Bangalore  Unspecified        Win       1               4   81783          UPI                 9576              15              20       2043         538829                101    15410               2                   1.0
42         1145      5027       Virat        CSK      India   27  Female     John Smith      Tennis  10-04-2023       5231   2338              740342    196        1      4        5         38750        10825  Bangalore        Sunny       Lose       1               4   80066  Credit Card                 9722              32              24       3376         747911                230    49575               2                   0.0
43         1161      5166    Joe Root        CSK      India   45  Female  Unknown Coach  Basketball  31-05-2021       1907    923              740342    135        4      4        4         43841        10057     Mumbai  Unspecified       Lose       1               4   82090   Netbanking                 9722              60              21        834         743172                171    53898               2                   0.0
44         1094      5146    Joe Root        CSK      India   44    Male   Rahul Dravid  Basketball  07-04-2020       1907   2338              740343    125        8      6        3         30278        10057  Bangalore        Sunny        Win       1               4   80233         Cash                 9722              18              13       1564         744588                171    40335               1                   1.0

In [ ]:

df.sort_values(by='Total_Earning', ascending=False)[['Player_Name', 'Total_Earning']].head(5)

     Player_Name  Total_Earning
1439    Joe Root        1004889
1769      Bumrah        1001163
2048       Smith        1001128
11     Anonymous        1000634
1060   Anonymous        1000222

Top 5 players by total earnings.

In [ ]:
df.groupby('Team')['Wickets'].sum().sort_values(ascending=False).head(5)

Team
Barcelona    1097
RCB          1095
Lakers       1090
CSK          1051
KKR          1041
Name: Wickets, dtype: int64

Top 5 teams by Wickets scored.

In [ ]:
df.groupby('Team')['Goals'].sum().sort_values(ascending=False).head(5)

Team
Lakers       2008
RCB          1902
Barcelona    1896
CSK          1893
MI           1846
Name: Goals, dtype: int64

2.	Top 5 teams by goals scored.

In [ ]:
df.groupby('Sport_Type')['Feedback_Score'].mean()

Sport_Type
Basketball    3.664975
Cricket       3.631098
Football      3.601891
Tennis        3.577640
other         3.636086
Name: Feedback_Score, dtype: float64

Average feedback score per sport type.

In [ ]:
df.groupby('Team')['Bonus'].mean()

Team
Barcelona    1931.944573
CSK          1965.004762
KKR          1954.566416
Lakers       1933.198198
MI           2022.167866
RCB          1918.407862
Name: Bonus, dtype: float64

Average bonus per team.

In [ ]:
df.groupby('Payment_Mode')['Ticket_Sales'].count()

Payment_Mode
Cash           641
Credit Card    639
Netbanking     602
UPI            638
Name: Ticket_Sales, dtype: int64

Most common payment mode among fans.

In [ ]:
df.sort_values(by='Score', ascending=False)[['Player_Name', 'Score']].head(1)

     Player_Name  Score
1924     Ronaldo    199

Identify player with highest single match score.

In [ ]:
df.loc[df['Matches_Played'] > 15, ['Player_Name', 'Matches_Played']]

     Player_Name  Matches_Played
3       Joe Root              28
5          Virat              23
6         Hardik              23
7         Hardik              18
11     Anonymous              28
...          ...             ...
2508     Ronaldo              26
2510      Hardik              18
2512       Rohit              24
2515       Smith              24
2517       Smith              22

[1201 rows x 2 columns]

Find players with >15 matches.

In [ ]:
df.sort_values(by='Minutes_Played', ascending=False)[['Player_Name', 'Minutes_Played']]

     Player_Name  Minutes_Played
1837      Hardik             120
1584       Messi             120
1102       Virat             120
696      Ronaldo             120
448        Smith             120
...          ...             ...
2412      Hardik               0
1244       Dhoni               0
1317       Smith               0
2406       Dhoni               0
2452   Anonymous               0

[2520 rows x 2 columns]

Sort players by total minutes played.

In [ ]:
df.groupby('Venue')['Matches_Played'].sum()

Venue
Bangalore    14237
Chennai       4533
Delhi         4804
Gujarat       4325
Kolkata       4557
Mumbai        4608
Name: Matches_Played, dtype: int64

Identify most frequently played venue.

In [ ]:
df.groupby(['Country', 'Sport_Type'])['Ticket_Sales'].sum()

Country    Sport_Type
Australia  Basketball     2953342
           Cricket        1414248
           Football       4600214
           Tennis         1625126
           other          1537230
England    Basketball     2875161
           Cricket        1466634
           Football       5146570
           Tennis         1557550
           other          2289159
India      Basketball     7974773
           Cricket        4382291
           Football      12026212
           Tennis         3483305
           other          3932735
Sri Lanka  Basketball     2785479
           Cricket        1856331
           Football       4981491
           Tennis         2138184
           other          1579041
Name: Ticket_Sales, dtype: int64

Group by Country & Sport_Type → total ticket sales.

In [ ]:

p = df.groupby('Player_Name')['Country'].nunique()
p

Player_Name
Anonymous    4
Bumrah       4
Dhoni        4
Hardik       4
Joe Root     4
Messi        4
Rohit        4
Ronaldo      4
Smith        4
Virat        4
Name: Country, dtype: int64

Identify players appearing with different countries.

In [ ]:
df['Match_Date'] = pd.to_datetime(df['Match_Date'], dayfirst=True)

Detect inconsistent date formats in Match_Date and standardize to YYYY-MM-DD.

In [ ]:
print(df.to_string())

      Player_Id  Match_Id Player_Name       Team    Country  Age  Gender     Coach_Name  Sport_Type Match_Date  Match_Fee  Bonus  Sponsorship_Amount  Score  Assists  Goals  Wickets  Ticket_Sales  Merch_Sales      Venue      Weather Win_Status  Rating  Feedback_Score  Fan_Id Payment_Mode  Fan_Purchase_Amount  Minutes_Played  Matches_Played  Fan_Count  Total_Earning  Performance_Score  Revenue  Gender_Numeric  Win_Status Numerical
0          1102      5082       Virat        CSK      India   17    Male   Rahul Dravid    Football 2023-02-13       1907   2338              287941     13        0      1        5         37356        10057    Chennai  Unspecified        Win       5               4   81006         Cash                 8970               1               3       2337         292186                 36    47413               1                   1.0
1          1179      5034       Virat        KKR      India   23    Male  Unknown Coach      Tennis 2022-12-05       1907   2338              740342     90        9      7        0         18655         7745  Bangalore  Unspecified       Draw      10               4   80048   Netbanking                 9722              60              11        805         744587                129    26400               1                   0.5
2          1014      5068      Bumrah        KKR      India   60    Male  Unknown Coach  Basketball 2024-01-22       1907     67              740343     76        9      8        0         30278        14535  Bangalore        Rainy       Draw       1               4   81929  Credit Card                 9722              12               2        278         742317                118    44813               1                   0.5
3          1071      5195    Joe Root     Lakers  Australia   20   Other  Unknown Coach    Football 2023-05-12        387   2338              740343    108        1      3        3         30278        10057     Mumbai        Sunny       Lose       1               4   81525   Netbanking                 9393              33              28        787         743068                131    40335               3                   0.0
4          1188      5139       Smith        KKR  Sri Lanka   58   Other  Unknown Coach    Football 2024-01-23       1907   2338              740343     30        4      1        1         30278        10057  Bangalore  Unspecified       Draw       2               4   80328         Cash                 9722              62              11       1332         744588                 45    40335               3                   0.5
5          1020      5187       Virat        CSK  Australia   33    Male  Unknown Coach  Basketball 2021-08-07       1907   2338              740342    121        9      1        3          8839         3104    Chennai       Cloudy        Win       7               1   82657  Credit Card                 9722              66              23       4372         744587                154    11943               1                   1.0
6          1102      5026      Hardik     Lakers  Sri Lanka   10    Male   Rahul Dravid     Cricket 2022-05-19       1907   2925              730707    106        3      1        5         30417        10057    Kolkata        Sunny       Lose       1               3   84529          UPI                17522             107              23       3147         735539                135    40474               1                   0.0
7          1121      5055      Hardik        RCB      India   30  Female  Unknown Coach    Football 2024-02-08        761   2338              740342     53        7      5        3          3528        10057  Bangalore        Rainy       Lose       6               4   80587  Credit Card                 5898              60              18       2345         743441                 94    13585               2                   0.0
8          1074      5022       Virat        KKR      India   11    Male     John Smith      Tennis 2023-12-03       1907   2338              835031    132        0      6        2         27302        13721  Bangalore       Cloudy        Win       1               3   83205   Netbanking                  240              59              12       3449         839276                158    41023               1                   1.0
9          1116      5020     Ronaldo     Lakers  Australia   38  Female  Unknown Coach    Football 2023-12-03        909   2338              740342    155        9      1        0         30456        10057  Bangalore        Rainy       Lose       1               4   83851         Cash                 9722              91               7       1009         743589                176    40513               2                   0.0
10         1052      5152      Hardik     Lakers    England   50  Female     John Smith    Football 2023-12-05       1907   1846              740342     70        0      8        0         39669        18222  Bangalore       Cloudy        Win       1               4   84659   Netbanking                 7545              60               9        935         744095                 94    57891               2                   1.0
11         1001      5054   Anonymous     Lakers  Sri Lanka   53    Male  Unknown Coach      Tennis 2023-03-03       1907   1890              996837    165        1      1        1         30278        10057      Delhi        Rainy        Win       1               4   84398         Cash                 9722              15              28       3518        1000634                174    40335               1                   1.0
12         1087      5045       Rohit         MI      India   56  Female     John Smith    Football 2023-07-07       1907   2338              597941     66        0      7        1         30278        10057  Bangalore        Rainy       Lose       5               1   84044  Credit Card                12815              65               5       3787         602186                 91    40335               2                   0.0
13         1037      5054    Joe Root        CSK    England   45    Male     John Smith       other 2023-12-05       1907   2338              811576    108        1      8        5         14156        10543  Bangalore        Sunny        Win       8               3   82604         Cash                10842             112              17        495         815821                154    24699               1                   1.0
14         1129      5095    Joe Root        CSK      India   14  Female   Rahul Dravid  Basketball 2022-08-21       1907    122              740343    166        0      9        0         30278         8106  Bangalore        Rainy        Win       8               4   82023   Netbanking                 2254              60              16       3592         742372                193    38384               2                   1.0
15         1020      5109    Joe Root        CSK  Sri Lanka   13  Female  Unknown Coach      Tennis 2021-11-14       2632   2338              740342     85        9      9        3         30278         7054    Gujarat        Rainy        Win       1               4   84603         Cash                 9722              60               1       2935         745312                142    37332               2                   1.0
16         1048      5079       Smith  Barcelona  Australia   41    Male  Unknown Coach    Football 2021-06-12       1620   2338              740342     32        9      3        4         28270        10057  Bangalore       Cloudy        Win      10               4   81790  Credit Card                15884               0              15        905         744300                 75    38327               1                   1.0
17         1169      5112       Messi  Barcelona  Australia   44  Female  Unknown Coach    Football 2023-12-05       1427   2338              369706     41        5      9        4         38521         8764     Mumbai        Rainy        Win       1               3   82789   Netbanking                19875               6               8       1827         373471                 94    47285               2                   1.0
18         1187      5060      Bumrah        CSK      India   52    Male  Unknown Coach       other 2023-12-05       1907   2338              446653    111        2      3        3         30278         2084    Chennai       Cloudy        Win       1               4   82184          UPI                 8796              19              24       3722         450898                136    32362               1                   1.0
19         1014      5136       Smith        KKR      India   42    Male  Unknown Coach    Football 2020-03-21       1907   2267              474567    125        8      2        5         30278        13454  Bangalore        Rainy        Win       1               1   80538         Cash                 9722             118              24       2580         478741                167    43732               1                   1.0
20         1189      5005    Joe Root        KKR      India   41  Female  Unknown Coach  Basketball 2022-01-20       1907    189              740342    154        4      2        4         30278        10057     Mumbai        Rainy        Win       8               1   84784  Credit Card                 7650              38              23       4597         742438                184    40335               2                   1.0
21         1189      5038       Virat  Barcelona  Sri Lanka   42  Female  Unknown Coach    Football 2022-05-17       1907   2338              786510    105        5      8        4          1440        14806  Bangalore        Rainy       Draw       1               1   80305   Netbanking                 9722              60              26       4806         790755                155    16246               2                   0.5
22         1107      5168       Virat         MI  Sri Lanka   20    Male  Unknown Coach  Basketball 2022-07-05       3412   2620              262307    112        5      4        4         32080         9882    Gujarat        Rainy        Win       3               1   80724         Cash                13804              60               6        111         268339                150    41962               1                   1.0
23         1063      5004       Messi        CSK      India   28  Female  Unknown Coach  Basketball 2020-01-10       4086   1343              740343    122        5      4        0         10987        12869      Delhi        Rainy        Win       7               4   82435         Cash                11031              60              10       2302         745772                144    23856               2                   1.0
24         1130      5169   Anonymous        CSK      India   16    Male  Unknown Coach      Tennis 2022-10-13       1907   2090              740342    113        7      0        0         30278        10057    Gujarat       Cloudy        Win       1               4   82340  Credit Card                12543              60               0       1650         744339                127    40335               1                   1.0
25         1134      5075       Rohit         MI  Sri Lanka   56  Female  Unknown Coach     Cricket 2022-01-13       2472   2731              740342     15        9      4        5         30278        10057    Chennai       Cloudy        Win       9               4   81903          UPI                 9722              26              20       2474         745545                 65    40335               2                   1.0
26         1072      5157      Hardik         MI  Sri Lanka   26    Male  Unknown Coach    Football 2023-12-05        450   2338              740342     18        7      6        5         16432        10057    Gujarat        Sunny       Lose       1               4   83383         Cash                 5504              60              18       1890         743130                 70    26489               1                   0.0
27         1017      5126     Ronaldo         MI    England   48    Male   Rahul Dravid      Tennis 2021-11-22        178   2338              220096    135        1      9        1          4958        10057  Bangalore        Rainy       Draw       1               4   84542          UPI                15724              96               4        120         222612                168    15015               1                   0.5
28         1131      5028       Virat     Lakers      India   35    Male  Unknown Coach     Cricket 2021-11-22       1907   1687              740343    165        0      8        5         30278        10057      Delhi        Rainy       Draw       1               4   84861          UPI                 1251              60              27       3101         743937                209    40335               1                   0.5
29         1059      5086      Bumrah     Lakers  Australia   35  Female  Unknown Coach  Basketball 2023-03-02       3030   1080              740343    180        6      1        1         30278        10057     Mumbai        Rainy        Win       8               4   80095         Cash                12429              73              28       1427         744453                199    40335               2                   1.0
30         1013      5140       Messi  Barcelona      India   32    Male   Rahul Dravid    Football 2021-03-04       1907   2777              740342     92        9      1        3         28501        10696      Delhi        Rainy       Lose       9               2   81283         Cash                 9722               1              23       3102         745026                125    39197               1                   0.0
31         1089      5045       Messi  Barcelona      India   39  Female  Unknown Coach    Football 2023-04-25       2535   2338              740342     99        9      0        0         30278        17623    Kolkata        Rainy        Win       8               4   80981   Netbanking                 9722              88              21       1455         745215                117    47901               2                   1.0
32         1129      5111    Joe Root         MI  Australia   39    Male   Rahul Dravid    Football 2023-04-25       3026   2338              740343    158        8      9        1         32600        13146  Bangalore        Rainy        Win       1               4   81565   Netbanking                 9722               7              22       1346         745707                205    45746               1                   1.0
33         1091      5044       Rohit        KKR      India   28    Male  Unknown Coach     Cricket 2021-05-27       3066   2338              250729    187        6      4        4         30278        15677     Mumbai        Rainy       Draw       1               4   80735         Cash                14758              60              25       1214         256133                227    45955               1                   0.5
34         1198      5084      Bumrah  Barcelona  Sri Lanka   47  Female  Unknown Coach       other 2020-12-05       1907   1768              713588     78        1      2        3         23059         1988      Delhi       Cloudy       Draw       6               4   80448  Credit Card                 8922              60               9       4612         717263                 98    25047               2                   0.5
35         1034      5017     Ronaldo        RCB  Australia   58    Male     John Smith    Football 2023-11-20       1907   2365              740342    175        1      4        0         22991        10057     Mumbai        Sunny        Win       6               1   81433  Credit Card                13058             120               7       2858         744614                189    33048               1                   1.0
36         1080      5093      Bumrah        RCB  Australia   57  Female  Unknown Coach      Tennis 2020-03-22       1907   1730              740342    139        3      0        0         30278         2525     Mumbai  Unspecified        Win       1               5   80876          UPI                 9722              68              21        761         743979                145    32803               2                   1.0
37         1163      5149       Dhoni     Lakers  Australia   26    Male  Unknown Coach     Cricket 2023-05-12       1907   2338              369408     95        2      1        0         30278         2000  Bangalore        Sunny        Win       9               4   82575         Cash                12407              60              26       2366         373653                102    32278               1                   1.0
38         1049      5032       Smith        RCB  Sri Lanka   57  Female  Unknown Coach       other 2021-12-09       1907   2338              555903     88        3      0        5         30278        10057    Kolkata       Cloudy       Draw       1               4   81133         Cash                 9722              60              12       4206         560148                114    40335               2                   0.5
39         1131      5125       Smith        RCB      India   52    Male  Unknown Coach  Basketball 2023-12-05       1132   2338              683275    145        6      8        0         37459        14224  Bangalore        Rainy       Draw       1               5   80671  Credit Card                13833              88               6       4902         686745                181    51683               1                   0.5
40         1133      5169       Messi        KKR      India   41  Female  Unknown Coach  Basketball 2022-09-18       1907   2338              740342    121        7      4        2          2826        17165      Delhi       Cloudy        Win       6               4   83318         Cash                 6443              98               3       3919         744587                155    19991               2                   1.0
41         1190      5161       Virat        RCB      India   13  Female  Unknown Coach    Football 2021-09-16       1907   2036              534886     61        0      8        4          4787        10623  Bangalore  Unspecified        Win       1               4   81783          UPI                 9576              15              20       2043         538829                101    15410               2                   1.0
42         1145      5027       Virat        CSK      India   27  Female     John Smith      Tennis 2023-04-10       5231   2338              740342    196        1      4        5         38750        10825  Bangalore        Sunny       Lose       1               4   80066  Credit Card                 9722              32              24       3376         747911                230    49575               2                   0.0
43         1161      5166    Joe Root        CSK      India   45  Female  Unknown Coach  Basketball 2021-05-31       1907    923              740342    135        4      4        4         43841        10057     Mumbai  Unspecified       Lose       1               4   82090   Netbanking                 9722              60              21        834         743172                171    53898               2                   0.0
44         1094      5146    Joe Root        CSK      India   44    Male   Rahul Dravid  Basketball 2020-04-07       1907   2338              740343    125        8      6        3         30278        10057  Bangalore        Sunny        Win       1               4   80233         Cash                 9722              18              13       1564         744588                171    40335               1                   1.0

In [ ]:
df.reset_index(drop=True,inplace=True)

In [ ]:
print(df.to_string())

      Player_Id  Match_Id Player_Name       Team    Country  Age  Gender     Coach_Name  Sport_Type Match_Date  Match_Fee  Bonus  Sponsorship_Amount  Score  Assists  Goals  Wickets  Ticket_Sales  Merch_Sales      Venue      Weather Win_Status  Rating  Feedback_Score  Fan_Id Payment_Mode  Fan_Purchase_Amount  Minutes_Played  Matches_Played  Fan_Count  Total_Earning  Performance_Score  Revenue  Gender_Numeric  Win_Status Numerical
0          1102      5082       Virat        CSK      India   17    Male   Rahul Dravid    Football 2023-02-13       1907   2338              287941     13        0      1        5         37356        10057    Chennai  Unspecified        Win       5               4   81006         Cash                 8970               1               3       2337         292186                 36    47413               1                   1.0
1          1179      5034       Virat        KKR      India   23    Male  Unknown Coach      Tennis 2022-12-05       1907   2338              740342     90        9      7        0         18655         7745  Bangalore  Unspecified       Draw      10               4   80048   Netbanking                 9722              60              11        805         744587                129    26400               1                   0.5
2          1014      5068      Bumrah        KKR      India   60    Male  Unknown Coach  Basketball 2024-01-22       1907     67              740343     76        9      8        0         30278        14535  Bangalore        Rainy       Draw       1               4   81929  Credit Card                 9722              12               2        278         742317                118    44813               1                   0.5
3          1071      5195    Joe Root     Lakers  Australia   20   Other  Unknown Coach    Football 2023-05-12        387   2338              740343    108        1      3        3         30278        10057     Mumbai        Sunny       Lose       1               4   81525   Netbanking                 9393              33              28        787         743068                131    40335               3                   0.0
4          1188      5139       Smith        KKR  Sri Lanka   58   Other  Unknown Coach    Football 2024-01-23       1907   2338              740343     30        4      1        1         30278        10057  Bangalore  Unspecified       Draw       2               4   80328         Cash                 9722              62              11       1332         744588                 45    40335               3                   0.5
5          1020      5187       Virat        CSK  Australia   33    Male  Unknown Coach  Basketball 2021-08-07       1907   2338              740342    121        9      1        3          8839         3104    Chennai       Cloudy        Win       7               1   82657  Credit Card                 9722              66              23       4372         744587                154    11943               1                   1.0
6          1102      5026      Hardik     Lakers  Sri Lanka   10    Male   Rahul Dravid     Cricket 2022-05-19       1907   2925              730707    106        3      1        5         30417        10057    Kolkata        Sunny       Lose       1               3   84529          UPI                17522             107              23       3147         735539                135    40474               1                   0.0
7          1121      5055      Hardik        RCB      India   30  Female  Unknown Coach    Football 2024-02-08        761   2338              740342     53        7      5        3          3528        10057  Bangalore        Rainy       Lose       6               4   80587  Credit Card                 5898              60              18       2345         743441                 94    13585               2                   0.0
8          1074      5022       Virat        KKR      India   11    Male     John Smith      Tennis 2023-12-03       1907   2338              835031    132        0      6        2         27302        13721  Bangalore       Cloudy        Win       1               3   83205   Netbanking                  240              59              12       3449         839276                158    41023               1                   1.0
9          1116      5020     Ronaldo     Lakers  Australia   38  Female  Unknown Coach    Football 2023-12-03        909   2338              740342    155        9      1        0         30456        10057  Bangalore        Rainy       Lose       1               4   83851         Cash                 9722              91               7       1009         743589                176    40513               2                   0.0
10         1052      5152      Hardik     Lakers    England   50  Female     John Smith    Football 2023-12-05       1907   1846              740342     70        0      8        0         39669        18222  Bangalore       Cloudy        Win       1               4   84659   Netbanking                 7545              60               9        935         744095                 94    57891               2                   1.0
11         1001      5054   Anonymous     Lakers  Sri Lanka   53    Male  Unknown Coach      Tennis 2023-03-03       1907   1890              996837    165        1      1        1         30278        10057      Delhi        Rainy        Win       1               4   84398         Cash                 9722              15              28       3518        1000634                174    40335               1                   1.0
12         1087      5045       Rohit         MI      India   56  Female     John Smith    Football 2023-07-07       1907   2338              597941     66        0      7        1         30278        10057  Bangalore        Rainy       Lose       5               1   84044  Credit Card                12815              65               5       3787         602186                 91    40335               2                   0.0
13         1037      5054    Joe Root        CSK    England   45    Male     John Smith       other 2023-12-05       1907   2338              811576    108        1      8        5         14156        10543  Bangalore        Sunny        Win       8               3   82604         Cash                10842             112              17        495         815821                154    24699               1                   1.0
14         1129      5095    Joe Root        CSK      India   14  Female   Rahul Dravid  Basketball 2022-08-21       1907    122              740343    166        0      9        0         30278         8106  Bangalore        Rainy        Win       8               4   82023   Netbanking                 2254              60              16       3592         742372                193    38384               2                   1.0
15         1020      5109    Joe Root        CSK  Sri Lanka   13  Female  Unknown Coach      Tennis 2021-11-14       2632   2338              740342     85        9      9        3         30278         7054    Gujarat        Rainy        Win       1               4   84603         Cash                 9722              60               1       2935         745312                142    37332               2                   1.0
16         1048      5079       Smith  Barcelona  Australia   41    Male  Unknown Coach    Football 2021-06-12       1620   2338              740342     32        9      3        4         28270        10057  Bangalore       Cloudy        Win      10               4   81790  Credit Card                15884               0              15        905         744300                 75    38327               1                   1.0
17         1169      5112       Messi  Barcelona  Australia   44  Female  Unknown Coach    Football 2023-12-05       1427   2338              369706     41        5      9        4         38521         8764     Mumbai        Rainy        Win       1               3   82789   Netbanking                19875               6               8       1827         373471                 94    47285               2                   1.0
18         1187      5060      Bumrah        CSK      India   52    Male  Unknown Coach       other 2023-12-05       1907   2338              446653    111        2      3        3         30278         2084    Chennai       Cloudy        Win       1               4   82184          UPI                 8796              19              24       3722         450898                136    32362               1                   1.0
19         1014      5136       Smith        KKR      India   42    Male  Unknown Coach    Football 2020-03-21       1907   2267              474567    125        8      2        5         30278        13454  Bangalore        Rainy        Win       1               1   80538         Cash                 9722             118              24       2580         478741                167    43732               1                   1.0
20         1189      5005    Joe Root        KKR      India   41  Female  Unknown Coach  Basketball 2022-01-20       1907    189              740342    154        4      2        4         30278        10057     Mumbai        Rainy        Win       8               1   84784  Credit Card                 7650              38              23       4597         742438                184    40335               2                   1.0
21         1189      5038       Virat  Barcelona  Sri Lanka   42  Female  Unknown Coach    Football 2022-05-17       1907   2338              786510    105        5      8        4          1440        14806  Bangalore        Rainy       Draw       1               1   80305   Netbanking                 9722              60              26       4806         790755                155    16246               2                   0.5
22         1107      5168       Virat         MI  Sri Lanka   20    Male  Unknown Coach  Basketball 2022-07-05       3412   2620              262307    112        5      4        4         32080         9882    Gujarat        Rainy        Win       3               1   80724         Cash                13804              60               6        111         268339                150    41962               1                   1.0
23         1063      5004       Messi        CSK      India   28  Female  Unknown Coach  Basketball 2020-01-10       4086   1343              740343    122        5      4        0         10987        12869      Delhi        Rainy        Win       7               4   82435         Cash                11031              60              10       2302         745772                144    23856               2                   1.0
24         1130      5169   Anonymous        CSK      India   16    Male  Unknown Coach      Tennis 2022-10-13       1907   2090              740342    113        7      0        0         30278        10057    Gujarat       Cloudy        Win       1               4   82340  Credit Card                12543              60               0       1650         744339                127    40335               1                   1.0
25         1134      5075       Rohit         MI  Sri Lanka   56  Female  Unknown Coach     Cricket 2022-01-13       2472   2731              740342     15        9      4        5         30278        10057    Chennai       Cloudy        Win       9               4   81903          UPI                 9722              26              20       2474         745545                 65    40335               2                   1.0
26         1072      5157      Hardik         MI  Sri Lanka   26    Male  Unknown Coach    Football 2023-12-05        450   2338              740342     18        7      6        5         16432        10057    Gujarat        Sunny       Lose       1               4   83383         Cash                 5504              60              18       1890         743130                 70    26489               1                   0.0
27         1017      5126     Ronaldo         MI    England   48    Male   Rahul Dravid      Tennis 2021-11-22        178   2338              220096    135        1      9        1          4958        10057  Bangalore        Rainy       Draw       1               4   84542          UPI                15724              96               4        120         222612                168    15015               1                   0.5
28         1131      5028       Virat     Lakers      India   35    Male  Unknown Coach     Cricket 2021-11-22       1907   1687              740343    165        0      8        5         30278        10057      Delhi        Rainy       Draw       1               4   84861          UPI                 1251              60              27       3101         743937                209    40335               1                   0.5
29         1059      5086      Bumrah     Lakers  Australia   35  Female  Unknown Coach  Basketball 2023-03-02       3030   1080              740343    180        6      1        1         30278        10057     Mumbai        Rainy        Win       8               4   80095         Cash                12429              73              28       1427         744453                199    40335               2                   1.0
30         1013      5140       Messi  Barcelona      India   32    Male   Rahul Dravid    Football 2021-03-04       1907   2777              740342     92        9      1        3         28501        10696      Delhi        Rainy       Lose       9               2   81283         Cash                 9722               1              23       3102         745026                125    39197               1                   0.0
31         1089      5045       Messi  Barcelona      India   39  Female  Unknown Coach    Football 2023-04-25       2535   2338              740342     99        9      0        0         30278        17623    Kolkata        Rainy        Win       8               4   80981   Netbanking                 9722              88              21       1455         745215                117    47901               2                   1.0
32         1129      5111    Joe Root         MI  Australia   39    Male   Rahul Dravid    Football 2023-04-25       3026   2338              740343    158        8      9        1         32600        13146  Bangalore        Rainy        Win       1               4   81565   Netbanking                 9722               7              22       1346         745707                205    45746               1                   1.0
33         1091      5044       Rohit        KKR      India   28    Male  Unknown Coach     Cricket 2021-05-27       3066   2338              250729    187        6      4        4         30278        15677     Mumbai        Rainy       Draw       1               4   80735         Cash                14758              60              25       1214         256133                227    45955               1                   0.5
34         1198      5084      Bumrah  Barcelona  Sri Lanka   47  Female  Unknown Coach       other 2020-12-05       1907   1768              713588     78        1      2        3         23059         1988      Delhi       Cloudy       Draw       6               4   80448  Credit Card                 8922              60               9       4612         717263                 98    25047               2                   0.5
35         1034      5017     Ronaldo        RCB  Australia   58    Male     John Smith    Football 2023-11-20       1907   2365              740342    175        1      4        0         22991        10057     Mumbai        Sunny        Win       6               1   81433  Credit Card                13058             120               7       2858         744614                189    33048               1                   1.0
36         1080      5093      Bumrah        RCB  Australia   57  Female  Unknown Coach      Tennis 2020-03-22       1907   1730              740342    139        3      0        0         30278         2525     Mumbai  Unspecified        Win       1               5   80876          UPI                 9722              68              21        761         743979                145    32803               2                   1.0
37         1163      5149       Dhoni     Lakers  Australia   26    Male  Unknown Coach     Cricket 2023-05-12       1907   2338              369408     95        2      1        0         30278         2000  Bangalore        Sunny        Win       9               4   82575         Cash                12407              60              26       2366         373653                102    32278               1                   1.0
38         1049      5032       Smith        RCB  Sri Lanka   57  Female  Unknown Coach       other 2021-12-09       1907   2338              555903     88        3      0        5         30278        10057    Kolkata       Cloudy       Draw       1               4   81133         Cash                 9722              60              12       4206         560148                114    40335               2                   0.5
39         1131      5125       Smith        RCB      India   52    Male  Unknown Coach  Basketball 2023-12-05       1132   2338              683275    145        6      8        0         37459        14224  Bangalore        Rainy       Draw       1               5   80671  Credit Card                13833              88               6       4902         686745                181    51683               1                   0.5
40         1133      5169       Messi        KKR      India   41  Female  Unknown Coach  Basketball 2022-09-18       1907   2338              740342    121        7      4        2          2826        17165      Delhi       Cloudy        Win       6               4   83318         Cash                 6443              98               3       3919         744587                155    19991               2                   1.0
41         1190      5161       Virat        RCB      India   13  Female  Unknown Coach    Football 2021-09-16       1907   2036              534886     61        0      8        4          4787        10623  Bangalore  Unspecified        Win       1               4   81783          UPI                 9576              15              20       2043         538829                101    15410               2                   1.0
42         1145      5027       Virat        CSK      India   27  Female     John Smith      Tennis 2023-04-10       5231   2338              740342    196        1      4        5         38750        10825  Bangalore        Sunny       Lose       1               4   80066  Credit Card                 9722              32              24       3376         747911                230    49575               2                   0.0
43         1161      5166    Joe Root        CSK      India   45  Female  Unknown Coach  Basketball 2021-05-31       1907    923              740342    135        4      4        4         43841        10057     Mumbai  Unspecified       Lose       1               4   82090   Netbanking                 9722              60              21        834         743172                171    53898               2                   0.0
44         1094      5146    Joe Root        CSK      India   44    Male   Rahul Dravid  Basketball 2020-04-07       1907   2338              740343    125        8      6        3         30278        10057  Bangalore        Sunny        Win       1               4   80233         Cash                 9722              18              13       1564         744588                171    40335               1                   1.0